### ISSUE TITLE
What's the meaning by "Points above vertex id 845 are not defined on the reference" in ibug2did.txt?

### ISSUE THREAD

**Issue by wguo68** [patrikhuber/eos#101]
I don't understand the meaning of "Note: Points above vertex id 845 are not defined on the reference and thus not available in all model resolutions."? 
I also think the mapping from landmarks to vertices is a little complex. Why use three file (image_0010.pts,ibug2did.txt,model_contours.json)to do this simple task?

**Comment by patrikhuber** [comment]
Well, the reference has 845 vertices. So, naturally, all points in the mapping that have a vertex id higher than the number of vertices of the model you're using, will not be defined in that model. (So you should uncomment them in the mappings file).

**Comment by wguo68** [comment]
Thank you
