### ISSUE TITLE
Using cv::solvePnP with eos

### ISSUE THREAD

**Issue by wguo68** [patrikhuber/eos#104]
I calibrated the color camera (std::vector<T> intrinsic_params = {516.05,516.35,317.47,250.06};). But the fitting result is too bad. What's wrong I made?
I used cv::solvePnP to solve the camera pose. It seems cv::solvePNP can't give correct pose!
![pers](https://cloud.githubusercontent.com/assets/4994038/23054608/f238e7bc-f51b-11e6-9f38-3339cc6647ac.jpg)

**Comment by patrikhuber** [comment]
That's interesting. I'm not using `cv::solvePnP`, so I'm not sure why its estimation is wrong. Good idea of increasing the prior-weight to check the result. I'm not sure what's in your intrinsics vector, but most likely something is wrong there? I would suggest you play around with this vector?

I will tag this as "invalid" as it's a problem with `cv::solvePnP`, not eos. However I'm happy if you continue the investigation here as `cv::solvePnP` might be interesting to other people.

**Comment by wguo68** [comment]
I am sorry I made a mistake  I use a color image from another different camera (1920*1680), but the calibrated camera is the 640*480  color camera.

**Comment by patrikhuber** [comment]
Interesting observation with `cv::solvePnP`. If I was you I would find out which landmarks cause the fitting result to get worse.

Also if you use the contour too (all 68, like in eos), it should get better again. Nevertheless it would be interesting to know which landmarks make it worse in above case.

**Comment by wguo68** [comment]
I will try it later. now I want to do 3d registration to do facial  reconstruction using depth map or 3d scan model.

**Comment by patrikhuber** [comment]
Actually it occurred to me that `cv::solvePnP` estimates a perspective camera matrix, so this is not compatible with the **linear** shape fitting from eos. A perspective camera model introduces nonlinearity. I'll close this issue, I think it's pretty much solved.
