### ISSUE TITLE
Extract non-frontal mesh

### ISSUE THREAD

**Issue by AaronJackson** [patrikhuber/eos#106]
Hi,

I am wondering if there is a simple way to extract the mesh after the rotation, translation and scale are applied, since currently it only appears to output a frontal mesh and the 2D projection. At the moment I am using projection, but this will distort the z component. 

```
void write_vertices(const core::Mesh& mesh, glm::mat4x4 modelview, glm::mat4x4 projection, glm::vec4 viewport)
{
  for (const auto& vert : mesh.vertices) {
    const auto p = glm::project({vert[0],vert[1],vert[2]}, modelview, projection, viewport);
    std::cout << p[0] << "," << p[1] << "," << p[2] << std::endl;
  }
};
```
Am I missing something? Any help greatly appreciated.

Thanks,

Aaron.

**Comment by patrikhuber** [comment]
Hi!

I'm not sure I understand what you want to do. Is [`write_obj`](https://github.com/patrikhuber/eos/blob/master/include/eos/core/Mesh.hpp#L65) not what you need?

**Comment by AaronJackson** [comment]
Thanks for your reply. ``write_obj`` appears to output a frontal face which does not have spatial correspondence with the input image (unlike the projection). I am guessing some transformations need to be applied to the points. Did I run something wrong?

**Comment by patrikhuber** [comment]
If you want the mesh given the current pose, then indeed your approach is right. You can also see [how draw_wireframe draws the mesh](https://github.com/patrikhuber/eos/blob/master/examples/fit-model.cpp#L119-L127). If you want the z-coordinates in world space, you can easily compute that separately by just multiplying each vertex with the `modelview` matrix (without doing the subsequent projection). If you need more info about that I suggest having a look at the Shirley & Marscher Computer Graphics book or for example [this page](http://www.songho.ca/opengl/gl_transform.html).

**Comment by AaronJackson** [comment]
Thanks Patrick, that makes sense. I appreciate your help.

**Comment by patrikhuber** [comment]
Great! :-)
