### ISSUE TITLE
When to release the next version?

### ISSUE THREAD

**Issue by ming81** [patrikhuber/eos#11]

**Comment by patrikhuber** [comment]
Your question is a bit weird, without even knowing what the next version would contain. What are you expecting? What are you currently missing?

**Comment by ming81** [comment]
I think you have your version plan! This version had some bug, such as black lines, ear next to the texture mapping problem.
I think you'll get this program better than FaceGen!

**Comment by patrikhuber** [comment]
You're right, this is on my version plan ;-)
There will surely be improvements soon, but I'd hate to make a specific commitment. I'm working on it ;-)

**Comment by patrikhuber** [comment]
I'm closing this, since it's not really a question with an answer. There will be continuing commits anyway, and some neat improvements in the very near future :-)
