### ISSUE TITLE
Error loading the Morphable Model

### ISSUE THREAD

**Issue by flyingzhao** [patrikhuber/eos#111]
I load the model sfm_shape_1724.bin, but an error occurs. I also test with other model. Except sfm_shape_3448, the same error occurs with other three model. Can you give me some help?

![default](https://cloud.githubusercontent.com/assets/9637913/23884669/1c697e70-08a9-11e7-840d-534dde9a5786.PNG)

**Comment by patrikhuber** [comment]
This is most likely a version mismatch, you are taking the wrong model versions with the wrong version of the software. You can check the following:

A) Does it work with the default model of the same version of the code? (sfm_shape_3448.bin)

B) Check your eos version, what exact version (tag) you're using

C) Check which models you downloaded (pre-v0.12.0 or v0.12.0 and newer), make sure you're using the correct ones that match your eos version, and re-download the new ones if necessary. Please read the [release notes of v0.12.0](https://github.com/patrikhuber/eos/releases).

**Comment by flyingzhao** [comment]
My tag is v0.10.1. Code can work well with defalt model. My tag is v0.10.0. 

You are right. I download pre-v0.12.0 model and it works well. Thank you very much!

**Comment by flyingzhao** [comment]
But somethong worse happened.You can see the image. I guess that it is because the wrong landmak mapping. Can you give me some help?

code like this

`fit-model.exe -i data/1.jpg -o out/111 -m ../share/sfm_shape_16759.bin -b ../share/expression_blendshapes_16759.bin 

Finished fitting and wrote result mesh and isomap to files with basename "111".`

![111 isomap](https://cloud.githubusercontent.com/assets/9637913/23894417/fe179702-08dc-11e7-8645-4a0657e15f7f.png)

**Comment by patrikhuber** [comment]
Great that it works now!

Regarding the 16k blendshapes, please read the file `errata.txt` in the model's download directory: http://www.cvssp.org/faceweb/3dmm/facemodels/shape/errata.txt.

**Comment by linengmiao** [comment]
Hi Patrik

I am facing the same issue, but with the default model. I get: "Error loading the Morphable Model: Error opening given file: ../share/sfm_shape_3448.bin"

Any suggestions?
