### ISSUE TITLE
Running 'fit-model' example

### ISSUE THREAD

**Issue by baricks** [patrikhuber/eos#114]
Coding n00b here, just trying to get this example up and running.

You mention that we should run 'fit-model' after installation. Where should we run that command? I've tried running it in the /build and /install folders and I get the same error: "fit-model: command not found". Any tips?

**Comment by patrikhuber** [comment]
That really depends on your IDE/Generator - just use your file browser to find the executable. I recommend you run the INSTALL target and then run the executable from the installation directory (the one you've set, see the README.md) - that way, all the paths to the files will be correct and you don't need to specify anything.

**Comment by baricks** [comment]
I generated the Unix Makfiles. Tried running this command: "fit-model-simple -m ../share/sfm_shape_3448.bin -p ../share/ibug2did.txt -i data/image_0010.png -l data/image_0010.pts"

When I run "open fit-model-simple" on the executable in install/bin, the process exits.

**Comment by patrikhuber** [comment]
I don't know what "open" does, but to run an executable in Linux in your local directory you need to prefix it with `./`, so try `./fit-model-simple`. And run `ls -la` to make sure the executable is really there.

PS: For the future I recommend you ask such generic Linux questions on a site like [stackoverflow.com](stackoverflow.com), as this is not about the eos library. I'm going to close this ticket as it's not an issue of eos, but feel free to reply here nonetheless.
