### ISSUE TITLE
Expression transfer

### ISSUE THREAD

**Issue by ch4uz** [patrikhuber/eos#115]
How can I make an expression transfer from a realtime mesh (made from eos) to a loaded mesh (loaded before, but also made from eos)?

**Comment by patrikhuber** [comment]
Have a look at our [recent paper](https://www.patrikhuber.ch/files/Video_Fitting_SPL_2016.pdf), equation (4). You can transfer the psi's from one face to another.

**Comment by ch4uz** [comment]
Thanks, it worked!
Now, another question:
How I improve the expression animations? I want to be able to see the cheeks of the model moving when transfering expressions.

**Comment by patrikhuber** [comment]
Cool. As to your new question, I guess you need some sort of real-time window to display the model and then linearly interpolate the blendshape weights from the original value to the new value? Not sure really what you mean but this goes beyond this GitHub issue - I'll therefore close it, but feel free to reply nevertheless with your findings!
