### ISSUE TITLE
MatrixXf::Zero weird problem

### ISSUE THREAD

**Issue by chrisluu** [patrikhuber/eos#116]
Hi, I found that the function "MatrixXf::Zero()" in leaner_shape_fitting.hpp runs very very slow, it should't be this, it's very weird, do you have any idea about that problem?

MatrixXf V_hat_h = MatrixXf::Zero(4 * num_landmarks, num_coeffs_to_fit);
MatrixXf P = MatrixXf::Zero(3 * num_landmarks, 4 * num_landmarks);

Thanks & Best Regards,
Chris

**Comment by patrikhuber** [comment]
Hi,
What is "very very slow"? How many milliseconds/microseconds, and how large are the matrices? Please provide some exact numbers.

**Comment by patrikhuber** [comment]
@chrisluu Any progress on this? Otherwise I'll close as invalid.
