### ISSUE TITLE
Different results, matrix multiplication

### ISSUE THREAD

**Issue by ch4uz** [patrikhuber/eos#117]
When multiplying blendshape matrix by blendshapes coefficients using cv Mat, I obtain different results than multiplying using eigen matrix ( using to_matrix and to_vector methods that are in eos ). The difference is low, but is making weird results. Why is this happening?

**Comment by patrikhuber** [comment]
If the difference is low, how is it making weird results?
Are the coefficients identical? Where exactly are the differences and how big?

**Comment by ch4uz** [comment]
I just noticed that in the function fit_shape_and_pose I was using different parameters. Now is everything okay.
