### ISSUE TITLE
CVSSP full models download link down?

### ISSUE THREAD

**Issue by Larumbergera** [patrikhuber/eos#118]
Hi Patrik,

with the version v0.12.0 you said: 
"There are some breaking changes in this release and models have to be re-downloaded in the new format."
However, I can't download the high resolution models from the cvssp server... link is down. 
How can I download models?

Thanks,

Andoni.

**Comment by patrikhuber** [comment]
Hi,

Sorry to hear the server is down! That is unexpected, thank you for reporting it. Can you please write to cvssp-facemodel@surrey.ac.uk? I think most people are already on Easter holidays, so it might be a while until you will get a reply.

In the meantime, I hope the 3448 model on the repo will work for you.

**Comment by Larumbergera** [comment]
Yes, 404 Not Found. I'll have to wait...
 
Thanks,

Andoni.

**Comment by patrikhuber** [comment]
The link is up from our side and I've also just verified and it looks all fine. It looks like it was never down actually. If you continue experiencing problems regarding the download, please contact cvssp-facemodel@surrey.ac.uk. Thanks.
