### ISSUE TITLE
Making model eyes close

### ISSUE THREAD

**Issue by ch4uz** [patrikhuber/eos#120]
Im trying to make to make the 3d model close his eyes when the people in video close eyes too. Correct me if im wrong:

I need to get the vector of offsets that deform the reference mesh to close its eyes, and write it as a blendshape object in the blenshape.bin file. Is that right?

**Comment by patrikhuber** [comment]
That's a really interesting topic. Your suggested approach should definitely be a viable one, and one that should work right away within eos. I think there are many other approaches as well to do this, which come from the computer graphics domain - I didn't dig into this topic but you may find some literature or tutorials there as well.

**Comment by ch4uz** [comment]
It didnt work. You have any suggestion?

**Comment by patrikhuber** [comment]
I can't really give any more recommendations than I already gave without knowing more and why it didn't work.
