### ISSUE TITLE
Matrix not positive definite when to fit shape coeff?

### ISSUE THREAD

**Issue by wguo68** [patrikhuber/eos#121]
Suppose B is the shape basis whose column is a basis.
Eigen::Matrix<T, Eigen::Dynamic, Eigen::Dynamic> BtB = B.transpose()*B;
Eigen::Matrix<T, Eigen::Dynamic, Eigen::Dynamic> Btb = B.transpose()*b;
Eigen::Matrix<T, Eigen::Dynamic, 1> x = BtB.inverse()*Btb;
What's the problem? Is it because the PCA model has some problem? I used 40 basis. The total number is 63.  
BTW, I divided all coordinates by 1000 to convert unit from mm to m.

Thanks

**Comment by patrikhuber** [comment]
Is this an issue or was it your mistake and you closed it? Not really sure what's up with your post.
