### ISSUE TITLE
How the data of the bin file was arranged?

### ISSUE THREAD

**Issue by Adra8373** [patrikhuber/eos#122]
Hi 

I need to know how the data of the bin file was arranged. Does the mean was arranged as follows 
(x y z)' . Also I need to know how did you arrange the eigenvalues and the eigenvectors? and how can I get the alphas values?

**Comment by patrikhuber** [comment]
This is all very well documented in the `PcaModel` and `MorphableModel` classes, please read the documentation in these files.
