### ISSUE TITLE
Anyone know why the recovered camera pose is so bad? (3D-3D fitting)

### ISSUE THREAD

**Issue by wguo68** [patrikhuber/eos#123]
![face_fitting](https://cloud.githubusercontent.com/assets/4994038/25032591/f2592adc-2107-11e7-90b0-cd7824580577.jpg)

I used the kinect to scan 3d face and fitting using one image with known intrinsic param of the color .camera. I have  transformed the 3d model to color camera coordinate system.
It seems the camera pose is far sway from the real object?

**Comment by patrikhuber** [comment]
Not sure I really understand how you did what you were doing. But the fitting looks pretty good, except for the z offset. My guess is that you used eos's 2D-3D landmark fitting to fit 3D-3D. The fitting input is 2D coordinates (no 'z'), so it can't know where on your z-plane the fitting is.
I think you could modify the fitting function to work with 3D (x, y, z) landmarks input, it should just add another row for each point to the system of equations. I haven't thought that through though, just a pointer.

**Comment by patrikhuber** [comment]
I'll close this as it's not an eos issue. Feel free to re-open if you're still working on it.
