### ISSUE TITLE
Error in Eigen package when run in cmake

### ISSUE THREAD

**Issue by Adra8373** [patrikhuber/eos#124]
Hi 

I am trying to build the eos library using cmake, but I got this error

CMake Error at CMakeLists.txt:60 (find_package):
  By not providing "FindEigen3.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Eigen3", but
  CMake did not find one.

  Could not find a package configuration file provided by "Eigen3" with any
  of the following names:

    Eigen3Config.cmake
    eigen3-config.cmake

  Add the installation prefix of "Eigen3" to CMAKE_PREFIX_PATH or set
  "Eigen3_DIR" to a directory containing one of the above files.  If "Eigen3"
  provides a separate development package or SDK, be sure it has been
  installed.

However, I downloaded the Eigen package and I changed the environment variables to 
EIGEN3_INCLUDE_DIR    C:\eigen-eigen-67e894c6cd8f\Eigen

**Comment by patrikhuber** [comment]
You shouldn't have to download Eigen separately (that is, you can, if you want, but you don't have to).

Please make sure you've run

* `git submodule update --init --recursive`
* Delete the CMake cache, ideally delete the build directory (to make sure `EIGEN3_INCLUDE_DIR` does definitely not exist)

If instead you want to proceed with your own Eigen, I think you need to remove the "\Eigen" at the end of your `EIGEN3_INCLUDE_DIR`. 

In any case, something is not quite right with your local setup.

**Comment by Adra8373** [comment]
Hi 

Thanks for replying the problem was solved. But when I run the project I got this error 

Error while parsing command-line arguments: the option '--model' is required but
 missing
Use --help to display a list of options.
Press any key to continue . . .

Although I changed all the required paths.

**Comment by patrikhuber** [comment]
If you follow the instructions in the readme, and run the INSTALL target, it works without specifying any paths (i.e. the defaults). If you do want to specify them and it doesn't work, you have some typo, missing dash, wrong or missing quotes in the path, etc.
