### ISSUE TITLE
Error in run bfm-binary-to-cereal.cpp

### ISSUE THREAD

**Issue by Adra8373** [patrikhuber/eos#125]
Hi 

I am trying to run the bfm-binary-to-cereal.cpp file using VS2015 command prompt but I got this error 

bfm-binary-to-cereal.cpp(20): fatal error C1083: Cannot open include file: 'eos/
morphablemodel/MorphableModel.hpp': No such file or directory

Sorry for this question but I do not know how to run it, do I need to run any files before run this file? Could you tell me the steps of running this file please?

**Comment by patrikhuber** [comment]
This looks like a compile error and not an error in running. Please follow the readme w.r.t. compiling and installation.

**Comment by Adra8373** [comment]
Hi 

I run the bfm-binary-to-cereal project, but I got this error:

Error while parsing command-line arguments: the option '--input' is required but
 missing
Use --help to display a list of options.
Press any key to continue . . .

**Comment by patrikhuber** [comment]
Well, did you specify an `--input` argument? (i.e. the bfm raw binary file)

I'm closing this as it's not an eos library issue.

**Comment by Adra8373** [comment]
I tried to do that in the  bfm-binary-to-cereal.cpp but it has been accepted it 

("input,i", po::value<fs::path>(&bfm_file)->required("C:/phd/codes/eos-master (1)/eos/utils/eos/share/bfm.raw"),

**Comment by Adra8373** [comment]
This is the error 

Severity	Code	Description	Project	File	Line	Suppression State
Error	C2660	'boost::program_options::typed_value<boost::filesystem::path,char>::required': function does not take 1 arguments	bfm-binary-to-cereal	C:\phd\codes\eos-master (1)\eos\utils\bfm-binary-to-cereal.cpp	83

**Comment by Adra8373** [comment]
Many thanks for replying the problem solved.
