### ISSUE TITLE
Error while using my own model in fit-model-simple.cpp 

### ISSUE THREAD

**Issue by Adra8373** [patrikhuber/eos#126]
Hi 

I have my own model that contains shape mean, shape basis, eigenvalues and triangle list. But I do not have texture coordinates and PCA for texture. When I run fit-model-simple on my model I got this error: 

fit-model-simple.exe!eos::render::render_affine(const eos::core::Mesh & mesh, cv::Mat affine_camera_matrix, int viewport_width, int viewport_height, bool do_backface_culling) Line 81	C++

depthbuffer	{flags=1124024326 dims=2 rows=1024 ...}	cv::Mat

My question if I want to use my own model, do I need to have PCA for texture and texture coordinates as well?

**Comment by patrikhuber** [comment]
PCA texture (albedo) model is fundamentally different from texture remapping. Please read some literature (our VISAPP paper is a good start) and computer graphics book (with regards to texture coordinates).

eos does not require or use the PCA texture model, it's purely shape-model fitting (except for the fit-model-ceres prototype).
Regarding texture coordinates, many functionality in eos will work without them, but for obvious reasons, not things like texture remapping or rendering with texture.

**Comment by patrikhuber** [comment]
I'll close this as it's not an eos issue. Feel free to re-open if you're still working on it.
