### ISSUE TITLE
CMake error building python bindings

### ISSUE THREAD

**Issue by dhiegomaga** [patrikhuber/eos#127]
It's been mentioned before [here](https://github.com/pybind/python_example/issues/10#issuecomment-223570084), but I didn't find any solution. 
It's probably something stupid, but when I click "Configure" on CMake I get this error: 

**CMake Error at CMakeLists.txt:24 (pybind11_add_module):
  Unknown CMake command "pybind11_add_module".**

Not sure what to do here.

**Comment by patrikhuber** [comment]
I'm pretty sure you just need `git submodule update --init --recursive`, as described in our readme.

**Comment by dhiegomaga** [comment]
Ok, now it worked. Actually what I did wrong was that instead of running cmake with the **EOS_GENERATE_PYTHON_BINDINGS** I tried to use cmake directly from _eos/python/_. 

By the way, is there a reason for the -D before the flag name (i.e. **-DEOS_GENERATE_PYTHON_BINDINGS**) as it is in the readme?

**Comment by patrikhuber** [comment]
Good, yep, always run CMake from the project root.

The variable is called `EOS_GENERATE_PYTHON_BINDINGS`, the `-D` is CMake's syntax for defining a variable. If you run `cmake-gui` you'll see the actual variable name (also inside `CMakeLists.txt`).
