### ISSUE TITLE
"already defined" linking errors due to missing "inline" directives

### ISSUE THREAD

**Issue by babalex** [patrikhuber/eos#130]
There are some linking errors due to missing "inline" keyword in front of the function definitions in the following two places:
- line 238 in include/eos/fitting/contour_correspondence.hpp
- line 124 in include/eos/render/utils.hpp

**Comment by patrikhuber** [comment]
Thanks for reporting! I'm happy to accept a PR, otherwise I'll fix it as soon as I get to it :-)

**Comment by babalex** [comment]
Hi Patrik,

I am a newby with git, so I wasn't sure how to do pull requests. I think I
did it. Let me know if it worked out.

Alex.

**Comment by patrikhuber** [comment]
The PR looks great, you did exactly right :-) Will merge as soon as CI tests pass.

Thank you!

**Comment by patrikhuber** [comment]
Ah, a small comment: Usually it is advised to create a separate branch for a PR. If you do it in master, then you run into problems if you add more commits to master - they will then be added to the PR as well. So usually the workflow is: Create branch from master => Fix code, commit changes => Submit a PR from babalex:your_branch_with_fix to patrikhuber:master.

In this case it should be fine, as long as you don't commit anything new to master before I merge the PR.
