### ISSUE TITLE
Why people all use BFM in their papers? Is it because SFM only has 40 people in the database?

### ISSUE THREAD

**Issue by wguo68** [patrikhuber/eos#132]
BFM has 200 people in the database. So BFM is better than SFM?

**Comment by patrikhuber** [comment]
The BFM was published in 2009, the SFM in 2016. The SFM just started acquiring citations.

Who says the SFM has 40 people in the database? Please, go read our paper, before making such statements.

Thank you.

**Comment by wguo68** [comment]
I am sorry. How many people are used in the SFM database?

**Comment by Larumbergera** [comment]
Hi, 
In [this paper](https://www.researchgate.net/publication/285054377_A_Multiresolution_3D_Morphable_Face_Model_and_Fitting_Framework) you can find the information about the Surrey Face Model.

Regards,

Andoni.

**Comment by wguo68** [comment]
Thanks. There are 169 people in SFM and it is a Multiresolution MM. I remember in my programming ,it seems there is only 40 basis.  It may be my mistake.

**Comment by patrikhuber** [comment]
We keep around 60-65 shape basis vectors, which accounts for I think 95 or 99% of the variation in the training set - again, see the paper for details.
For fitting to landmarks, depending on your application, it actually may not make sense to use more than 10-20 basis vectors.

**Comment by wguo68** [comment]
Thank you. It seems only 6 blendshapes in blendshape model?

**Comment by patrikhuber** [comment]
Yes, as mentioned before, this is all described in our papers, and actually in README.md too.

**Comment by wguo68** [comment]
Could we add more  than 6 blendshapes ?

**Comment by patrikhuber** [comment]
You can add however many you want and/or replace the existing ones.
