### ISSUE TITLE
reference.obj kind of misleading?

### ISSUE THREAD

**Issue by dhiegomaga** [patrikhuber/eos#133]
So, in the [share folder](https://github.com/patrikhuber/eos/tree/master/share) there are some files used to do the fitting (including the identity model, expression model, contour vertex indices, etc...). But there is also a **reference.obj** file. I assumed that it was sort of the mean shape of the identity model, but then I learned that it wasn't in correspondance with the other files (i.e. [ibug_to_sfm.txt](https://github.com/patrikhuber/eos/blob/master/share/ibug_to_sfm.txt), [sfm_3448_edge_topology](https://github.com/patrikhuber/eos/blob/master/share/sfm_3448_edge_topology.json) ) because it only has 845 vertices, and these files have indices that go up to 3400. 

I also verified that the **out.obj** outputed by [fit-model](https://github.com/patrikhuber/eos/blob/master/examples/fit-model.cpp) has 3448 vertices, so I guess that is the actual size the algorithm is working with, not 845. Maybe removing or replacing **reference.obj** by a mean shape of the actual size of the model would be a good idea? Personally it made me very confused when trying to understand what the other files were for.

**Comment by patrikhuber** [comment]
Dhiego, in 3D-3D registration, most algorithm usually use a reference or template mesh, to which all scans get registered to. It can be the mean, one of the samples, or any mesh. The registration used to build the SFM works in a multi-resolution way and the 845 vertices reference mesh is the one it starts with. They are in correspondence actually. Please have a look at our VISAPP paper which contains all this information. Also any literature on 3D mesh registration will help you understand further.

All the files that you mention are also described in the readme in `share/`. Let me know if there is any particular thing in the documentation that could be improved.
