### ISSUE TITLE
fitting a flat and round face resulted in a long face

### ISSUE THREAD

**Issue by wguo68** [patrikhuber/eos#136]
![long_face](https://cloud.githubusercontent.com/assets/4994038/26272981/9445ddba-3d58-11e7-8d86-78f2991c2b65.jpg)

**Comment by patrikhuber** [comment]
Is there a question here? The fitting looks good to me. You can reproject the fitted vertices that correspond to the 2D landmarks back to the 2D image to see how well it fits, or even easier, use `draw_wireframe(...)`.

**Comment by wguo68** [comment]
I hope it is a flat and round face not a long face. For me ,it is not good enough. Maybe I must use more other kind of constrains.

**Comment by patrikhuber** [comment]
As I said use `draw_wireframe(...)` to check how good the fit is.

**Comment by wguo68** [comment]
![wg3](https://cloud.githubusercontent.com/assets/4994038/26282891/625e3fe0-3e4d-11e7-8625-b7454bb12025.jpg)
Is this better?
