### ISSUE TITLE
Matlab bindings error

### ISSUE THREAD

**Issue by Adra8373** [patrikhuber/eos#137]
Hi 

When I tried to the demo.m in matlab I got this error:

Undefined function 'fitting' for input arguments of type 'char'.

Error in eos.fitting.fit_shape_and_pose (line 42)
[ mesh, rendering_parameters ] = fitting(morphable_model, blendshapes, landmarks, landmark_mapper, image_width, image_height,
edge_topology, contour_landmarks, model_contour, num_iterations, num_shape_coefficients_to_fit, lambda);

Error in demo (line 14)
[mesh, render_params] = eos.fitting.fit_shape_and_pose(model_file, blendshapes_file, landmarks, landmark_mappings, image_width,
image_height);

Could you help me to solve it, please? 

Also, when I run cmake in windows 7 I wrote this command:

C:\phd\codes\eos-master (1)\eos\matlab>cmake -G"Visual Studio 14 2015 Win64" ..
-DEOS_GENERTE_MATLAB_BINDINGS=on

Is that right? could you tell me how can I run it in windows 7, please? 

Regards

**Comment by patrikhuber** [comment]
I think this looks like a problem with your system.
I don't really have time to maintain the Matlab bindings currently, and the focus is on C++ and the Python bindings. So in the latest eos release, they may not work anymore. It wouldn't be hard to make them work again though.

I'll close this as it was probably a problem with your system configuration.
