### ISSUE TITLE
fit_model without a landmark file

### ISSUE THREAD

**Issue by mikim** [patrikhuber/eos#138]
Hello @patrikhuber 

I succeeded to build eos in VS2017.

So I tried fit_model and found there is a landmark file which is, I guess, manually annotated.

So... is there a functionality to replace this landmark file? 

I'm wondering whether the following steps are possible.
- given an image
- missing a landmark file is auto-generated somehow, say dlib? if this functionality is not supported, and its mapping to sfm.
- get output model/texture

Since my plan is to modify eos to support video input.

Any advice will be appreciated. Thanks~ :)

**Comment by patrikhuber** [comment]
Hi,

Sure, that's what eos is made for. You can use it with any landmarks, for example dlib. There's of course no need to write a landmarks file to disk if all is done within the same app.
Many people have asked this question before, if you need more help, please browse through the closed issues.
