### ISSUE TITLE
Rendering parameter 'pose'

### ISSUE THREAD

**Issue by pawanvaishnav60** [patrikhuber/eos#139]
I am trying to create a virtual try on glasses system, using the dlib module I am getting the facial landmarks of a person in real time. Now I want to use these landmarks to fit a 3D face mesh so that I can fit the 3D sunglass model on it. 
I am using your 3D Morphable model for fitting, can you please demonstrate how to construct the 3D facial model from the rendering parameter 'pose'.

**Comment by patrikhuber** [comment]
eos contains a nice `fit-model` example app that runs you through all, just have a look at that. If you want to re-render in a different pose in C++, you can have a look at how [4dface](https://github.com/patrikhuber/4dface) does it, or better do it in OpenGL by yourself if it needs to be performant. If you need help on using dlib landmarks with eos, look through the (closed) GitHub Issues, many people have asked this before and there's extensive descriptions.

eos should be well-documented overall and has good examples. If you feel like a particular part is not well-documented please let me know how to improve it.
