### ISSUE TITLE
Is it possible to make this library be compatible  with cuda?

### ISSUE THREAD

**Issue by tangshi** [patrikhuber/eos#141]
I'm wondering that is it possible to make this library compatible with cuda which may speed up the library

**Comment by patrikhuber** [comment]
Hi,

I think the question is, what part of it? Definitely a lot of it can be parallelised, even to a GPU - like the matrix operations, and the ray-casting is massively parallel too. (I think someone parallelised that to OpenCL or OpenGL already in their branch of eos). So the answer is definitely yes.

**Comment by patrikhuber** [comment]
I'm going to close this as non-issue. I would love to hear about it if there is any progress on this.
