### ISSUE TITLE
the mesh vertices order and 3D point origin

### ISSUE THREAD

**Issue by ForestWang** [patrikhuber/eos#144]
Hi:
    thank your for your excellent work.
    for the 3D mesh vertices, which one is  the first? what's the order? for example, i want to get the mouth or eye vertices, how can i get it?

   another question is for the 3D mesh coordinates, where is the origin point(0,0,0)?

thank you very much

**Comment by patrikhuber** [comment]
Hi,
Thanks!
You can open the reference.obj in any 3D program like MeshLab or Blender to inspect the mesh and its vertices. I think the origin is somewhere around the nose, you can also check that in a 3D program.
If you want to inspect the mesh of the 3448 model, you can use `write_obj(...)` to save an instance of the model as obj.
