### ISSUE TITLE
Ceres error in Cmake

### ISSUE THREAD

**Issue by mortezab** [patrikhuber/eos#146]
Dear Patrik,
Thanks for sharing your code.

I download your latest code and try to configure it with Cmake for visual studio 2015. but this error appear:
"Could not find a package configuration file provided by "Ceres" with any of
  the following names:
    CeresConfig.cmake
    ceres-config.cmake "

Where can i find ceres ?

**Comment by patrikhuber** [comment]
You need to download Ceres, possibly build it if you're on Windows (don't remember whether they offer binaries), then set the path in https://github.com/patrikhuber/eos/blob/master/initial_cache.cmake.template.
