### ISSUE TITLE
How can i generate random faces with texture using this face model?

### ISSUE THREAD

**Issue by shanenian** [patrikhuber/eos#150]
How can i generate random faces with texture using this face model? Just like script_gen_random_head.m script from the official basel face model.

Thanks!

**Comment by patrikhuber** [comment]
Have a look at [`MorphableModel::draw_sample`](http://patrikhuber.github.io/eos/doc/classeos_1_1morphablemodel_1_1_morphable_model.html).

**Comment by patrikhuber** [comment]
I'm going to close this, feel free to re-open if you have specific issues with the library.
