### ISSUE TITLE
Generating a lower-resolution face model

### ISSUE THREAD

**Issue by Sar-Kerson** [patrikhuber/eos#151]
Hello.
In the code fit-model.cpp, it uses the default model file sfm_shape_3448.bin to generate the mesh.
But I want to make the surface more simplified, which means less vertices.
How can I generate sfm_shape_3448.bin and some files else depended  to do this?

**Comment by patrikhuber** [comment]
You could use the topology of the reference.obj. You could reduce the 3448 model to 845 vertices using that topology. If you want to keep the PCA bases orthogonal (or orthonormal), you may want to reorthogonalise after sub-selecting the lower-resolution basis.

**Comment by Sar-Kerson** [comment]
Hi, @patrikhuber ,
but how can I generate the *.bin files from the refernce.obj  via eos?
Just like in the example code fit-model.cpp, it needs 3 more files related to the sfm_shape_3448.bin.

**Comment by patrikhuber** [comment]
You need to write an app (in C++ or with the Python bindings) that does what I outlined above. I'd start with having a look at the documentation for the `MorphableModel` class and its members.

**Comment by patrikhuber** [comment]
I'm going to close this, feel free to re-open if you have specific issues with the library.
