### ISSUE TITLE
Can I Fit shape_model to face vertices from 3d scan?

### ISSUE THREAD

**Issue by yansfil** [patrikhuber/eos#153]
Hi: 
thank you for your excellent work.
I have 3d face vertices(1300 points) from kinect hd face. 
I want to make my 3d face model from 3d scan data.
So I want to know if I Fit shape_model(eos model) to face vertices from 3d scan?

**Comment by patrikhuber** [comment]
Hi!

Thank you and thanks for your interest.
Currently, eos doesn't contain functionality to fit to 3D meshes with other topologies (that would be dense 3D registration) or to 3D point clouds. You could use eos's 3DMM functionality though and find another library like PCL or maybe libigl and "glue" them together - it may require some work though.

**Comment by yansfil** [comment]
Thanks for your quick reply.
I want to know one more!
Can I modify 2D landmarks format(.pts) to 3D landmarks format(with depth)?
I want to make model more precisely.

**Comment by zaykl** [comment]
I think https://github.com/menpo/lsfm make help.

**Comment by patrikhuber** [comment]
> Can I modify 2D landmarks format(.pts) to 3D landmarks format(with depth)?

Well, see my answer above. It would need modifications to the landmark fitting code to incorporate the z coordinates when solving the linear systems! It might work quite well, but you need to think it through :-)

**Comment by bilelmnasser** [comment]
> Hi:
> thank you for your excellent work.
> I have 3d face vertices(1300 points) from kinect hd face.
> I want to make my 3d face model from 3d scan data.
> So I want to know if I Fit shape_model(eos model) to face vertices from 3d scan?

hi sir  , did you find any workground about your issue, currently i am in need of guidance toards your exact problem , any tip or help is much appreciated .
thanks a lot
