### ISSUE TITLE
Any idea about estimating camera in perspective projection?

### ISSUE THREAD

**Issue by helloyxc** [patrikhuber/eos#157]
Now， the EOS estimate camera in orthographic projection.
```
	fitting::ScaledOrthoProjectionParameters current_pose;
	current_pose = fitting::estimate_orthographic_projection_linear(image_points, model_points, true, image_height);
	fitting::RenderingParameters rendering_params(current_pose, image_width, image_height);
```

Do you have any idea or paper about estimating camera in perspective projection?

**Comment by patrikhuber** [comment]
There's many papers on estimating perspective projection. You will probably need a nonlinear optimiser.

I'll close this issue as it is not an issue with eos, but feel free to continue the discussion. Thanks!
