### ISSUE TITLE
How to make scan model and texture densely registered to the 3D model

### ISSUE THREAD

**Issue by zaykl** [patrikhuber/eos#158]
Hi Huber,

First, thx your work. Recently I have read your paper <A Multiresolution 3D Morphable Face Model and Fitting Framework>. And I think the section 2.2 3D scan data is useful for us build our new model. I have found lsfm framework. but this framework don't support texture registered to the model.

Can you please let know some more detail about this work.

**Comment by patrikhuber** [comment]
Thanks!

I'm not really sure what your question is. If you're looking to densely register 3D face scans, eos doesn't currently do that.
Please feel free to re-open if you have a more specific question or issue.

**Comment by zaykl** [comment]
Do you know some opensource project working on densely register 3D face scans? Thx.

**Comment by zaykl** [comment]
I read your paper while fitting 3DMM with photos, you train the SFM with scan faces dataset. So I would like to know how to train the new SFM by using the dataset I have.

**Comment by patrikhuber** [comment]
* If you need to register 3D data/scans (i.e. bring in dense correspondence), you can try scalismo from Basel, the N-ICP in menpo, and I think the lab of Wuhrer et al. have some code online as well.
* If your scans are already in dense correspondence, you can use the [pca functions](https://github.com/patrikhuber/eos/blob/master/include/eos/pca/pca.hpp) in eos (also available from the python bindings).
