### ISSUE TITLE
CMake GUI

### ISSUE THREAD

**Issue by rathaROG** [patrikhuber/eos#159]
Hi! I've got this problem..
```
CMake Error at CMakeLists.txt:4 (cmake_minimum_required):
  CMake 3.9.20170812-g71ee6 or higher is required.  You are running version
  3.9.4


Configuring incomplete, errors occurred!
```
What should I do?

**Comment by patrikhuber** [comment]
The error message pretty much says it. Download CMake 3.10.x: https://cmake.org/download/

You can also try to modify eos's CMakeLists and try with 3.9.4 but no guarantees that it'll work (you'll probably have to manually add the `/std:c++17` flag).

**Comment by rathaROG** [comment]
Thank you for your help! I thought v3.9.4 was newer or higher than 3.9.20170812-g71ee6.

**Comment by patrikhuber** [comment]
`3.9.20170812-g71ee6` is a nightly release (the number following the last dot is the date). All versions from thereon include the support for the C++17 flags in VS2017. At some point it would probably make sense to change that to 3.10.0 to avoid any confusion :-)
