### ISSUE TITLE
#error:  class template optional is only available with C++17

### ISSUE THREAD

**Issue by k-miracle** [patrikhuber/eos#162]
hello， @patrikhuber ,when I'm compiling the example/fit-model.cpp(Win10+VS2017),the code got an error:`error:  class template optional is only available with C++17`,that seems some problem when compile the code with C++14,and when I transform to C++17,I get other more errors.
ps: I've using python bindings correctly,but when I using C++,that seems a big trouble?any suggestions?Thank you!

**Comment by patrikhuber** [comment]
It seems like you may not have used cmake. In any case, please follow the steps in [README.md](https://github.com/patrikhuber/eos/blob/master/README.md) and [appveyor.yml](https://github.com/patrikhuber/eos/blob/master/appveyor.yml). Maybe you need to upgrade boost?
 Without knowing the error, nobody can say what's wrong with your setup. But the code compiles successfully on AppVeyor with cmake and VS2017.
