### ISSUE TITLE
error: optional: No such file or directory

### ISSUE THREAD

**Issue by thestrawh8** [patrikhuber/eos#164]
Hi,
Thanks for making such a good library I have problem with building. It points to the correct location of the header file but it throws the error header file not found. Can you please help me with this. 
Thanks 

luffykaizoku@luffy:/Desktop/build$ cmake ../eos/
-- Options:
-- EOS_BUILD_EXAMPLES: ON
-- EOS_BUILD_CERES_EXAMPLE: OFF
-- EOS_BUILD_UTILS: OFF
-- EOS_BUILD_DOCUMENTATION: OFF
-- EOS_GENERATE_PYTHON_BINDINGS: OFF
-- EOS_GENERATE_MATLAB_BINDINGS: OFF
-- Eigen3 found: TRUE, version: 3.3.3
-- Eigen3 include dir found at /home/luffykaizoku/Desktop/eos/3rdparty/eigen
-- OpenCV 2.x detected
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   system
--   filesystem
--   program_options
-- Boost found at /usr/include
-- Configuring done
-- Generating done
-- Build files have been written to: /home/luffykaizoku/Desktop/build
luffykaizoku@luffy:/Desktop/build$ make 
[ 16%] Building CXX object examples/CMakeFiles/fit-model.dir/fit-model.cpp.o
In file included from /home/luffykaizoku/Desktop/eos/examples/fit-model.cpp:21:0:
/home/luffykaizoku/Desktop/eos/include/eos/core/LandmarkMapper.hpp:27:20: fatal error: optional: No such file or directory
compilation terminated.
examples/CMakeFiles/fit-model.dir/build.make:62: recipe for target 'examples/CMakeFiles/fit-model.dir/fit-model.cpp.o' failed
make[2]: *** [examples/CMakeFiles/fit-model.dir/fit-model.cpp.o] Error 1
CMakeFiles/Makefile2:121: recipe for target 'examples/CMakeFiles/fit-model.dir/all' failed
make[1]: *** [examples/CMakeFiles/fit-model.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by patrikhuber** [comment]
Please read your error message: **`fatal error: optional: No such file or directory`**
As documented in the readme, you need a compiler with `<optional>` support. Please have a look at the readme.

**Comment by thestrawh8** [comment]
Thanks.
