### ISSUE TITLE
no optional head file found

### ISSUE THREAD

**Issue by xiejunyi-joey** [patrikhuber/eos#165]
hi 
I am just download the newest code.  When I am make this project.   The errors occur like this
ubuntu@xiejunyi:~/eos/build$ make -j4
Scanning dependencies of target generate-obj
Scanning dependencies of target fit-model
Scanning dependencies of target fit-model-simple
[ 16%] Building CXX object examples/CMakeFiles/generate-obj.dir/generate-obj.cpp.o
[ 33%] Building CXX object examples/CMakeFiles/fit-model.dir/fit-model.cpp.o
[ 50%] Building CXX object examples/CMakeFiles/fit-model-simple.dir/fit-model-simple.cpp.o
In file included from /home/ubuntu/eos/include/eos/render/render.hpp:28:0,
                 from /home/ubuntu/eos/examples/generate-obj.cpp:23:
/home/ubuntu/eos/include/eos/render/detail/render_detail.hpp:37:20: fatal error: optional: No such file or directory
compilation terminated.
examples/CMakeFiles/generate-obj.dir/build.make:62: recipe for target 'examples/CMakeFiles/generate-obj.dir/generate-obj.cpp.o' failed
make[2]: *** [examples/CMakeFiles/generate-obj.dir/generate-obj.cpp.o] Error 1
CMakeFiles/Makefile2:121: recipe for target 'examples/CMakeFiles/generate-obj.dir/all' failed
make[1]: *** [examples/CMakeFiles/generate-obj.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
In file included from /home/ubuntu/eos/include/eos/fitting/RenderingParameters.hpp:25:0,
                 from /home/ubuntu/eos/examples/fit-model-simple.cpp:25:
/home/ubuntu/eos/include/eos/fitting/orthographic_camera_estimation_linear.hpp:34:20: fatal error: optional: No such file or directory
compilation terminated.
What should I do? Is this optional file from Boost?

**Comment by patrikhuber** [comment]
Please read the [Readme](https://github.com/patrikhuber/eos/blob/master/README.md) and the [Release notes](https://github.com/patrikhuber/eos/releases). The latest eos versions require a C++ compiler which has `<optional>`.
Alternatively you can try replacing it with boost optional or something like akrzemi1/Optional but that's not something that will be supported going forward. I recommend updating your compiler.

**Comment by patrikhuber** [comment]
eos can now transparently use akrzemi1/Optional (it's included in the eos headers) when there is no `<optional>` yet. Currently there is only a check for `#ifdef __APPLE__` but I think it could be modified for other compilers too. The changes are merged into `master` and present from eos v0.15.0.
