### ISSUE TITLE
boost error

### ISSUE THREAD

**Issue by yuancorp** [patrikhuber/eos#166]
Hi,
i tried to compile example of eos and got this error on my MacPro.Note my boost is 1.60.
Undefined symbols for architecture x86_64:
  "boost::filesystem::path::replace_extension(boost::filesystem::path const&)", referenced from:
      _main in generate-obj.cpp.o
  "boost::program_options::validators::check_first_occurrence(boost::any const&)", referenced from:
      void boost::program_options::validate<float, char>(boost::any&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, float*, long) in generate-obj.cpp.o

**Comment by patrikhuber** [comment]
This looks to me like you might be mixing x64 and 32-bit compilation?

**Comment by yuancorp** [comment]
thanks
