### ISSUE TITLE
I don't know much about C++,but I want to use it in my python code

### ISSUE THREAD

**Issue by Ostnie** [patrikhuber/eos#167]
I have read your README file ,but I am still not understand what should I do,maybe because I only know some basic grammar about C . I guess maybe I can use it by "pip install eos-py" ,as you have said in your file. But I don't know how to use your program, I have read your demo.py, and when I run the demo.py , nothing has happened , Does this mean that my installation failed? Moreover， I did not find how to take a 3D face data enhancement operations, such as facial expressions and posture changes, these operations how to use it?many thanks, I'm really appreciate for your work!

**Comment by patrikhuber** [comment]
I suggest that you maybe step through the code with a debugger (for example in PyCharm if you want to start with Python) - this will help you see what's going on.

The GitHub issues are for bugs and problems with the eos library, not for help on programming. I suggest you ask programming questions in better suited help forums like [Stackoverflow](https://stackoverflow.com).
