### ISSUE TITLE
Hello!

### ISSUE THREAD

**Issue by bigHeadsStudio** [patrikhuber/eos#169]
thanks for your software I am interested in this field of research right now as an Independent investigator. Just starting... and I got stuck I can't find the ibug2did.txt file to run the most basic example, any pointers will be appreciated.

**Comment by patrikhuber** [comment]
Hi,
Apologies, this file got renamed a few months ago but I didn't see the reference to the old filename in the README.md. I've fixed the readme (6252159f9ea82636cfcb9ab82ee3e37669cc03d6), the file is `ibug_to_sfm.txt`.
