### ISSUE TITLE
Fitting 3D model

### ISSUE THREAD

**Issue by mortezab** [patrikhuber/eos#17]
Hi,

First of all so thanks for sharing your useful code. I'm going to fit 3d model of face into webcam stream in real-time. In the first frame, I've used of your SDM to find facial landmarks. Then I've passed its output to your Eos to construct 3d model of face. For other incoming frames I find facial landmarks again. Then transform the model to correct scale, position and angle. I've used of the Rendering parameters (from fitting::estimate_orthographic_camera) for model transformation. My Opengl code to renderScene is as follow:

```
void renderScene(void) {
       -----------------------------
	//Capture current frame 
	-----------------------------
	RenderingParams = FindLandmarks_EstimateCamera(curFrame);
	yaw_angle = glm::degrees(RenderingParams.r_y);
	pitch_angle = glm::degrees(RenderingParams.r_x);
	roll_angle = glm::degrees(RenderingParams.r_z);
	trans_x = RenderingParams.t_x;
	trans_y = RenderingParams.t_y;
		
	glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT);

	-----------------------------
	//render  background image
	-----------------------------

	// set camera matrix
	setCamera(camX, camY, camZ, 0, 0, 0);
	// set the model matrix to the identity Matrix
	setIdentityMatrix(modelMatrix, 4);

	glRotate(roll_angle, 0.0f, 0.0f, 1.0f);
	glRotate(yaw_angle, 0.0f, 1.0f, 0.0f);
	glRotate(pitch_angle, 1.0f, 0.0f, 0.0f);

	OrthoFrustum(RenderingParams.frustum.l, RenderingParams.frustum.r, 	RenderingParams.frustum.b, RenderingParams.frustum.t, 1, 1000);
		
	-----------------------------	
	//render  model 
	-----------------------------
	glutSwapBuffers();
}
void OrthoFrustum(float l, float r, float b, float t, float n, float f) {
	float aux[16];
	setOrthoFrustum(aux, l, r, b, t, n, f);
	multMatrix(modelMatrix, aux);
	setModelMatrix();
}

void setOrthoFrustum(float *mat, float l, float r, float b, float t, float n, float f)
{
	setIdentityMatrix(mat, 4);
	mat[0] = 2 / (r - l);
	mat[5] = 2 / (t - b);
	mat[10] = -2 / (f - n);
	mat[12] = -(r + l) / (r - l);
	mat[13] = -(t + b) / (t - b);
	mat[14] = -(f + n) / (f - n);
}
```

I have problem with speed. It is so slow which I can't see its transformation is correct or no. I found that it becomes slower and slower over time. I don't know if I'm in right way?  Can I use these projects for real-time purpose? Is my Opengl code to transformation correct? 

Regards,
Morteza

**Comment by patrikhuber** [comment]
Hi Morteza,

It runs at around 10 fps on my laptop *without* using OpenGL, and everything is definitely real-time capable. Are you compiling in debug-mode?

Try to uncomment `extract_texture()`, that's the slowest part of everything.

You can use `glm::ortho` instead of creating your matrices manually:
`auto ortho_projection = glm::ortho(rendering_params.frustum.l, rendering_params.frustum.r, rendering_params.frustum.b, rendering_params.frustum.t);`

I don't have problems with the code getting slower and slower. I regularly run it for several minutes and longer, and it works steadily at real-time performance. It must be an issue on your end.

**Comment by mortezab** [comment]
Thanks for your reply and help. I'm working on it. I'll inform you the results soon.

**Comment by mortezab** [comment]
Hi Patrik,

Thanks again for your help. I've solved it. It was my mistake as you said. I've been divided your main function into two sub functions and define variables in global domain. I've been forgotten to clear variables at the first of these functions. So it cause to grow their values and program becomes slower and slower over time.

It run at around 10 fps on my system now. Its is great but I need to increase the fps in my work. What is your idea about using SDM tracker? Can it improves the speed? Could you please give me some advises to improve the speed?

Regards,
Morteza

**Comment by patrikhuber** [comment]
Hi Morteza,

Glad you solved the issues in your code!

Regarding getting more than 10fps: Can you try and uncomment `extract_texture()`, and see how fast it runs? That's the slowest part of everything. Do you need that?

Cheers,
Patrik

**Comment by mortezab** [comment]
Thanks Patrik. I've constructed 3d model of face in the first frame and I've just transformed it in other frames and I didn't call extract_texture() again. So it is not important for fps. I'm trying to decrease number of landmarks. I don't know how much it affect on accuracy but I'll test it. Any other idea to increase fps would be appreciated.

Regards,
Morteza

**Comment by patrikhuber** [comment]
I see. Well, the way to go is run a profiler. One general rule of program optimisation is to always run a profiler to tell you where the hotspots are - our intuition is very often wrong. I'm sure if you tell me the hotspots, I'll have some ideas on how to improve it! :-)

**Comment by mortezab** [comment]
So thanks Patrik. OK. I'll do it and inform you the results.

**Comment by mortezab** [comment]
Hi Patrik,

I've attached profiler report.

![Uploading img1.png…]()
![Uploading img2.png…]()

**Comment by patrikhuber** [comment]
A lot of the time is spent in the HOG feature extraction of the landmark detection. This coincides with my own measurements. There's not sooo much we can do about that, except to parallelise it, it could run it in parallel for each landmark, so we could use 4, 8 or even more cores.

However what's a bit odd is ~50% of the samples are in opencv_objdetect.dll. Are you running V&J each frames? It seems that is what is making everything slow in your case!

**Comment by mortezab** [comment]
Thanks for your quick response. Yes, I run V&J on each frames now. I've read about Lucas-Kanade tracking. Is it good for tracking? Have you any other suggestion?
About HOG feature extraction, is faster alternative algorithm? So thanks for your time.

**Comment by patrikhuber** [comment]
You can actually just use our landmark detection for tracking! I recently trained two new models which are a lot better than the one in the repository, and everything works even better when _not_ running V&J each frame. I'll put all that stuff in the repository, but I'm quite busy until January, here you go in the mean-time:

* [42-point model](http://www.patrikhuber.ch/files/models/face_landmarks_model_rcr_42.bin)
* [68-point model](http://www.patrikhuber.ch/files/models/face_landmarks_model_rcr_68.bin)

The tracking-loop looks like this:

```
	cv::VideoCapture cap(0);
	if (!cap.isOpened()) {
		return EXIT_FAILURE;
	}
	Mat frame;
	bool have_face = false;
	rcr::LandmarkCollection<cv::Vec2f> current_landmarks;
	for (;;) {
		cap >> frame; // get a new frame from camera
		if (frame.empty()) { // stop if we're at the end of the video
			break;
		}
		// You may want some check here if you're still tracking a valid face, and if not, set have_face = false
		if (!have_face) {
			// Run the face detector and obtain the initial estimate using the mean landmarks:
			vector<cv::Rect> detected_faces;
			face_cascade.detectMultiScale(frame, detected_faces);
			if (detected_faces.empty()) {
				continue;
			}
			// rescale the V&J facebox to make it more like an ibug-facebox (it should also/still be square):
			cv::Rect ibug_facebox = rescale_facebox(detected_faces[0], 0.85, 0.2);
			current_landmarks = rcr_model.detect(frame, ibug_facebox);
			have_face = true;
		}
		else {
			// We already have a face. Track from the landmark bounding-box.
			auto enclosing_bbox = get_enclosing_bbox(rcr::to_row(current_landmarks));
			enclosing_bbox = make_bbox_square(enclosing_bbox);
			current_landmarks = rcr_model.detect(frame, enclosing_bbox);
		}
// Do fitting etc.
```
and:
```
// V&J to ibug: scaling = 0.85, translation_y = 0.2 // moves down, in percent of original facebox
cv::Rect rescale_facebox(cv::Rect vj_facebox, float scaling, float translation_y)
{
	const auto new_width = vj_facebox.width * scaling;
	const auto smaller_in_px = vj_facebox.width - new_width;
	const auto new_tl = vj_facebox.tl() + cv::Point2i(smaller_in_px / 2.0f, smaller_in_px / 2.0f);
	const auto new_br = vj_facebox.br() - cv::Point2i(smaller_in_px / 2.0f, smaller_in_px / 2.0f);
	cv::Rect ibug_facebox(new_tl, new_br);
	ibug_facebox.y += vj_facebox.width * translation_y;
	return ibug_facebox;
};
```

You just need to add some criteria to stop and reinitialise the tracking, for example when the bounding-box is <= 40 pixel or you could run V&J every 100 frames or so.

Note that this code will **not** work with the model that is on the repository currently, it will diverge, because the initialisation is done slightly different.

As I said all this will end up in the repository, hopefully in January :-)

**Comment by patrikhuber** [comment]
Also about the HOG features, you could use LBP or something faster, but you'd have to re-train (and re-optimise) the model. IMHO HOG is quite fast already and the easier way is just to parallelise it.

**Comment by mortezab** [comment]
Sooooo thanks for your kindly help. I've tested it. I've some problem with it. There is not exist definition of "make_bbox_square" function. I've commented it and it works with 68-point model but 42-point model cause this error: "kernelbase.pdb not loaded."

Another question: I've seen you mentioned in issue#19 of superviseddescent If we're initializing with the previous frame, the landmarks will be fairly close to the true location and we should re-train a model with a different initialization strategy. Is this 42-point model and 68-point model trained using that method?

Again and again so thanks for your time.

**Comment by patrikhuber** [comment]
You're welcome. Here's the missing function:

```
cv::Rect make_bbox_square(cv::Rect bounding_box)
{
	auto center_x = bounding_box.x + bounding_box.width / 2.0;
	auto center_y = bounding_box.y + bounding_box.height / 2.0;
	auto box_size = std::max(bounding_box.width, bounding_box.height);
	return cv::Rect(center_x - box_size / 2.0, center_y - box_size / 2.0, box_size, box_size);
};
```

"kernelbase.pdb not loaded." is not an error of the program, it just means certain debug information wasn't found. Try to find out the real error message, I believe it should work :-)

Your question regarding superviseddescent issue#19: The two new models I linked to go a little bit into that direction, they're still trained with bounding-box initialisation, but they're a lot better. I don't think the training method mentioned in that issue can give much better performance.

**Comment by mortezab** [comment]
Thanks Patrik. It works great now.
I've only two other questions. [ last questions :-) ]

1- I need to increase the speed for my work so I should reduce the number of landmarks. Could you please  guide me how can I change previous training code to include this method?

2- I need to extend this program to include profile view too. Has it potential of it? Can I reach this goal by training with profile view instances?

So Thanks.

**Comment by patrikhuber** [comment]
Cool! :-)

1. I've just modified rcr-train basically to load ibug faceboxes, trained from these, rescaled the mean, and then trained on a lot of the ibug images. I'll commit the code to the superviseddescent repo in the future but in the meantime, if you're interested you can drop me an email and I can send you my modified .cpp file. You can find my address on my homepage.

2. "This program" refering to eos, yes, definitely. Refering to superviseddescent, I'd say "yes" too, it scaled very nicely to more images (for example from Helen). I'm not sure about profile, but it can definitely handle a lot more pose!

**Comment by mortezab** [comment]
Thanks :-)

I appreciate your time. Your comments were so helpful for me. 

Wishing you all the best of luck,
Morteza
