### ISSUE TITLE
A question

### ISSUE THREAD

**Issue by zkailong** [patrikhuber/eos#175]
what's wrong about it?

Configuring done
CMake Error in examples/CMakeLists.txt:
  The compiler feature "cxx_nonstatic_member_init" is not known to CXX
  compiler

  "MSVC"

  version 18.0.40629.0.

I am using VS2013,CMake 3.10.2,EOS v0.14
Do I have to install VS2017?

**Comment by patrikhuber** [comment]
Hi,

It's exactly what the error says. Your compiler, MSVC 18.0.x, does not support C++ nonstatic member initialisation - it's too old. In your case it's way too old, VS2013 shouldn't be used anymore, it contains many bugs and a non-standard conforming compiler.
I highly suggest that you update to VS2017, the community edition is completely free.

Thanks!

**Comment by zkailong** [comment]
Thanks a lot!
