### ISSUE TITLE
error while making the project

### ISSUE THREAD

**Issue by maple003** [patrikhuber/eos#178]
In file included from /home/diqong/eos/include/eos/render/detail/render_detail.hpp:33:0,
                 from /home/diqong/eos/include/eos/render/render.hpp:27,
                 from /home/diqong/eos/examples/generate-obj.cpp:23:
/home/diqong/eos/include/eos/cpp17/optional.hpp:31:22: fatal error: optional: No such file or directory

but I have the file optional.hpp

**Comment by patrikhuber** [comment]
What compiler version and platform are you using?
