### ISSUE TITLE
Request for details about sfm_shape_3448.bin

### ISSUE THREAD

**Issue by hrdkjain** [patrikhuber/eos#18]
Thanks alot for providing the library!! Could you please give some information about how this model was prepared. How many face scan does it has ?
Or some link which describes this Model.
That would be a great help.

**Comment by patrikhuber** [comment]
Hi!

We just published a paper with all the details in it: 


http://www.patrikhuber.ch/files/3DMM_Framework_VISAPP_2016.pdf

**Comment by hrdkjain** [comment]
Thanks alot !!
