### ISSUE TITLE
Python bindings install error

### ISSUE THREAD

**Issue by jjjjohnson** [patrikhuber/eos#180]
Hi there,

I tried to install eos binding to my ubuntu16.04: `pip install eos-py`
```
But got the error:
  [ 50%] Building CXX object python/CMakeFiles/python-bindings.dir/generate-python-bindings.cpp.o
  In file included from /tmp/pip-build-l1ihvlsb/eos-py/python/generate-python-bindings.cpp:21:0:
  /tmp/pip-build-l1ihvlsb/eos-py/include/eos/core/LandmarkMapper.hpp:27:20: fatal error: optional: No such file or directory
   #include <optional>
                      ^
  compilation terminated.
```
Any help is greatly appreciated.

**Comment by patrikhuber** [comment]
Hi Junjie Jin,

Have a look at the [readme](https://github.com/patrikhuber/eos#python-bindings):

> Make sure that you've got >=gcc-7 or >=clang-5 as the default compiler on Linux (for example from the [ubuntu-toolchain-r/test](https://launchpad.net/~ubuntu-toolchain-r/+archive/ubuntu/test) repository) or do ``CC=`which gcc-7` CXX=`which g++-7` pip install eos-py``.

It'll then work.
Thanks!

**Comment by jjjjohnson** [comment]
Hi @patrikhuber ,

It turns out that I donot have gcc-7 and g++-7. It is successfully installed. Thanks.
