### ISSUE TITLE
How to solve this issue?

### ISSUE THREAD

**Issue by bigdimboom** [patrikhuber/eos#181]
![image](https://user-images.githubusercontent.com/6119906/37721771-c190d44e-2d00-11e8-90f8-65aa6c288495.png)

**Comment by patrikhuber** [comment]
The "Error" literally tells you your options. To perform albedo-model fitting, you need the albedo model. The readme contains a link with information on how to obtain it. And/Or, have a look at the code, to remove the `ImageCost` part and do landmark-fitting.
