### ISSUE TITLE
Synchronization of facial expression

### ISSUE THREAD

**Issue by sunjunlishi** [patrikhuber/eos#183]
The 3D model is estimated with a person's multiple faces. Then the real-time expression change parameters of the face are estimated based on 3D, and then the expression change parameters are applied to other 3D models.

**Comment by patrikhuber** [comment]
Is there an issue here? :-O I'm closing it meanwhile.

**Comment by sunjunlishi** [comment]
Can I synchronize one person's expression to another's 3D model using EOS technology?

**Comment by patrikhuber** [comment]
If they have the same mesh topology, sure, you can just transfer the blendshape weights. I'd recommend you to read some of the literature and perhaps find some forum or community to ask beginner questions, as the GitHub issues are for developer issues with the library. Thanks!

**Comment by sunjunlishi** [comment]
EOS technology！
I want to synchronize expressions on the basis of your EOS functions.            Because I found that EOS has many methods of parameter transformation of 3D model, I don't know the exact role, I want to use them flexibly to achieve expression synchronization.

**Comment by patrikhuber** [comment]
Well as I said, one method would be to transfer the blendshape weights. It really depends on your use case, and you need to find out what works best for that.

**Comment by sunjunlishi** [comment]
oh，yes yes。 one method would be to transfer the blendshape weights，it is expression param。yes yes

**Comment by sunjunlishi** [comment]
@patrikhuber blendshap weights is very ok.but 
The mixed shape weight is not perfect, and the details are not in place, such as eyebrow movement and eye movement, because it has only six variables. What should we do

**Comment by sunjunlishi** [comment]
@patrikhuber 
Highlights
"Morphable Model, captured from real human 3D face scans
36 expressions and facial action units
Topology optimised for animation & real-time use cases
Full-head model
Two different mesh resolutions"                      how could i get  "36 expressions and facial action units",how much i can get it.
