### ISSUE TITLE
Custom input landmarks to output landmarks

### ISSUE THREAD

**Issue by jjjjohnson** [patrikhuber/eos#184]
Hi @patrikhuber 

If I have 88-point annotations of face landmarks. How can I convert it  to the Surrey Face Model (SFM) mesh vertex indices. Can I do the mappings from input landmarks to output landmarks (SFM, rhs) myself? If so, what additional information do I need to do that.

Thanks a lot!
Junjie

**Comment by patrikhuber** [comment]
Hi @jjjjohnson,

Yes, you can just adjust the mappings file. See the `share/` directory for some examples, e.g. the `ibug_to_sfm.txt`. If you need to find the according vertex IDs of the SFM, open `reference.obj` in MeshLab (or if you need more fine-grained resolution, write the 3448 model's mean to disk with `write_obj` and then open that in MeshLab).
If you search through the closed issues you may also find a few similar questions that have an a bit more elaborate answer.

Thanks!
