### ISSUE TITLE
Port the Library to Android JNI

### ISSUE THREAD

**Issue by kzw5309** [patrikhuber/eos#187]
Hi,

I am interested in porting this library to android. I tried to do it by following some instructions in https://github.com/tzutalin/dlib-android and https://github.com/detsikas/Dlib4Android. Do you think it is doable to port this library to android? Do you have any suggestions for setting up the Android.mk and Application.mk?

**Comment by patrikhuber** [comment]
Hi,

If you can use a more-or-less recent compiler, the library should already compile fine on Android, and there should be no obstacles. eos is also CI-tested on macOS and runs fine on iOS.
If you are lucky even something as old as gcc-5 might still work, though we don't CI-test that anymore.
As for Android.mk or Application.mk, I have no idea and am not familiar with these files. But these are probably just the build files, the library itself probably doesn't need any modifications. In fact, eos is a header-only library, so you won't need these build files either - you can just include the eos headers from your application, and you should be done.

**Comment by kzw5309** [comment]
Thanks for your reply! By the way, is there a build-in function that transfer the mesh to a normal map?

**Comment by patrikhuber** [comment]
Hmm - I'm not sure what you mean with "transfer the mesh to a normal map", but possibly no. There are some functions in the `render::` namespace to compute per-vertex and per-face normals, if that helps you!

**Comment by kzw5309** [comment]
Thanks. I found the compute_face_normal function. I am trying to get normal map of the face like the image below (RGB of each pixel are XYZ of the normal vector):
![image](https://user-images.githubusercontent.com/18537671/38180239-0fcc4688-35f9-11e8-9abb-12e4fb722f73.png)

**Comment by patrikhuber** [comment]
Hi @kzw5309,
What came out of it?
Can we close this?
