### ISSUE TITLE
morphablemodel::get_mean() for models with expressions

### ISSUE THREAD

**Issue by patrikhuber** [patrikhuber/eos#188]
For `MorphableModel`s that contain a PCA expression model, we have to decide whether [`morphablemodel::get_mean()`](https://github.com/patrikhuber/eos/blob/73fda186ad44f45fca0d27f23b623e2150d91b10/include/eos/morphablemodel/MorphableModel.hpp#L134-L161) should return the combined identity + expression mean. If yes, that would mean that the result probably wouldn't be a neutral face.

**Comment by patrikhuber** [comment]
Changed this in b8be43698704deaafaa5ceff5f5e52cc66312ab3 to return the overall, combined mean now. I think that's the more sound way.
If someone wants the obtain the neutral-only shape mean, they can use `get_shape_model().get_mean()` and `sample_to_mesh`.

**Comment by sunjunlishi** [comment]
@patrikhuber dear author
I saw that you had an example where you could turn any expression into a neutral expression. Why didn't you see it. Now that I have extracted the expression change parameters, it works. Now I need the texture to be able to change according to the expression,
