### ISSUE TITLE
How to create my sfm_shape_3448.bin?

### ISSUE THREAD

**Issue by KeeganRen** [patrikhuber/eos#19]
I found that the model does not look like me, and the nose is particularly high, so how to create my sfm_shape_3448.bin, I am Asian, or where can find Asian model.

**Comment by longpeng2008** [comment]
I have the same question.

**Comment by patrikhuber** [comment]
Hi,

First of all, you can't "create your own sfm_shape_3448.bin". That file is the PCA model itself, and you can create an instance of the model, and save that as a mesh or obj or something. (Well you _can_ create your own PCA model, but I don't think that's what you mean.)

We have quite a number of Asian subjects in our model, I'm not sure that's an issue. You can find more details in our paper. You have to keep in mind that the default algorithm performs shape-from-landmarks fitting, which results in a semi-dense shape based on the given landmarks. 
One thing you could do is use more landmarks for the fitting, or use a more complex fitting cost function, but this will of course make it slower.

**Comment by KeeganRen** [comment]
OK, thanks.

**Comment by patrikhuber** [comment]
Ah, one thing I forgot to mention: It might be worth checking out the `devel` branch, there are quite a few improvements in there! :-)

I will close the issue, feel free to re-open or open a new one if you have further issues.
