### ISSUE TITLE
Convert Surrey Face Model into the format of Basel Face Model

### ISSUE THREAD

**Issue by cpwei80** [patrikhuber/eos#190]
I know Basel Face Model could be converted into the eos format. Is it possible to convert the Surrey Face Model (sfm_shape_3448.bin) into the format of Basel Face Model?

**Comment by patrikhuber** [comment]
Yes, sure.
You could write a converter script analogous to `convert-bfm2017-to-eos.py`, just doing the reverse. You probably have to dig into the details of the BFM format a bit.

I'm closing this since it is not an eos issue. Feel free to post back about your progress.
