### ISSUE TITLE
"No targets specified and no makefile found.  Stop."

### ISSUE THREAD

**Issue by leoli3024** [patrikhuber/eos#191]
Hi! I'm having difficulty finishing the last step to build
"make && make install # or open the project file and build in an IDE like Visual Studio".

I'm completely new to C++, and I'm not sure how to fix this. After running the first three steps, I got the following outputs 

```
[leoli@Leos-MacBook-Pro-2 build]$ ls
CMakeCache.txt		CPackConfig.cmake	eos.build
CMakeFiles		CPackSourceConfig.cmake	eos.xcodeproj
CMakeScripts		cmake_install.cmake	examples
```

I wonder how should I fix it. I looked online for some solutions (running ./configure, etc.), but nothing has helped so far. I used Xcode as the generator, and Clang (CommandLineTool from Xcode) as the compiler. 

Thanks for the help!

**Comment by patrikhuber** [comment]
Hi,

Everything is working as expected. In your output of `ls` that you posted you can see that cmake generated an `eos.xcodeproj` file for you. This is a regular Xcode project file that you can open with Xcode or build via the Apple command-line tools from Xcode.

I am not an Xcode expert so I don't know how to build Xcode projects on the command-line but you probably know or can google that - it's probably something using `xcodebuild [...]`.

You can also just build with cmake:
`cmake --build . --config Release`
`cmake --build . --target install --config Release`
This will invoke the Apple tools too (probably `xcodebuild`).

I'm going to close this as it is a "user error" and not an eos issue, but feel free to post back with how it's going.

**Comment by patrikhuber** [comment]
Hi @leoli3024,

The error you posted pretty much shows you what's going wrong. Have a look at [line 26](https://github.com/patrikhuber/eos/blob/7f0e46179112c44c26321491ea0246394a9a5a8a/include/eos/cpp17/optional.hpp#L26) - it wants to include `<optional>`. So what you have to find out is why it's going into this `#if`-branch. Maybe `__cplusplus >= 201703L` is true for some reason on your compiler? What's your Xcode version? I'd recommend you check the value of `__cplusplus`.

You can also follow the steps for macOS in the [.travis.yml](https://github.com/patrikhuber/eos/blob/master/.travis.yml) file **step-by-step**, in a clean build directory.
