### ISSUE TITLE
How to get the rest Surrey Face Model

### ISSUE THREAD

**Issue by likewind1993** [patrikhuber/eos#192]
I followed README instructions, visited website http://www.cvssp.org/faceweb/3dmm/facemodel/, and registered, but it has been a week after registered. I have no received any reply.
and I send a email to cvssp-facemodel@surrey.ac.uk ....without reply...
So, the only way I can consider is post a issue here...
looking for a reply，
and Thank you for your work again!

**Comment by patrikhuber** [comment]
Hi,

Thank you very much!

Unfortunately there is nothing really that I can do to help you regarding obtaining the full Surrey Face Model - as you already know, cvssp-facemodel@surrey.ac.uk is the contact address and you would have to wait until you receive a reply, or email them again.

I wish you good luck, and hope you hear from them soon! :-) Maybe let us know here once you do.
