### ISSUE TITLE
Reconstruct a mesh with python

### ISSUE THREAD

**Issue by qinhaifangpku** [patrikhuber/eos#193]
hi~
I am fresh here, I have read the generate-python-bindings.cpp,  But when I use **eos.fitting.ScaledOrthoProjectionParameters** to initialize the **RenderingParameters**, it will be wrong. is there anybody use the parameters to reconstruct a mesh and show with python? 
Now I have construct form draw_sample() function and get a mesh. next, I want to add rotation and transform, projection to the mesh.  I try to use the function in pybinds but failed.
Looking forward to your reply!

**Comment by patrikhuber** [comment]
Hi,
Apologies for the late reply. This has been discussed in #140, you could find some help there. You can follow the projection pipeline from C++ 100% in Python, and if you do that correctly, it'll work just fine.
Thanks!
