### ISSUE TITLE
How to use new modelfile in eos?

### ISSUE THREAD

**Issue by Qqqqqqin** [patrikhuber/eos#194]
Hi

I have using LSFM to generate a new shape_model.mat which include mean ,orthonormal_pca_basis,eigenvalues and triangle_list.

how to ues new modelfile to generate a .bin file while can be use in eos?

**Comment by patrikhuber** [comment]
You can do this very easily with the python bindings. You can see [here](https://github.com/patrikhuber/eos/blob/7f0e46179112c44c26321491ea0246394a9a5a8a/share/scripts/convert-bfm2017-to-eos.py#L22-L50) for how to instantiate the model classes from data in Python.
You can see [here](https://github.com/patrikhuber/eos/blob/7f0e46179112c44c26321491ea0246394a9a5a8a/share/scripts/convert-bfm2009-to-eos.py) how you can import your data with `scipy.io` in case your data is in Matlab format.
If you need a PCA expression model, you can use the `devel` branch of eos.

**Comment by Qqqqqqin** [comment]
Hi
i would like to konw python bingdings can be used in windows?

thanks

**Comment by patrikhuber** [comment]
@Qqqqqqin Just follow the readme instructions to install them. The AppVeyor config also builds them on Windows. Actually they can be installed in various ways and all of them work. You can get them via `pip`, but they're currently not updated to the latest version, so I recommend to clone the repo and build them - either with CMake "manually" or I think one can also do `pip install <local eos folder>` and it'll pick up the `setup.py` file. I recommend asking on StackOverflow if you need more help,
