### ISSUE TITLE
Question on ISOmap

### ISSUE THREAD

**Issue by DoraXingyu** [patrikhuber/eos#20]
Hi, Patrik! I am wondering if the isomap output is a way for obj file viewer to see the texture? Is there a way to visualise the 3D model directly(like utilising the openGL function)?
// This is not an issue, but I don't know where to put it.

**Comment by patrikhuber** [comment]
Hi Xingyu,

It's in principle just a texture map, if you're a bit familiar with computer graphics. So yes, obj viewer get the texture from there. And for us, it's a convenient representation to store the texture information.
If you want to visualise the model inside the C++ code, you could use my [`render(...)`](https://github.com/patrikhuber/eos/blob/master/include/eos/render/render.hpp#L114-L129) function, or, maybe better, use OpenGL to draw the `Mesh`. The `Mesh` contains all the vertex information necessary for OpenGL to draw it.

**Comment by patrikhuber** [comment]
Closing this, let me know if you have further questions!
