### ISSUE TITLE
Is the uv-coordinate necessary in the PCA model used in the fit-model?

### ISSUE THREAD

**Issue by Qqqqqqin** [patrikhuber/eos#200]
hello
i'm  so sorry for ask you such a stupid question
because i need to use my model ,but , .bin don't have uv-coordinate.

**Comment by patrikhuber** [comment]
No, uv-coords are only needed if you want to do texture extraction.
These GitHub issues are for issues and discussions around developing the library - please ask such beginner questions on more appropriate websites like Stackoverflow, or better, find some beginner tutorials on the subject matter. Thanks!
