### ISSUE TITLE
845 model

### ISSUE THREAD

**Issue by DmitryBorin** [patrikhuber/eos#207]
Hello!

I'm trying to speed up the fitting process by 845 model used. But I can't generate the needed .bin (and other) files correctly. And i read your documentation. I want to use the standard 68 dlib's landmarks. Could you please shape the appropriate files for the 845 model? Or give some samples for their simple generation.

Thank you very much!

**Comment by patrikhuber** [comment]
Hi @DmitryBorin,

Apologies for the slightly late reply. I think if you request the full model from CVSSP (http://www.cvssp.org/facemodel), the 845 model should be included. If not, you could easily take the 3448 vertices model and just take the first 845 vertices, and the corresponding entries from the PCA basis matrix. The topology of the SFM mesh is in such a way that the 3448 model contains the vertices of the 845 model (i.e. during the registration, it was started with the reference consisting of 845 vertices, and then the mesh was subdivided, keeping the original vertices - as described in our paper).
Depending on your use-case you may also want to re-orthogonalise the resulting "reduced" basis. It's pretty trivial and how I generated the 845 model too, you can do it in a short Python script using the eos Python bindings.
