### ISSUE TITLE
Citation

### ISSUE THREAD

**Issue by nehatoppo** [patrikhuber/eos#21]
Should we cite "Fitting 3D Morphable Models using Local Features" or "A multiresolution 3D Morphable face model and fitting framework" for using this code.

**Comment by patrikhuber** [comment]
The second one is fine, "A multiresolution 3D Morphable face model and fitting framework". (Or both if you have the space ;-) ).

Thanks for asking!

**Comment by nehatoppo** [comment]
Thanks !!

**Comment by patrikhuber** [comment]
I should probably update the front page readme. Will do that soon :-)
