### ISSUE TITLE
Errors in building the project with Visual Studio 2015 in Windows 10

### ISSUE THREAD

**Issue by Wasseem81** [patrikhuber/eos#214]
Hi I got this error when building the project in Visual Studio 2015 in Windows 10. Could you please help?

5> generate-obj.cpp
3>C:\Users\WNI\Desktop\eos_cmake\include\eos/cpp17/optional.hpp(31): fatal error C1083: Cannot open include file: 'optional': No such file or directory
2>C:\Users\WNI\Desktop\eos_cmake\include\eos/cpp17/optional.hpp(31): fatal error C1083: Cannot open include file: 'optional': No such file or directory
4>C:\Users\WNI\Desktop\eos_cmake\include\eos/cpp17/optional.hpp(31): fatal error C1083: Cannot open include file: 'optional': No such file or directory
5>C:\Users\WNI\Desktop\eos_cmake\include\eos/render/detail/texturing.hpp(81): warning C4244: 'argument': conversion from 'int' to 'float', possible loss of data
5>C:\Users\WNI\Desktop\eos_cmake\include\eos/render/detail/texturing.hpp(81): warning C4244: 'initializing': conversion from 'float' to 'unsigned char', possible loss of data
5>C:\Users\WNI\Desktop\eos_cmake\include\eos/render/detail/texturing.hpp(81): warning C4244: 'initializing': conversion from 'float' to 'const unsigned char', possible loss of data
5>C:\Users\WNI\Desktop\eos_cmake\include\eos/cpp17/optional.hpp(31): fatal error C1083: Cannot open include file: 'optional': No such file or directory
7>------ Build started: Project: ALL_BUILD, Configuration: Debug x64 ------

**Comment by patrikhuber** [comment]
If you read the readme, you'll read that VS 2015 is no longer officially supported.
There is some chance that it might still work - it seems the wrong define branch gets chosen [here](https://github.com/patrikhuber/eos/blob/master/include/eos/cpp17/optional.hpp) and it tries to include `<optional>`, which VS 2015 doesn't have. You can investigate why it doesn't use the latter branch and adjust the define accordingly.

**Comment by Wasseem81** [comment]
Thank you for your quick response. I tried with Visual Studio 2017 15.7.5 on Windows 10 and got the following errors:

4>C:\Users\WNI\Desktop\eos_cmake\examples\fit-model-simple.cpp : fatal error C1128: number of sections exceeded object file format limit: compile with /bigobj
4>Done building project "fit-model-simple.vcxproj" -- FAILED.
2>C:\Users\WNI\Desktop\eos_cmake\examples\fit-model.cpp : fatal error C1128: number of sections exceeded object file format limit: compile with /bigobj
2>Done building project "fit-model.vcxproj" -- FAILED.
3>C:\Users\WNI\Desktop\eos_cmake\examples\fit-model-multi.cpp : fatal error C1128: number of sections exceeded object file format limit: compile with /bigobj
3>Done building project "fit-model-multi.vcxproj" -- FAILED.

**Comment by patrikhuber** [comment]
Just do what it says, add `/bigobj` to the compiler flags.

**Comment by Wasseem81** [comment]
I did it and it worked. I wanted to add MATLAB bindings and got this error:

2>c:\users\wni\desktop\eos_cmake\3rdparty\mexplus\include\mexplus\mxarray.h(1102): error C3861: 'mxGetPiIsDeprecated': identifier not found

**Comment by patrikhuber** [comment]
As the compiler error tells you, this error is coming from `3rdparty\mexplus\include\mexplus\mxarray.h`. Maybe Matlab removed this deprecated function - in that case, an earlier version of the MCR will probably work. Perhaps you might want to file an issue in the mexplus repo.

**Comment by Wasseem81** [comment]
I tried with earlier versions of MCR. However, all of them produces much more different errors. What version of MATLAB did you use to compile the code successfully?

**Comment by patrikhuber** [comment]
It has been a few months since I last compiled them so I'm not 100% sure, but I think 2017b should work fine (and 2017a possibly too). What where the errors with these?

**Comment by Wasseem81** [comment]
Severity	Code	Description	Project	File	Line	Suppression State
Error	C2039	'begin': is not a member of 'Eigen::Matrix<float,3,1,0,3,1>'	eos-matlab-fitting	c:\users\wni\desktop\eos_cmake\3rdparty\mexplus\include\mexplus\mxarray.h	1222	
Error	C2039	'end': is not a member of 'Eigen::Matrix<float,3,1,0,3,1>'	eos-matlab-fitting	c:\users\wni\desktop\eos_cmake\3rdparty\mexplus\include\mexplus\mxarray.h	1223	
Error	C2672	'std::copy': no matching overloaded function found	eos-matlab-fitting	c:\users\wni\desktop\eos_cmake\3rdparty\mexplus\include\mexplus\mxarray.h	1222	
Error	C2780	'_DestTy *std::copy(_ExPo &&,_FwdIt1,_FwdIt1,_DestTy (&)[_DestSize]) noexcept': expects 4 arguments - 2 provided	eos-matlab-fitting	c:\users\wni\desktop\eos_cmake\3rdparty\mexplus\include\mexplus\mxarray.h	1224	
Error	C2780	'_FwdIt2 std::copy(_ExPo &&,_FwdIt1,_FwdIt1,_FwdIt2) noexcept': expects 4 arguments - 2 provided	eos-matlab-fitting	c:\users\wni\desktop\eos_cmake\3rdparty\mexplus\include\mexplus\mxarray.h	1224	
Error	C2780	'_DestTy *std::copy(_InIt,_InIt,_DestTy (&)[_DestSize])': expects 3 arguments - 2 provided	eos-matlab-fitting	c:\users\wni\desktop\eos_cmake\3rdparty\mexplus\include\mexplus\mxarray.h	1224	
Error	C2780	'_OutIt std::copy(_InIt,_InIt,_OutIt)': expects 3 arguments - 2 provided	eos-matlab-fitting	c:\users\wni\desktop\eos_cmake\3rdparty\mexplus\include\mexplus\mxarray.h	1224	
Error	C2039	'begin': is not a member of 'Eigen::Matrix<float,2,1,0,2,1>'	eos-matlab-fitting	c:\users\wni\desktop\eos_cmake\3rdparty\mexplus\include\mexplus\mxarray.h	1222	
Error	C2039	'end': is not a member of 'Eigen::Matrix<float,2,1,0,2,1>'	eos-matlab-fitting	c:\users\wni\desktop\eos_cmake\3rdparty\mexplus\include\mexplus\mxarray.h	1223	
Error	C2039	'begin': is not a member of 'Eigen::Matrix<float,3,1,0,3,1>'	eos-matlab-render	c:\users\wni\desktop\eos_cmake\3rdparty\mexplus\include\mexplus\mxarray.h	1222	
Error	C2039	'end': is not a member of 'Eigen::Matrix<float,3,1,0,3,1>'	eos-matlab-render	c:\users\wni\desktop\eos_cmake\3rdparty\mexplus\include\mexplus\mxarray.h	1223	
Error	C2672	'std::copy': no matching overloaded function found	eos-matlab-render	c:\users\wni\desktop\eos_cmake\3rdparty\mexplus\include\mexplus\mxarray.h	1222	
Error	C2780	'_DestTy *std::copy(_ExPo &&,_FwdIt1,_FwdIt1,_DestTy (&)[_DestSize]) noexcept': expects 4 arguments - 2 provided	eos-matlab-render	c:\users\wni\desktop\eos_cmake\3rdparty\mexplus\include\mexplus\mxarray.h	1224	
Error	C2780	'_FwdIt2 std::copy(_ExPo &&,_FwdIt1,_FwdIt1,_FwdIt2) noexcept': expects 4 arguments - 2 provided	eos-matlab-render	c:\users\wni\desktop\eos_cmake\3rdparty\mexplus\include\mexplus\mxarray.h	1224	
Error	C2780	'_DestTy *std::copy(_InIt,_InIt,_DestTy (&)[_DestSize])': expects 3 arguments - 2 provided	eos-matlab-render	c:\users\wni\desktop\eos_cmake\3rdparty\mexplus\include\mexplus\mxarray.h	1224	
Error	C2780	'_OutIt std::copy(_InIt,_InIt,_OutIt)': expects 3 arguments - 2 provided	eos-matlab-render	c:\users\wni\desktop\eos_cmake\3rdparty\mexplus\include\mexplus\mxarray.h	1224	
Error	C2039	'begin': is not a member of 'Eigen::Matrix<float,2,1,0,2,1>'	eos-matlab-render	c:\users\wni\desktop\eos_cmake\3rdparty\mexplus\include\mexplus\mxarray.h	1222	
Error	C2039	'end': is not a member of 'Eigen::Matrix<float,2,1,0,2,1>'	eos-matlab-render	c:\users\wni\desktop\eos_cmake\3rdparty\mexplus\include\mexplus\mxarray.h	1223

**Comment by patrikhuber** [comment]
According to [this issue](https://github.com/patrikhuber/eos/issues/160#issuecomment-386160047), the `eos-matlab-fitting` bindings work (and I tested them back in May). The `eos-matlab-render` bindings are not updated and don't compile though.
Make sure you're on the latest branch.

**Comment by Wasseem81** [comment]
What do you mean by "Make sure you're on the latest branch." ?

**Comment by patrikhuber** [comment]
I should've said "commit" probably. These commits from May updating the eos-matlab-fitting bindings should be in the master branch (and devel).

**Comment by Wasseem81** [comment]
I already used the bindings in the master branch and got the above errors. Now I got confused I used the same versions of Visual Studio and MATLAB that you used but I could not run the SFM. BTW, I used only two dependencies which are:  boost 1.67.0  and opencv 3.4.1. 

Is that okay to generate the code with CMake successfully ?

**Comment by patrikhuber** [comment]
Yea it should be, at least for the eos-matlab-fitting bindings. I'm sorry currently don't have time to look into it further - the eos-matlab-render bindings are harder to fix but the eos-matlab-fitting bindings should work, as mentioned. You can try to get them to work by yourself, or I recommend that you use the Python bindings, they're officially supported and much better.
