### ISSUE TITLE
Instructions to acquire the full model (http://cvssp.org/facemodel) are not available

### ISSUE THREAD

**Issue by lileirogers** [patrikhuber/eos#22]
could you tell me the updated instructions to acquire the full model ?thanks

**Comment by patrikhuber** [comment]
Hi! I'm sorry that page is not available yet, unfortunately that is a bit out of my hands. Please send me an email (you can find the address on my [homepage](http://www.patrikhuber.ch/)) and I will get you in touch. 

Thanks!

**Comment by patrikhuber** [comment]
There is now a preliminary page available at http://cvssp.org/facemodel with contact information. I'll close this!

**Comment by lileirogers** [comment]
Thanks
