### ISSUE TITLE
Blendshapes variability

### ISSUE THREAD

**Issue by aminm2a** [patrikhuber/eos#221]
![expression](https://user-images.githubusercontent.com/5443045/44612906-f3e8e300-a80c-11e8-91eb-2f8840d90142.png)

Hi Patrick, 

I was not able to get this expression (picture from your thesis report) using the 6 blendshapes model you provide. Are you using the same blendshapes model in this repository ?

**Comment by patrikhuber** [comment]
Hi Amine,

Yes indeed this result was generated with eos and the 6 SFM expression blendshapes in the repo! You should be able to get somewhat similar results. Maybe play around with the regularisation a bit?

I'm closing this as it's not an issue with the library, but feel free to report back with any more specific questions.

**Comment by patrikhuber** [comment]
That's a very good and valid question indeed! I think there is a slight asymmetry in the blendshapes, maybe together with the identity basis, and it's probably hard to recreate by hand, but the fitting figures out the exact right coefficients to make it happen. Maybe you can use the input image that I used (it's from some of the ibug 2D image datasets) or another one and create a toy example with landmarks laid out like this and then fit to them?

**Comment by aminm2a** [comment]
Yep, I'll do that. 
Thanks for your answer
