### ISSUE TITLE
Blinking eyes

### ISSUE THREAD

**Issue by ChriswooTalent** [patrikhuber/eos#223]
Hi，partrikhuber:
I installed eos on my computer and can run the example,  it was amazing. Thank you for sharing your code. 
But I found some problem, when I finished reconstruction of the 3D face, I found that the rendering of the face can only detect the opening and closing of the mouth, When I blinked my eyes，the eyes of the face model did not move, why this happen? Is that the lower-resolution model do not catch the blinking of eyes?

**Comment by patrikhuber** [comment]
Hi @ChriswooTalent,
There's no mechanism to detect blinking in eos. Blinking could be handled in different ways - e.g. by a separate eye/eyelid model, or blink blendshapes. It's quite an application-specific task. I suggest that if you need it, you implement whichever solution is most appropriate for your circumstances.
I think there might also be one or two related closed issues here, if you search for "eye" or "blink" or something like that.
