### ISSUE TITLE
About  fit-model-multi

### ISSUE THREAD

**Issue by yyssmm** [patrikhuber/eos#225]
thank you for sharing your code. When I used the "fit-model-multi" project, I found the merged isomap had some flaws. For example, when I fit three images of a person to the model, the result isomap was wrongly alignment. Would you please help me to find out where is the problem. Thank you！
![image](https://user-images.githubusercontent.com/28679695/46352365-30212600-c68c-11e8-8987-1512498d7b05.png)

**Comment by sunjunlishi** [comment]
for (int i = 0; i < num_iterations; ++i)
    {
        vector<Eigen::Matrix<float, 3, 4>> affine_from_orthos;

        vector<VectorXf> mean_plus_blendshapes;
        for (int j = 0; j < num_images; ++j)
        {
        }
}

Do you write the enumerated pictures in the number of cycles in order to let 3D touch you to fit all the pictures?

**Comment by sunjunlishi** [comment]
But I have another idea, one by one, and the next with the 3D model parameters of the final result of the previous one. Are there different and better effects?

**Comment by sunjunlishi** [comment]
author please?

**Comment by patrikhuber** [comment]
Hi!

@yyssmm, I would say that your landmarks are probably too inaccurate. I'd suggest you visualise the landmarks to double-check. Note that you will not get perfect alignment with landmark-fitting. I'd first check/improve the landmarks. Then, if they're good and you're still not happy, maybe you could use some post-processing (warping/optical flow)?

@sunjunlishi, both strategies would be valid and it would be interesting to compare them actually. If you have the images come in one-by-one, the second strategy might be better, while if you've got all the images in advance, optimisation over all of them might be beneficial.

**Comment by sunjunlishi** [comment]
thank you very much。it is good for reconstruct

**Comment by LeeTaiTai** [comment]
@sunjunlishi  how do you fiiting the 3d model through one by one image, can you share the code, i use fit_shape_and_pose, input last pca_shape_coefficients and last blendshape_coefficients.

**Comment by sunjunlishi** [comment]
yes。

**Comment by sunjunlishi** [comment]
@LeeTaiTai i have no trying
