### ISSUE TITLE
[Question] Candide

### ISSUE THREAD

**Issue by eviansplash** [patrikhuber/eos#227]
I know this library is for 3DMM but could it also be used for the candide model?

**Comment by patrikhuber** [comment]
I think this should be possible quite easily. The Candide model presumably has a mean, and variations of some sort (a basis matrix, or offsets). It's probably just a few lines of Python scripting.

**Comment by patrikhuber** [comment]
You'll just need to dive into it and see what's going on. The first things I'd do is the usual basic checks on the model, like draw a few samples from it and check whether the scaling and everything is okay, and for example the orthonormal/rescaled basis are correct.

**Comment by BenJaminKen** [comment]
@eviansplash  Does face reconstruction  take 0.3 seconds on Android?
![default](https://user-images.githubusercontent.com/18021834/47493341-a24aec00-d881-11e8-8a05-8defa0dec2c3.png)

**Comment by eviansplash** [comment]
Hi, sorry for the late reply, I don't usually check my emails:
@patrikhuber I did get it to work after some tweaking, thanks!
@BenJaminKen The time written down below is the complete JNI call, including the drawing. Also I used the least amount of iterations; The more iterations you go through will significantly increase the time, however, doing so has its advantages as well.

**Comment by patrikhuber** [comment]
@eviansplash Cool, glad you got it working!

By the way, 300ms sounds like quite a lot - if the fitting is only run for 1-5 iterations or so, it should be more like 1-10ms. So it would be interesting to run a profiler in your case to see why it takes so long, maybe it's your code that generates the Java obj.
