### ISSUE TITLE
Adding Blendshapes to Default Set

### ISSUE THREAD

**Issue by jjbouza** [patrikhuber/eos#229]
Hello,

I am working on a project involving the modeling of unusual facial expressions in a medical imaging scenario and this library has been immensely useful.  To increase the expressibility of the model and capture these extreme expressions correctly, I was thinking of modifying the set of blendshapes manually. 

Do you have any suggestions as to how I should approach this? E.g. how was the default expression_blendshapes_3448.bin file with the 6 basic blend shapes generated?

Thank you.

**Comment by patrikhuber** [comment]
Hi,
You've opened this ticket too, #230. Seems like you opened two of the same tickets by accident? Let's continue the discussion in the other one?
