### ISSUE TITLE
Add New Blendshapes to Default Set

### ISSUE THREAD

**Issue by jjbouza** [patrikhuber/eos#230]
Hello,

This library has been very useful for a project I am working on. The project involves modeling of unusual/extreme facial expressions (in a medical imaging scenario). I was considering adding custom blendshapes to increase the expressivity of the expression fitting and better capture more extreme expressions. 

Do you have any suggestions for how I could go about this? E.g. what is the format of the default expression_blendshapes_3448.bin file? 

Thank you.

**Comment by patrikhuber** [comment]
Hi,

Glad you could sort it out! The easiest thing to do is to read the existing blendshapes with the Python bindings, add your new ones, put them back into the model, and save the model. The Python bindings are extremely awesome for such kind of things :-)

Patrik

**Comment by jjbouza** [comment]
Thanks for the help, thats exactly what I did.

For anyone needing help in the future, the approach I used was to load up the reference model in blender (making sure to import such that vertex order is preserved) and modify as desired. Then export the modified mesh, compute the difference between the reference and the modified mesh, and save this as a eos.core.Blendshape object. Then this object can be appended to the default expression_blendshapes_3448.bin file (which is essentially just a serialized list of eos.core.Blendshape objects) and saved. All of this can be scripted easily using the Python interface.

Best, Jose.

**Comment by patrikhuber** [comment]
Excellent! :-)

**Comment by Chen-Jinlong** [comment]
> Thanks for the help, thats exactly what I did.
> 
> For anyone needing help in the future, the approach I used was to load up the reference model in blender (making sure to import such that vertex order is preserved) and modify as desired. Then export the modified mesh, compute the difference between the reference and the modified mesh, and save this as a eos.morphablemodel.Blendshape object. Then this object can be appended to the default expression_blendshapes_3448.bin file (which is essentially just a serialized list of eos.morphablemodel.Blendshape objects) and saved. All of this can be scripted easily using the Python interface.
> 
> Best, Jose.

Can you give more details please?

**Comment by Neo1024** [comment]
> Thanks for the help, thats exactly what I did.
> 
> For anyone needing help in the future, the approach I used was to load up the reference model in blender (making sure to import such that vertex order is preserved) and modify as desired. Then export the modified mesh, compute the difference between the reference and the modified mesh, and save this as a eos.morphablemodel.Blendshape object. Then this object can be appended to the default expression_blendshapes_3448.bin file (which is essentially just a serialized list of eos.morphablemodel.Blendshape objects) and saved. All of this can be scripted easily using the Python interface.
> 
> Best, Jose.

I did almost the same steps as  yours except the generation of the difference between the reference and the modified mesh is a bit different. Nevertheless, after I loaded the new blendshapes into EOS, I tried to fit the 2D image and I got the resulting blendshape coefficients successfully. However, when I tried to reconstruct the 3D mesh with the blendshape coefficients by adding up the shape vector and the linear combination of all blendshapes that are multiplied with the coefficients, I found the reconstructed 3D mesh is twisted as below. When I manually set the blendshape coefficient to a reasonable value, it works fine. 

![1638504214267-0ab27d42-6053-4a5b-8513-7d1dfd704986](https://user-images.githubusercontent.com/11141404/144774769-3bb7d746-b13d-4f61-885e-8ed242d9ccb4.png)
