### ISSUE TITLE
get_texture_coordinates TypeError

### ISSUE THREAD

**Issue by wqnow** [patrikhuber/eos#234]
When run python\demo.py meet a TypeError:
"File "C:/Users/wq/eos/python/demo.py", line 15, in main
    model.get_texture_coordinates())
TypeError: __init__(): incompatible constructor arguments. "

I removed parameter "model.get_texture_coordinates()" and the program run with no error.
I don't know whether the parameter is needed.
The modified file is attached.

[demo1.zip](https://github.com/patrikhuber/eos/files/2603086/demo1.zip)

**Comment by patrikhuber** [comment]
Hi!

Sorry for the slightly delayed reply. This should now all be fixed, see #238, and eos `1.0.1` has been released with the fixes.
