### ISSUE TITLE
When using as external lib, is it possible to use target_link_libraries?

### ISSUE THREAD

**Issue by ldXiao** [patrikhuber/eos#235]
Dear all, as the creator has mentioned in the main page, we can directly include the directory in the project.

But can we use the syntax like 
Find_Package(eos.....)
....
target_link_directories(...)
?

**Comment by patrikhuber** [comment]
Hi!

Unfortunately this is not yet possible. This would be part of #68.
But it shouldn't be a big issue - since eos is a header-only library, you could just add eos's include directory to your project using `target_include_directories`. No linking or compilation is required.

**Comment by patrikhuber** [comment]
I am closing this as a duplicate of #68 :-)
