### ISSUE TITLE
Error reading the landmarks: Could not open landmark file: data/image_0010.pts

### ISSUE THREAD

**Issue by anny0316** [patrikhuber/eos#236]
Hello Patrik Huber:
Thank you very much for sharing your code. I am fresh, an error occurred while I run the fit-model program in visual studio 2017：“Error reading the landmarks: Could not open landmark file: data/image_0010.pts”. But, in the install directory, I can run fit-model successfully. I don't know why, I have read the file "readme" and have debugged the program fit-model. Can you help me? Thanks a lot.

**Comment by patrikhuber** [comment]
Hello,

You just need to adjust either the working directory or specify the command-line arguments.

Please use StackOverflow or a similar other website for "help"-type questions. You will be much better helped there.

Thanks.
