### ISSUE TITLE
run fit-model-multi, error occurred(assertion failed)

### ISSUE THREAD

**Issue by anny0316** [patrikhuber/eos#237]
Hi Huber, Thank you for the great library and making it available.
When I run the **fit-model-multi** project , an error occurred. I only input one image, command line parameters like this: -i data/image_0010.png -l data/image_0010.pts.  And options like this:
modelfile: ../share/sfm_shape_3448.bin
mappingsfile: ../share/ibug_to_sfm.txt
contourfile: ../share/bfm2009_model_contours.json
edgetopologyfile: ../share/sfm_3448_edge_topology.json
blendshapesfile: ../share/expression_blendshapes_3448.bin
![image](https://user-images.githubusercontent.com/43496750/49800673-11719680-fd83-11e8-84b3-78846a3fee01.png)
![image](https://user-images.githubusercontent.com/43496750/49800717-30702880-fd83-11e8-9ecb-4d828d118580.png)
I debugged the program. The error occurred in the contour_correspondence.hpp on 357 line.
Other programs(fit-model-simple and fit-model) can run successfully. Would you please help me to find out where is the problem. Thank you！

**Comment by patrikhuber** [comment]
Hi,

> contourfile: ../share/bfm2009_model_contours.json

It looks like you're passing the BFM2009 model contour file but are using the SFM. Use the model contour file from the SFM.

**Comment by anny0316** [comment]
Hi, Thank you very much for your quick response.
