### ISSUE TITLE
convert-bfm2017-to-eos.py error

### ISSUE THREAD

**Issue by viliusmat** [patrikhuber/eos#238]
Hello,
I was trying to convert bjm2017 to eos format using provided script. But I got an error:
File "convert-bfm2017-to-eos.py", line 48, in <module>
    model = eos.morphablemodel.MorphableModel(shape_model, expression_model, color_model, []) # uv-coordinates can be added here
TypeError: __init__(): incompatible constructor arguments...

It looks like that the problem is expression_model.
Thank You for Your answer.

**Comment by igriffer** [comment]
Same error with demo.py

**Comment by patrikhuber** [comment]
@igriffer The error in `demo.py` should be fixed in 698a7d9147f1058c6c703c0b34a3ef773489bd39, committed yesterday. Did you try before or after that commit?

**Comment by viliusmat** [comment]
Thank you.

**Comment by igriffer** [comment]
It works, thanks! Can you tell when version 1.0.0 can be installed from pip?

**Comment by patrikhuber** [comment]
The BFM scripts should now work again too, see 001e0157004f55881d889346d75990e8bd06a191.

@igriffer "Soon" - I'll update this issue once I update pip.
However in the meantime, you can still install eos with pip - `git clone` the repo and then do `pip install .\eos` on the source directory from GitHub, this will build and install it into pip :-)

**Comment by patrikhuber** [comment]
`v1.0.1` is now on pypi!
