### ISSUE TITLE
mesh error

### ISSUE THREAD

**Issue by sunjunlishi** [patrikhuber/eos#239]
![out isomap](https://user-images.githubusercontent.com/11845664/50041399-4fc2ca80-008f-11e9-8ccb-8a17a1e8b170.png)

**Comment by sunjunlishi** [comment]
it is newest code

**Comment by patrikhuber** [comment]
Hi,

Can you give a bit more information please? What model exactly are you using? What function? The `fit-model` example app? With what command-line parameters are you calling it? Can you try it on the example image in the `data/` folder? The more details you can give the better.

**Comment by sunjunlishi** [comment]
fit-model-simple.cpp
 const core::Image4u isomap = render::extract_texture(mesh, affine_from_ortho, core::from_mat(image));

**Comment by patrikhuber** [comment]
Works fine on my end. Please follow my advice above and provide more details - otherwise it's not possible to give any advice.

**Comment by sunjunlishi** [comment]
![out](https://user-images.githubusercontent.com/11845664/50043713-24060b80-00b4-11e9-8827-d61cd1e3e266.png)
![out isomap](https://user-images.githubusercontent.com/11845664/50043717-3aac6280-00b4-11e9-99e8-1af305b1b27e.png)

fit-model is same error.  i use the master newest code

**Comment by sunjunlishi** [comment]
![out isomap](https://user-images.githubusercontent.com/11845664/50043795-78f65180-00b5-11e9-894a-486b2501164a.png)
![out](https://user-images.githubusercontent.com/11845664/50043797-7d226f00-00b5-11e9-9d67-926f968499e5.png)

vs2015  32bit.  change nothing almost

**Comment by patrikhuber** [comment]
As written in the readme, VS2015 hasn't been supported anymore for quite a while. I'd recommend updating to VS2017. Also, I'd recommend building a 64bit executable.

Still, the images don't really help without further details.

I am afraid this really looks like a problem on your own system. I recommend a clean clone & clean build with VS2017 64-bit.

**Comment by sunjunlishi** [comment]
if (!detail::is_triangle_visible(glm::tvec4<float>(v0[0], v0[1], v0[2], v0[3]),
                                             glm::tvec4<float>(v1[0], v1[1], v1[2], v1[3]),
                                             glm::tvec4<float>(v2[0], v2[1], v2[2], v2[3]), depthbuffer))
            {
                // continue;
               // return;
            }

get out  of return.
it is ok

**Comment by sunjunlishi** [comment]
the code i pasted,i get rid of  //return。 i have resovled  the problem,althogh i don't know the realy reason

**Comment by patrikhuber** [comment]
That's indeed quite weird. I'd guess it's because of your VS 2015 and 32-bit build.

**Comment by sunjunlishi** [comment]
i have resolved it. out.isomap is bitmap is ok.
