### ISSUE TITLE
Not all methods inlined.

### ISSUE THREAD

**Issue by Smorodov** [patrikhuber/eos#24]
Not all methods inlined.
This is "headers only" library, and not inlined methods cause errors like "method already defined".

**Comment by elador** [comment]
You're right. With what compiler did you get the errors? I'm wondering why I didn't catch that yet.

**Comment by patrikhuber** [comment]
That's true. What compiler gave you the errors? I'm curious why I didn't catch it yet.

**Comment by Smorodov** [comment]
In MSVC 2015, in GCC.
Errors appeares when project includes several source files each of which uses this library and requires inludes.
Example compiles without any errors .

**Comment by patrikhuber** [comment]
I see. Thanks for reporting that! Sorry for missing it. Shall I fix it or do you want to create a PR?

**Comment by Smorodov** [comment]
No, I fixed it in local project file and made many small changes.
I think it would be better to make it by yourself, I don't want to spoil anything in your great project. Thanks for sharing it.
PS: By the way, take a look at https://github.com/ssloy/tinyrenderer project, it may be useful.

**Comment by patrikhuber** [comment]
I'll fix it soon then and push an update. I would be curious about your "many small changes" though, is there anything else that could be improved or that might be useful? I'm happy to have a look!

That tinyrenderer project looks really awesome and useful, thank you so much for pointing me to it! I actually have something quite similar on my todo-list, but it was always quite low priority.

**Comment by Smorodov** [comment]
My changes are mainly concerning interface of methods to adapt library to
existing project interface.
Many changes, but nothing serious.
I'll make PR if will find anything meaningful to improve :)

2016-04-11 21:56 GMT+03:00 Patrik Huber <notifications@github.com>:

**Comment by patrikhuber** [comment]
I see! Cool, thank you very much for your input and comments. I'll leave this issue open until I fix the missing `inline` keywords.

-Patrik

**Comment by patrikhuber** [comment]
I've finally fixed this in 41f0818a8182677f69ae6917f9296ebfaa37dbfa, sorry for the long wait.

I'll leave this ticket open a few more days until I merge the pending changes from `devel`, just to remind me to make sure to not merge any non-inlined methods.

Thanks again for reporting this!
