### ISSUE TITLE
how do many  images  convert to  a 3d image

### ISSUE THREAD

**Issue by LeeTaiTai** [patrikhuber/eos#249]
how do many  images  convert to  a 3d image? i use python

**Comment by LeeTaiTai** [comment]
many 2d images convert to a 3d image, and 2d images have different pose

**Comment by patrikhuber** [comment]
I suggest you have a look at the readme and the examples. A forum, perhaps reddit or a page like StackOverflow might be a more appropriate place to ask such questions.
Thanks!
