### ISSUE TITLE
how can i save a 3d image with angle of the last 2d image

### ISSUE THREAD

**Issue by LeeTaiTai** [patrikhuber/eos#250]
I implemented multiple images according to the example  model-fitting-multi  to generate a 3d, why is it expanded, I need a stereo 3d.
i get the first image ,but i want the second image. pls help me ,how can i save the second image.
![46352365-30212600-c68c-11e8-8987-1512498d7b05](https://user-images.githubusercontent.com/47777313/53460904-c3af2500-3a79-11e9-9712-0958f46a87b0.png)
![af08102c-e82c-11e6-88c1-811b89c3effc](https://user-images.githubusercontent.com/47777313/53460907-c4e05200-3a79-11e9-99f5-2ecff22073ed.jpg)

**Comment by patrikhuber** [comment]
Hi,

I think you would be best off to have a closer look at the structure of the example code and try to understand what it does. What the multi-image fitting example does is reconstruct one 3D model from all the input images, i.e. solve for one set of shape coefficients given all images. (And afterwards it does a simple merging of the textures.)
