### ISSUE TITLE
Boost and EOS are not compatible with vcpkg installation

### ISSUE THREAD

**Issue by zdptrsz** [patrikhuber/eos#251]
My program environment is：WIN10-64+VS2017-64，I can successfully compile the file。When I use the sample code：fit-model.cpp
------
    BOOST_STATIC_CONSTEXPR value_type      separator = L'/';
    BOOST_STATIC_CONSTEXPR value_type      preferred_separator = L'\\';
    BOOST_STATIC_CONSTEXPR value_type      dot = L'.';
------
the error:
E0434 Unable to initialize a reference of type "boost::filesystem::path::iterator &" with a value of type "boost::filesystem::path::iterator" (extremely qualified)
--
C2975 "unnamed-parameter": The template parameter of "mpark::detail::copy_assignment" is invalid and should be a compile-time constant expression.
--
 the boost of vcpkg is Incompatible with EOS.I think the code have to modify or install boost without vcpkg.Other people have encountered the same mistakes with me: https://web-answers.ru/c/chlen-e0145-quot-boost-filesystem-path-separator.html

**Comment by patrikhuber** [comment]
It seems to me like you're mixing two different errors - one about `boost::filesystem::path::iterator`, and one about `mpark::detail::copy_assignment`.

In any case, note that the boost error would only be relevant for building the example apps - the eos library itself doesn't use or need boost, so it will work just fine.

I am pretty sure thought that I myself am using Boost from vcpkg and I haven't had any problems. But I haven't upgraded `vcpkg` in a while. Perhaps this would be an issue for the [vcpkg repository](https://github.com/Microsoft/vcpkg)?

**Comment by patrikhuber** [comment]
Were you able to resolve your problems? Without more information (like e.g. the exact Boost version), it's unfortunately not possible to discern whether this is something we can do something on the side of the eos repository. It's most likely a Boost/compiler/vcpkg issue.

Feel free to re-open if you have more details and think it's an issue with eos.
Thanks!
