### ISSUE TITLE
No module named 'pix2face_estimation'

### ISSUE THREAD

**Issue by vishnu41** [patrikhuber/eos#253]
when i run: python3 scripts/pix2face_demo.py.
I got the following error:
Traceback (most recent call last):
  File "scripts/pix2face_demo.py", line 5, in <module>
    import pix2face_estimation.geometry_utils as geometry_utils
ImportError: No module named 'pix2face_estimation'

**Comment by patrikhuber** [comment]
There is no `scripts/pix2face_demo.py` script in this repository. Pix2face is a different piece of software I think - you must have posted this issue in the wrong repository.
