### ISSUE TITLE
Error: ‘variant_size_v’ is not a member of ‘mpark’

### ISSUE THREAD

**Issue by qpoisson** [patrikhuber/eos#254]
I have noticed a closed issue #232 reporting the same error. However, I don't think the answer there had solved the issue.  My environment is   g++ (Ubuntu 7.1.0-10ubuntu1~16.04.york0) 7.1.0, which is a newer version than the author suggested in #232

**Comment by patrikhuber** [comment]
Hi, may I ask what the issue was in your case?

In any case if you're building with `CMAKE_CXX_STANDARD 17` (which should be the default, actually), `mpark::variant` shouldn't be used at all.

**Comment by qpoisson** [comment]
Hi,
I encountered building error: " variant_size_v’ is not a member of ‘mpark’ ", when using C++14 .   There is no error when using  c++17.

**Comment by patrikhuber** [comment]
Thanks for the feedback. Hmm, there shouldn't be an error on gcc-7. I'll leave this open, it might be good to investigate this at some point.

**Comment by renwenze** [comment]
i think gcc us not the problem

**Comment by patrikhuber** [comment]
I've updated to the latest `mpark::variant` master branch version in bd590bfc2c0a81a09a0d9751c774740261c4679b. This is now released as eos v1.2.0/1.2.1. IIRC I saw in their commits that they fixed some compiler errors on earlier compilers (gcc 6/7 or so), so this might likely fix any issues that might have been present.

If there are still issues with `mpark::variant` when compiling eos in C++14 mode, please report here or in https://github.com/mpark/variant.
