### ISSUE TITLE
how to load the model(load_model) using .bin file

### ISSUE THREAD

**Issue by vinccccho** [patrikhuber/eos#27]
Hi, in your code

morphablemodel::load_model(modelfile.string());

you used a .bin file to load the a Morphable Model.

I wonder what is inside the .bin file? Is it related to the reference.obj?

I am quite confused with that file.

Thanks

**Comment by patrikhuber** [comment]
Hi,
It contains the model data, you can have a look at the member variables of `MorphableModel` and `PcaModel`. It's basically the mean, eigenvalues and PCA basis. It's described quite well in the code, as well as in our [VISAPP paper](http://www.patrikhuber.ch/files/3DMM_Framework_VISAPP_2016.pdf).

**Comment by vinccccho** [comment]
So is there any relation between the .bin file and the reference.obj? Does it mean that the reference model is the mean model of the scans?
And in the mapping file like ' 9    33 ; chin bottom ', '9' is the index of the 2d landmark. So '33' is the 33rd point in the reference model?

**Comment by patrikhuber** [comment]
The reference is kind of a low-resolution mean of the scans. It's not the exact mean of the scans, it's just the initial 3D reference face that puts all scans into dense correspondence. What matters is that the 845 vertices of the reference represent the same points (i.e. are in dense correpondence) amongst the Morphable Model and all its resolution level. Let's say vertex 150 in the reference is the nose tip - vertex 150 will also be the nose tip in the 3448-vertex 3DMM, and in the full-resolution model.

Yes, your description of the mapping file is 100% correct.
