### ISSUE TITLE
pip install eos-py==1.1.2 fails with Python2

### ISSUE THREAD

**Issue by francoisruty** [patrikhuber/eos#274]
Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-MgGlBR/eos-py/setup.py", line 64, in <module>
        with open(os.path.join(this_directory, 'README.md'), encoding='utf-8') as f:
    TypeError: 'encoding' is an invalid keyword argument for this function

I got the same problem if I try to install each of the past published versions

**Comment by francoisruty** [comment]
after some googling it seems using io.open would work both in python 2 and python 3 (I'm using python 2.7)

**Comment by francoisruty** [comment]
ok so I just moved all my project to python 3 and now it works
I suggest to update the documentation to mention pip3 install instead of pip install, as eos-py is currently not installable with pip
It might be though if we just remove the long_description field that uses this file open command (or use io.open as stated earlier)

**Comment by imaccormick275** [comment]
@francoisruty ... would you be able to send me your environment setup/dependancies? I'm having trouble with pip3 install eos-py. Getting the following error message which I don't follow:

Command "/Library/Frameworks/Python.framework/Versions/3.6/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/private/var/folders/3q/d465_w_d79q5k_t3j9ky91yw0000gn/T/pip-build-l2erjh7w/eos-py/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/3q/d465_w_d79q5k_t3j9ky91yw0000gn/T/pip-kivlxde7-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/3q/d465_w_d79q5k_t3j9ky91yw0000gn/T/pip-build-l2erjh7w/eos-py/

**Comment by francoisruty** [comment]
Someone asked me for my environment (how I installed eos-py with pip3), here it is, it's a dockerfile:

FROM nvidia/cuda:10.0-cudnn7-devel-ubuntu16.04

RUN apt-get update --fix-missing
RUN apt-get install -y python3 python3-dev python3-pip wget vim libglib2.0-0 libsm6 libxext6 libxrender-dev build-essential cmake pkg-config libx11-dev libatlas-base-dev libgtk-3-dev make cython3 python3-setuptools

#Install gcc 7 for eos installation
RUN apt-get install -y software-properties-common python3-software-properties && add-apt-repository ppa:ubuntu-toolchain-r/test && apt update && apt install -y g++-7
#Install cmake 3.8 for eos installation
RUN apt-get purge -y cmake && wget https://github.com/Kitware/CMake/releases/download/v3.15.1/cmake-3.15.1.tar.gz && tar -xzvf cmake-3.15.1.tar.gz && cd cmake-3.15.1 && ./bootstrap && make -j4 && make install

RUN pip3 install numpy==1.15.0
RUN pip3 install opencv-python==3.4.0.12
RUN pip3 install dlib
RUN pip3 install scipy==0.16
RUN CC=`which gcc-7` CXX=`which g++-7` pip3 install eos-py

**Comment by imaccormick275** [comment]
deleted comment as solved my issue. didn't have xcode installed: xcode-select --install

**Comment by patrikhuber** [comment]
Hi,

Sorry for the slightly late reply.

I'm going to close this - [Python 2 is at the end of its lifetime](https://pythonclock.org/).

Also I'd say whether the correct command to use is `pip` or `pip3` is the user's responsibility - they should know their distribution and how to use the correct Python versions. On many distributions, Python 3 is the default and the command to use Python 3's pip is simply `pip`. The same also applies for Python 3 virtualenvs.
