### ISSUE TITLE
Mesh Point Index and Symmetry

### ISSUE THREAD

**Issue by imaccormick275** [patrikhuber/eos#277]
Is there any documentation on the mesh indexes and their symmetry? Trying to extract some points and is important I get the symmetry correct.

**Comment by patrikhuber** [comment]
See the [share/](https://github.com/patrikhuber/eos/tree/master/share) directory, and the description of `sfm_reference_symmetry.txt` in the `readme.txt` in that directory. This is a symmetry list for the 745 vertices reference (template) mesh. I am not sure whether the subdivided 3448 vertices mesh is still 100% symmetric. Most vertices should have a symmetric counterpart but there might be the odd one out where the subdivision created a slightly non-symmetric topology. You'd best ask CVSSP about it, or perhaps easier, just write a short script that computes (and checks) the symmetric counterpart for each vertex. If you need help doing that, Google or [StackExchange](https://stackexchange.com/) is probably a good friend.

If you're referring to the [4DFM](https://4dface.io/4dfm), then we can also provide a full symmetry list for all vertices.
