### ISSUE TITLE
different performance when chang a landmark detector

### ISSUE THREAD

**Issue by ZHANG-SHI-CHANG** [patrikhuber/eos#279]
hello, eos is a good job! thks~
I meet some problems when reduce the points num by change a  landmark detector, the result is bad。
![image](https://user-images.githubusercontent.com/30692249/63508096-d461c480-c50b-11e9-8e2c-ae7a593f17fa.png)
![image](https://user-images.githubusercontent.com/30692249/63508105-d75cb500-c50b-11e9-872f-c9c36b2a9c80.png)
can you give some advice? thx~

**Comment by patrikhuber** [comment]
Hi,

My guess is that you've got the landmark mappings wrong. Make sure to get the 2D landmark -> 3D vertex indices mapping correct.
Please debug and understand your code. Thanks!

**Comment by ZHANG-SHI-CHANG** [comment]
> Hi,
> 
> My guess is that you've got the landmark mappings wrong. Make sure to get the 2D landmark -> 3D vertex indices mapping correct.
> Please debug and understand your code. Thanks!

solved it, thx~
