### ISSUE TITLE
gcc seems to need -pthread too

### ISSUE THREAD

**Issue by alikharrat** [patrikhuber/eos#28]
Hi,

I'm using ubuntu 16.04, i got opencv 3.1, when i try to use "make && make install" i got this error:
"
[ 25%] Linking CXX executable fit-model
/usr/bin/ld: CMakeFiles/fit-model.dir/fit-model.cpp.o: undefined reference to symbol 'pthread_create@@GLIBC_2.2.5'
//lib/x86_64-linux-gnu/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
examples/CMakeFiles/fit-model.dir/build.make:100: recipe for target 'examples/fit-model' failed
make[2]: *** [examples/fit-model] Error 1
CMakeFiles/Makefile2:119: recipe for target 'examples/CMakeFiles/fit-model.dir/all' failed
make[1]: *** [examples/CMakeFiles/fit-model.dir/all] Error 2
Makefile:150: recipe for target 'all' failed
make: *** [all] Error 2"
Can you help me to solve this please? 
Thank you in advance.

**Comment by patrikhuber** [comment]
Hi,

Hmm I thought I fixed that, I'll check. What you're most likely missing is linking to pthreads.

Add this to `CMakeLists.txt`:

`set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -pthread")`

Or in any other way convenient for you add `pthread` to the command line of the linker.

**Comment by alikharrat** [comment]
Hi,
that lanes exists already in the CMakeLists, i'm using ubuntu 64bit,
To build i changed in the CmakeLists the opencv version required to  3.1.0 maybe this caused the problem i'm not sure.
I will try to use ubuntu 32bit and see if it works.
If you have any other idea that would be great, thank you.

**Comment by patrikhuber** [comment]
I'll certainly investigate, it needs to run on Ubuntu 16.04 without problems - I'll make sure of that. I'm just a bit busy, the earliest I can look at it is next week.

You can do `make VERBOSE=1` and check the linker command line whether there's a `-pthread` there or not. And then you could try to modify the arguments, in clang it's called `-lpthreads` I think, maybe gcc changed its naming, try with and without an "l" or "s". What gcc version are you using btw?

In the mean time if you want to try another Ubuntu, I recommend you try 14.04 64bit. I wouldn't try 32bit and I don't think it would make any difference to the problem.

**Comment by alikharrat** [comment]
I'm using gcc version 5.3.1, with make VERBOSE=1 i got this: 
`/usr/bin/cmake -H/opt/eos -B/opt/build --check-build-system CMakeFiles/Makefile.cmake 0
/usr/bin/cmake -E cmake_progress_start /opt/build/CMakeFiles /opt/build/CMakeFiles/progress.marks
make -f CMakeFiles/Makefile2 all
make[1]: Entering directory '/opt/build'
make -f examples/CMakeFiles/fit-model.dir/build.make examples/CMakeFiles/fit-model.dir/depend
make[2]: Entering directory '/opt/build'
cd /opt/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /opt/eos /opt/eos/examples /opt/build /opt/build/examples /opt/build/examples/CMakeFiles/fit-model.dir/DependInfo.cmake --color=
Dependee "/opt/build/examples/CMakeFiles/fit-model.dir/DependInfo.cmake" is newer than depender "/opt/build/examples/CMakeFiles/fit-model.dir/depend.internal".
Dependee "/opt/build/examples/CMakeFiles/CMakeDirectoryInformation.cmake" is newer than depender "/opt/build/examples/CMakeFiles/fit-model.dir/depend.internal".
Scanning dependencies of target fit-model
make[2]: Leaving directory '/opt/build'
make -f examples/CMakeFiles/fit-model.dir/build.make examples/CMakeFiles/fit-model.dir/build
make[2]: Entering directory '/opt/build'
[ 25%] Building CXX object examples/CMakeFiles/fit-model.dir/fit-model.cpp.o
cd /opt/build/examples && /usr/bin/c++    -I/opt/eos/include -I/opt/eos/3rdparty/cereal-1.1.1/include -isystem /usr/local/include/opencv -isystem /usr/local/include -I/usr/include/eigen3 -I/opt/eos/3rdparty/glm-0.9.7.0  -std=c++14   -o CMakeFiles/fit-model.dir/fit-model.cpp.o -c /opt/eos/examples/fit-model.cpp
[ 50%] Linking CXX executable fit-model
cd /opt/build/examples && /usr/bin/cmake -E cmake_link_script CMakeFiles/fit-model.dir/link.txt --verbose=1
/usr/bin/c++    -std=c++14   CMakeFiles/fit-model.dir/fit-model.cpp.o  -o fit-model -rdynamic /usr/local/lib/libopencv_imgcodecs.so.3.1.0 -lboost_system -lboost_filesystem -lboost_program_options /usr/local/lib/libopencv_imgproc.so.3.1.0 /usr/local/lib/libopencv_core.so.3.1.0 -Wl,-rpath,/usr/local/lib: 
/usr/bin/ld: CMakeFiles/fit-model.dir/fit-model.cpp.o: undefined reference to symbol 'pthread_create@@GLIBC_2.1'
//lib/i386-linux-gnu/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
examples/CMakeFiles/fit-model.dir/build.make:100: recipe for target 'examples/fit-model' failed
make[2]: *** [examples/fit-model] Error 1
make[2]: Leaving directory '/opt/build'
CMakeFiles/Makefile2:119: recipe for target 'examples/CMakeFiles/fit-model.dir/all' failed
make[1]: *** [examples/CMakeFiles/fit-model.dir/all] Error 2
make[1]: Leaving directory '/opt/build'
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2
`

**Comment by patrikhuber** [comment]
Indeed the `-pthread` flag is missing from the linker command line. Can you please add this line outside of any `if`-statements in `CMakeLists.txt` and try again:

`set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -pthread")`

**Comment by alikharrat** [comment]
This is the screenshoot 
![cmake](https://cloud.githubusercontent.com/assets/4748182/15092396/7c1fbad6-141d-11e6-98e9-72e4b5472458.png)

that lane exists but i still don't know why he can't detect it

**Comment by alikharrat** [comment]
I just solved the Problem the statement is miss placed. Thank you for your help

**Comment by patrikhuber** [comment]
Yes as I said I wanted you to try the statement *outside* of any `if`-block. 

It's not exactly misplaced, it's just a bit outdated - it's only in the clang `else`-branch. Recent versions of gcc require it too. I'll update it next week.

**Comment by alikharrat** [comment]
Ok, thank you again for your help.

**Comment by alikharrat** [comment]
I don't know i have to open another issue but to day i tried to run one of the examples (fit-model) i got this error:
"fit-model: /opt/eos/include/eos/render/texture_extraction.hpp:110: cv::Mat eos::render::extract_texture(eos::render::Mesh, cv::Mat, cv::Mat, cv::Mat, bool, eos::render::TextureInterpolation, int): Assertion `image.type() == CV_8UC3' failed.
Aborted (core dumped)"
do you have any ideas?
Thank you

**Comment by patrikhuber** [comment]
It says your input image is not a 3-channel uchar image. Most likely you tried to run it on an image with alpha channel. I believe OpenCV's function is called `cv::cvtColor(...)` and you have to give it a flag like `cv::RGBA2RGB`.
Did you try to run it with the example image btw? Then you shouldn't run into troubles. Maybe the path to the image is wrong?

**Comment by alikharrat** [comment]
I tried to run with the example image, when the path is wrong he says he couldn't open the file so i changed the paths and i got this problem.

**Comment by alikharrat** [comment]
i don't know what really happened but it worked after restarting my computer.
thank you, for your help.

**Comment by patrikhuber** [comment]
Great! I'll leave this issue open until I fix the `pthreads` problem in the `CMakeLists.txt`.

**Comment by patrikhuber** [comment]
I fixed the pthreads flag problem in 01e4af0cef4b955df50934fc7e8d5754a14108d7, master and devel branch. gcc-5.4 on Ubuntu 16.04 definitely needs it. In the longer term it would be good to switch to target-based CMake flags but the old style works for now.
