### ISSUE TITLE
how to compute image texture loss?

### ISSUE THREAD

**Issue by ZHANG-SHI-CHANG** [patrikhuber/eos#281]
thx~ for your greate job! 
Can this work compute image texture loss to get texture coeffs?

**Comment by ZHANG-SHI-CHANG** [comment]
> thx~ for your greate job!
> Can this work compute image texture loss to get texture coeffs?

![image](https://user-images.githubusercontent.com/30692249/63632252-4ac60a00-c665-11e9-9dd9-e2efdffb531d.png)
similar lmks but big diff, i think texture loss maybe work it.

**Comment by patrikhuber** [comment]
Hi,

Texture loss is not one of the main functionalities of eos. But eos is a lightweight framework that gives you all the infrastructure that you need to write a texture loss by yourself. I could recommend Ceres - you could have a look at https://github.com/patrikhuber/eos/blob/13f3add0bd570855cb3d339f659694a25d366c49/include/eos/fitting/ceres_nonlinear.hpp#L203-L212 and [fit-model-ceres](https://github.com/patrikhuber/eos/blob/master/examples/fit-model-ceres.cpp) (read through the `fit-model-ceres` example carefully, line-by-line! It's not a ready-made, "does-everything" example.)
