### ISSUE TITLE
About the detail of blendshape fitting

### ISSUE THREAD

**Issue by DanielMao2015** [patrikhuber/eos#285]
Hi, the eos is very efficient and the problem is that in my application, the detail of expresion is not reconstructed very well. For example, when I lift my brow, the corresponding brow of avatar does not action correspondently, so does about the nose. I would appreciate any suggestion that help with the problem.

**Comment by patrikhuber** [comment]
Hi,

Similar questions have been asked a few times before. Have a search through the open & closed issues and you should find a few suggestions there.
