### ISSUE TITLE
The 3D face reconstruction image looks so weird， how to improve it?

### ISSUE THREAD

**Issue by Chen-Jinlong** [patrikhuber/eos#288]
Hi, Patrik. 
     I got a problem when applied BFM2017 on eos. Since bfm2017 had no blendshapes file, I used expression PCA model which was extracted from the BFM2017 converted file. And it worked successfully, but the result was not so satisfied.  The reconstructed image is below:
![image](https://user-images.githubusercontent.com/56462034/70426525-24aa6580-1aae-11ea-9cb2-f0b4b807f4df.png)
![image](https://user-images.githubusercontent.com/56462034/70426597-4572bb00-1aae-11ea-8760-07d83a5632fa.png)
The shape was almost correct, but the color or the texture was not. It's obvious that there was a ghost around the eyes. I tried other images, and the results still appeared. 
How can I fix this problem? Do you have some advice?

**Comment by patrikhuber** [comment]
Hi,

I am going to reply here as you embedded the pictures here. I am not sure what your question is, what looks "so weird"? Do you expect it to look like in the second image? The second image is per-vertex colouring ("albedo") from the statistical model, the first one is texture remapping.

Also note that I believe in the first picture, when you view a mesh in MeshLab that contains both per-vertex colours (which in this case would probably be the mean face) **and** texture, then I think that MeshLab blends them together. You can disable that in the sidebar options I believe.

If you need better texture (in whatever sense "better" means), I recommend you refine the landmark fitting by using some method on top, and/or do some texture blending.

**Comment by Chen-Jinlong** [comment]
> Hi,
> 
> I am going to reply here as you embedded the pictures here. I am not sure what your question is, what looks "so weird"? Do you expect it to look like in the second image? The second image is per-vertex colouring ("albedo") from the statistical model, the first one is texture remapping.
> 
> Also note that I believe in the first picture, when you view a mesh in MeshLab that contains both per-vertex colours (which in this case would probably be the mean face) **and** texture, then I think that MeshLab blends them together. You can disable that in the sidebar options I believe.
> 
> If you need better texture (in whatever sense "better" means), I recommend you refine the landmark fitting by using some method on top, and/or do some texture blending.

thanks，I'll have a try.

**Comment by sunjunlishi** [comment]
No eyes closed, crooked mouth expression, how to improve rich expression fitting
