### ISSUE TITLE
Script for converting Basel model.

### ISSUE THREAD

**Issue by Smorodov** [patrikhuber/eos#29]
Hi, in VISAPP paper mentioned script for convertion of Basel model to format accepted in this application. Was it published somewere ?

**Comment by patrikhuber** [comment]
Hi,

It existed half a year ago but was not published yet, and in the meantime a few things have changed. I'm actually working on json import/export of the models right now, and then it's easy to convert and load the Basel model (it's also easy now in fact but requires writing some custom text files conversions).

I am away this week but might continue working on it, I expect to finish it next week. Does that work for you?

**Comment by Smorodov** [comment]
Great, thank you very much.

**Comment by samsgates** [comment]
Patrikhuber:  thanks for working on Basel model convertion script. 
It will very helpful to me to implement custom model

**Comment by patrikhuber** [comment]
Just wanted to update you guys that I'm nearly done. It's not ideal yet (json files are large and not really concise, and converting takes long). I'll finish some testing and put it in the repo in the next couple days.

**Comment by samsgates** [comment]
Patrikhuber: Thanks for your update

**Comment by patrikhuber** [comment]
I pushed a first working version of the script in c8dc5ac4d689028142e3d83f25f102bd73acbe62. It works, but it's not so nice yet.

* Converting takes >15 minutes.
* The converted json file is huge (>1 GB) - the generated json is really suboptimal. I'll have to see if it's possible to generate better json serialisation with cereal.
* I divided the BFM's shape by 1000 (from mm to cm, this is more of a convenience thing), and the colour by 255 (to go from [0, 255] to [0, 1]) to make it equal to the SFM's domains. I have to figure out whether we need to divide/scale the basis and eigenvalues too by some factor, I haven't thought about that yet. There might be a bug there now.
* Also, rendering with `eos::render` doesn't work yet for some (probably trivial) reason (produces a black image), but the created obj's are fine.

After converting to json, I recommend you run `json-to-cereal-binary` to create a small `.bin` file that you can then subsequently use like the Surrey Face Model file in this repo.

**Comment by patrikhuber** [comment]
I forgot, you need [JSONlab](http://www.mathworks.com/matlabcentral/fileexchange/33381-jsonlab--a-toolbox-to-encode-decode-json-files) for Matlab to write the file. It's trivial to install.

Also I noticed the script doesn't save the final model file when run with all 199 basis vectors. Set `nb = 99;` for now and it'll write the file. Possibly JSONlab (or Matlab) has issues with writing files larger than 1 GB. Let's see what solutions we can find to that.

**Comment by patrikhuber** [comment]
For the large JSON issue, see USCiLab/cereal#288.

**Comment by samsgates** [comment]
i have generated JSON file successfully, but i don't know how to run "json-to-cereal-binary" command, this command not available in "http://uscilab.github.io/cereal/index.html" app. 
where shall i get this command ?

**Comment by patrikhuber** [comment]
It's in the eos `devel` branch, see [here](https://github.com/patrikhuber/eos/tree/devel/utils).

**Comment by samsgates** [comment]
when i run "json-to-cereal-binary" the below error message shown as output
===
libc++abi.dylib: terminating with uncaught exception of type cereal::RapidJSONException: rapidjson internal assertion failure: flags_ & kIntFlag
Abort trap: 6
====

**Comment by patrikhuber** [comment]
Hmm, I don't have an immediate clue what that could be. `libc++abi.dylib` looks like Mac, which I have not much experience on. I suggest you debug through it and look at the call stack to find the place in our library code where the crash originates.

**Comment by samsgates** [comment]
i can't open JSON file because of 980mb file size. i want to see json file structure to create json from model file. can you share json structure

**Comment by patrikhuber** [comment]
You can still open it in any decent editor (like e.g. Notepad++), it's just a bit slow naturally.

In any case, in the [conversion script](https://github.com/patrikhuber/eos/blob/devel/share/convert_bfm2009_to_json.m#L39-L40), just set `nb` to a smaller value (3 or so) and optionally you can set `nt` to a smaller value too (that one has to be a multiple of 3, and it'll give you an incomplete mesh, but doesn't matter if you just want to look at the json).

**Comment by samsgates** [comment]
when i tried to build dev branch "https://github.com/patrikhuber/eos/tree/devel/utils" 
the below error message triggered, you have any idea how to resolve this issue?

![attachment3](https://cloud.githubusercontent.com/assets/4558944/17585945/6ff721da-5fdc-11e6-92c7-3d1c7f64aa84.png)

**Comment by patrikhuber** [comment]
@samsgates As I mentioned above can you please open a new issue for this? It's not related to this issue at all. Thanks.

**Comment by patrikhuber** [comment]
Using json for files that are this large might be a bit of a lost cause, even if we can optimise the generated json. I've thus removed the old script and added a new one in 1c51f4c3a4d0e61d66efb9546f145726547e3748 that converts the BFM into a raw binary file. d36b8d419866e08cafa4354f794ccb5a70a110ad then adds an app that converts such a raw binary file into the eos cereal model format that can be used by any of eos's app/library functions.

The advantage of doing it via a raw binary file in contrast to for example calling the Matlab library from C++ is that users don't need to have the Matlab compiler runtime installed, and we also don't need to find these Matlab libraries with CMake. Users who wish to convert the model can just start Matlab, run the `.m` script, and then use `bfm-binary-to-cereal` to convert the model to the eos model format.

Closing this as fixed!
