### ISSUE TITLE
Why I cannot display the out.obj with OpenGL?

### ISSUE THREAD

**Issue by yygbruce** [patrikhuber/eos#291]
I cannot display the out.obj correctly with OpenGL, when I set the projection matrix and modelview matrix for the glsl shader.But I can use the class RenderingParameters to draw wireframe on the image, so the render parameters is right.What's wrong with me? By the way, have a interface for raycasting?

**Comment by patrikhuber** [comment]
Hi,

"display the out.obj correctly with OpenGL" sounds a bit weird. Maybe try opening your out.obj with MeshLab?

It sounds like you need to spend some time debugging your OpenGL matrices.

There is some ray casting stuff [here](https://github.com/patrikhuber/eos/blob/master/include/eos/render/ray_triangle_intersect.hpp) and [here](https://github.com/patrikhuber/eos/blob/master/include/eos/fitting/closest_edge_fitting.hpp).

**Comment by yygbruce** [comment]
Sorry ! I mean that I can display the out.obj correctly, but the position is wrong when I set the model-view matrix and projection matrix.I can use RendererParameters draw wireframe as you, I think maybe because of the viewport parameter.the viewport[3] is -height.

**Comment by yygbruce** [comment]
I have readed the source code, and know the fountion of ray_triangle_intersect, but I cannot find the correct ray_origin and ray_direction when I pick the screen.Can you give me some advice?

**Comment by yygbruce** [comment]
Thanks! I have solved the question through rasterization.
