### ISSUE TITLE
Black holes (nostrils)

### ISSUE THREAD

**Issue by virtualenv** [patrikhuber/eos#297]
Dear Patrik,

First of all, amazing project! Thanks so much for sharing!
I am having this issue with 95% of the faces files that I have.
Please let me know what I could be doing wrong.
I know this was already asked here : Black line in isomap extraction #4

	std::tie(mesh, rendering_params) = eos::fitting::fit_shape_and_pose(*morphable_model_with_expressions, landmarks, landmark_mapper, frame.cols, frame.rows, edge_topology, ibug_contour, model_contour, 5, eos::cpp17::nullopt, 30.0f);
	// Extract the texture from the frame using given mesh and camera parameters:
	const Eigen::Matrix<float, 3, 4> affine_from_ortho = eos::fitting::get_3x4_affine_camera_matrix(rendering_params, frame.cols, frame.rows);
	isomap = eos::render::extract_texture(mesh, affine_from_ortho, eos::core::from_mat(frame), true);
	isomap = eos::render::detail::interpolate_black_line(isomap); <-- doesn't work for the nostrils.

![error_1](https://user-images.githubusercontent.com/582991/75206922-3834a680-5756-11ea-9c46-44b4602c75f0.JPG)
![error_2](https://user-images.githubusercontent.com/582991/75206924-3965d380-5756-11ea-9ae0-9707e6a1283c.JPG)
![output isomap](https://user-images.githubusercontent.com/582991/75207038-703be980-5756-11ea-8da8-98bd39fd91c5.jpg)

Thank you!!!

**Comment by patrikhuber** [comment]
Hi,

Thanks!

This looks like it's working as expected. These triangles ("patches of skin") are occluded, they're not in view. There is no data (texture) there in your image of that region. What would you expect to be there?

If you want texture data for occluded regions, you'll have to decide what strategy you want of how to fill it (blend/interpolate, mirror, use per-vertex colour from the model, etc.).

**Comment by virtualenv** [comment]
Just thought : isomap = eos::render::detail::interpolate_black_line(isomap); would fill those gaps.
"  What would you expect to be there? "
Ok, sorry for the dumb question, thank you for your time.

**Comment by patrikhuber** [comment]
No worries!

The `eos::render::detail::interpolate_black_line(...)` function actually only "fixed" a very specific problem with a vertical line occurring in the centre of the texture map. However as indicated in #4, this was fixed in 6875e08b6678046e9c04fc5860383f39d22edd4f. Actually, since the problem was properly fixed, I could've removed the `eos::render::detail::interpolate_black_line(...)` function a while ago. It can definitely be removed now and I will do so - I opened #298 to track that. Thank you!

**Comment by virtualenv** [comment]
Thank you for the explanation.
May I ask if there is any function in your library, that could fill the occluded patches of skin ?
Thank you once again.

**Comment by virtualenv** [comment]
Thank you for the explanation.
May I ask if there is any function in your library, that could fill the occluded patches of skin ?
Thank you once again.

**Comment by patrikhuber** [comment]
There isn't currently any ready-made function that fills occluded patches.

**Comment by virtualenv** [comment]
Thank you.
