### ISSUE TITLE
fit-model on own images

### ISSUE THREAD

**Issue by alikharrat** [patrikhuber/eos#30]
Hi,
i'm trying to use the fit-model, with other images but i coudn't make it, should i have any constraint on the inputs or how should i choose my inputs? 
Thank you.

**Comment by patrikhuber** [comment]
Hi,
There are no constraints on the inputs. I'm not really sure what you mean.

-Patrik

**Comment by alikharrat** [comment]
Hi,
so what i did is i used another image with another file containing the landmarks point (the like the original one) but i got an error:
"fit-model: /opt/eos/include/eos/fitting/nonlinear_camera_estimation.hpp:254: eos::fitting::RenderingParameters eos::fitting::estimate_orthographic_camera(std::vector<cv::Vec<float, 2> >, std::vector<cv::Vec<float, 4> >, int, int): Assertion `image_points.size() >= 6' failed.
Aborted (core dumped)"
i don't know what's really the problem

**Comment by patrikhuber** [comment]
The assertion reads `image_points.size() >= 6`. You need to give it at least 6 landmarks. In the demo app, you actually need to give all 68 ibug landmarks, since the ibug `pts` format expects all of them, and in the correct order.

**Comment by alikharrat** [comment]
What do you mean the correct order? sorry for having so many questions

**Comment by patrikhuber** [comment]
The [example](https://github.com/patrikhuber/eos/blob/master/examples/data/image_0010.pts) uses the [ibug format](http://ibug.doc.ic.ac.uk/resources/facial-point-annotations/). The landmarks in the `.pts` file need to be in that order, see the figure in the second link.

This is just to keep the example simple and working with the well-known ibug images. You can easily modify [the reader](https://github.com/patrikhuber/eos/blob/master/examples/fit-model.cpp#L58) if you want to only use a subset of them.

**Comment by alikharrat** [comment]
thank you, i will try things, then i will give you a feedback.

**Comment by alikharrat** [comment]
Hi patrik,
Sorry i didn't see your reply, I will try this.
Thank you
