### ISSUE TITLE
Python: Extracted texture has wrong rotation

### ISSUE THREAD

**Issue by MatthewCaruana** [patrikhuber/eos#301]
I was following and building upon your face fitting example (for Python) while also making my own implementation. When trying out your example code I decided to do the following in addition to the code that is provided in the demo.py file:
    
    eos.core.write_textured_obj(mesh, "models/test.obj")

    image = cv.imread('Images_Final/image_0010.png')
    isomap = eos.render.extract_texture(mesh, pose, image)

    cv.imshow("image", image)
    cv.imshow("isomap", isomap)

    cv.waitKey(0)
    cv.destroyAllWindows()

The results that came with these commands (specifically the extracted texture) is the following:

![image](https://user-images.githubusercontent.com/29656600/78009671-a8c87780-7341-11ea-989e-3874e268a19f.png)

As can be seen, it is orientated wrongly. I am using the latest pip version of the package, however, I also tried using 1.0.1 version as was discussed in #129 with the same result. Inherently, when I apply the texture to the model through MeshLab, it is keeping the same rotation as can be seen below. 

![image](https://user-images.githubusercontent.com/29656600/78009971-1aa0c100-7342-11ea-9eeb-d8c9c7a762ba.png)

Is there some sort of function that I have forgot to implement or call?

**Comment by patrikhuber** [comment]
Hi,

As you can see, the texture map is just 90° rotated. You can probably just rotate it and it should be fine.

I think this was an issue in the `Image` Python bindings which I fixed recently in the devel branch: https://github.com/patrikhuber/eos/compare/devel

Let me know how that goes. Thanks!

**Comment by MatthewCaruana** [comment]
Managed to acquire the rotated texture map. Sorry I did not try out the devel branch binding as I am running rather tight on getting things done with my studies.

**Comment by patrikhuber** [comment]
Great!

I'll leave this one open until the changes from the devel branch are merged.

**Comment by patrikhuber** [comment]
This has now been merged into the master branched and released in eos 1.2.0/1.2.1! :-) Thanks again for pinging me on this issue here.
