### ISSUE TITLE
no effect from changing isomap resolution 

### ISSUE THREAD

**Issue by wildeyevr** [patrikhuber/eos#304]
interested in rendering isomaps at a higher resolution... when I pass in a new value (like 2048), the resulting isomaps are still 512... am I missing something?

**Comment by patrikhuber** [comment]
Hi,

When you pass a new value to what?

**Comment by wildeyevr** [comment]
Hey thanks for getting back and sorry for not being clear at all... when using render::extract_texture()... it looks like you have it set up to pass in an int for the resolution of the texture... but it doesn't have any effect when I do... also doesn't write any textures out if I change it from 512

**Comment by patrikhuber** [comment]
Hmm, I've used that parameter before to create texture maps of higher resolutions, so it should work. I would recommend you to run a debug build and step through it and see what's happening - it should be fairly simple. You can also try `render::v2::extract_texture(...)` though you may or may not run into other issues there.

**Comment by wildeyevr** [comment]
Hey Patrik... thanks for getting back... ended up being a silly mistake on my part... works fine... appreciate your help

**Comment by patrikhuber** [comment]
Great, thanks for reporting back!
