### ISSUE TITLE
Will your theory be inaccurate on the edge

### ISSUE THREAD

**Issue by sunjunlishi** [patrikhuber/eos#305]
Your algorithm is refined and the code is simple.

Using 3D rotation translation and other operations, project to 2D, and then correct with 2D key points.

The 17 points of the starting 3D edge, after rotation, will go around to the back, and the key points of 2D will not coincide, which is the problem. Does your SFM _edge_topology.json solve this problem?
![QQ图片20200419123254](https://user-images.githubusercontent.com/11845664/79679624-f0a03780-8239-11ea-9df6-adeaa0b3f6b7.png)

**Comment by patrikhuber** [comment]
Hi @sunjunlishi,

You can find the details of the contour fitting in my [PhD thesis](http://epubs.surrey.ac.uk/842138/), there's a section on contour fitting. Additionally, the code should be fairly well documented and it's based on the paper by Bas et al. (see the eos README.md).

Thanks.

**Comment by sunjunlishi** [comment]
thank you very much,author
