### ISSUE TITLE
Error loading the landmark mappings: unordered_map::at: key not found

### ISSUE THREAD

**Issue by milad-ahmadi** [patrikhuber/eos#307]
Hello,
I make and build eos on mac 10.15 with clang=10. when I run 'fit_model' in example I faced with:
"Error loading the landmark mappings: unordered_map::at: key not found" in loading "ibug_to_sfm.txt".

**Comment by patrikhuber** [comment]
Hi,

I currently don't have access to macOS. Since this is a runtime error and not a compile error, I think this is likely a problem on your end with how you run `fit-model`. I would suggest that you step through the relevant part in the debugger, and check what's going wrong.

**Comment by patrikhuber** [comment]
@milad-ahmadi Did you make any progress on this?
I am going to close this issue, as it is likely a problem on your end. Feel free to re-open if you have more information and it's an eos issue.
