### ISSUE TITLE
Can i change the picture called image_0010.png int the data folder

### ISSUE THREAD

**Issue by Coding4mejie** [patrikhuber/eos#31]
Is the picture with .png is a common picture,and where can i get these pictures?Sorry for having so many questions.

**Comment by patrikhuber** [comment]
I'm not sure what you mean with common picture. It's a picture from the [ibug](http://ibug.doc.ic.ac.uk/resources/facial-point-annotations/) database but you can use any picture for the fitting, as long as you take care of the landmarks being in the correct format.

**Comment by Coding4mejie** [comment]
Thank you very much.I had found the ibug database,but I want to know the method of get 68 landmarks on any picture.Could you tell me?Thank you.

**Comment by patrikhuber** [comment]
If you want to do it automatically, you could use our [4dface](github.com/patrikhuber/4dface), which uses our [superviseddescent](github.com/patrikhuber/superviseddescent) landmark detection. You can use any other landmark detector too, or do it manually. See also #30 for a bit more details on the landmark format. And the code is quite well documented.

**Comment by Coding4mejie** [comment]
Thanks for your replying,so kind a man you are.I will see 4dface later and might use it.I hope you do not mind my poor English.My project is similar to virtual glasses fitting and makeup,are you familiar with the direction of this project?Sorry for have so many questions.

**Comment by patrikhuber** [comment]
I'm familiar with these applications, but I'm not really working on them by myself.
