### ISSUE TITLE
Compile errors with either toml or mpark-variant

### ISSUE THREAD

**Issue by towermalta** [patrikhuber/eos#310]
I refer to the eos model and want to run fit-moel.cpp in example. The settings I used are (windows10+visual studio 2017 15.9+opencv 3.2.0+boost 1.73.0),  but I encountered the following error at runtime.
ps. I also tried (visual studio 2019+opencv 3.2.0+boost 1.72.0), still got same problem:
![image](https://user-images.githubusercontent.com/29008487/83458297-dee6bc80-a494-11ea-912c-f3f38eb8a6ac.png)
The expression it said is:
![image](https://user-images.githubusercontent.com/29008487/83458369-050c5c80-a495-11ea-99a4-80221108b784.png)
I wonder if anyone got same problem when building this project and know the solution for it.

**Comment by patrikhuber** [comment]
Hi,

Perhaps you can try updating the [toml submodule](https://github.com/patrikhuber/eos/tree/master/3rdparty)? For mpark::variant, I directly copied the file from the [mpark repository](https://github.com/mpark/variant) to [here](https://github.com/patrikhuber/eos/blob/master/include/eos/cpp17/detail/mpark_variant.hpp), you can try updating the file with the latest version.

Also, if you compile eos in C++17 mode, you should not receive the `mpark::variant` errors, as the code should use `std::variant` instead!

Let us know how you get along.

**Comment by patrikhuber** [comment]
I should also mention that I am successfully using eos on VS 2019 16.6.0 and am not getting any toml errors. So it may only be a problem with `mpark::variant` (which an update might fix, as suggested). I am also not getting any errors with `CMAKE_CXX_STANDARD 17`, because, as mentioned, this will use `std::variant`.

**Comment by towermalta** [comment]
Hello, glad to have your reply, here is my update.
I changed my previous method and used vcpkg on visual studio 2019 to install the dependencies. then I get the build directory as follows:
![image](https://user-images.githubusercontent.com/29008487/83956157-9280ef80-a88d-11ea-8ed9-c0d21f1f2764.png)
I use visual studio to open eos.sln in this folder, compile it in C++17 mode and build INSTALL successfully. The following screenshot shows what it looks like in vs2019:
![image](https://user-images.githubusercontent.com/29008487/83956188-e68bd400-a88d-11ea-879f-23efebd5bdd2.png)
And I try to run the fit-model, but it gives error like:
![image](https://user-images.githubusercontent.com/29008487/83956204-04593900-a88e-11ea-8a34-cc0279bab9e5.png)
I wonder how to fix this problem, is it because I don't run INSTALL? but every tim"e I want to run INSTALL, it will say "access denied" like this:
![image](https://user-images.githubusercontent.com/29008487/83956235-48e4d480-a88e-11ea-8aea-aacca8e3606f.png)
And another thing, I don't find this install folder:
![image](https://user-images.githubusercontent.com/29008487/83956250-674ad000-a88e-11ea-9fa8-b802631325fb.png)
Looking forward to have your reply!

**Comment by patrikhuber** [comment]
Okay, it sounds like this indeed was a problem with your local build.

>> I don't run INSTALL? but every tim"e I want to run INSTALL, it will say "access denied" like this:

Probably you're trying to install to the default CMake INSTALL directory, which is along the lines of C:\Program Files\..., so you'll need admin rights. You can change that, see cmake-gui or the cmake documentation.

>> I don't find this install folder:

After you've run the INSTALL target, these files will be in your CMake INSTALL directory. Again, see the CMake documentation. The files are copied from `share/` and and `examples/data/`.

These are generic CMake and Visual Studio setup questions, if you need further help, then a place like [StackOverflow](https://stackoverflow.com/) is a more appropriate place to get help for such things.
