### ISSUE TITLE
out.obj files don't contain vn parameters

### ISSUE THREAD

**Issue by towermalta** [patrikhuber/eos#312]
Hello, I ran fit-model and got the out.obj file. I want to load the file in Android Studio, but it only contains v,vt,f parameter, not containing the vn parameter, which means no normal variables. I'm wondering if I'm running it wrong, or if there is no vn parameter in the obj file in your design?

**Comment by patrikhuber** [comment]
Hi,

You can generate the vertex normals easily by yourself - have a look at some standard computer graphics book / internet search.
