### ISSUE TITLE
Hi patrikhuber,I would like to know which version of dependencies you use in eos-master 

### ISSUE THREAD

**Issue by Jared-Dai** [patrikhuber/eos#313]
Hi patrikhuber,
I tried to compile the lastest version eos, but I meet some problems. These pictures show the problems, Could you plz tell me the version you use  and how to compile ,thank you very much!
 
![微信截图_20200617145452](https://user-images.githubusercontent.com/66655052/84865303-8e817880-b0aa-11ea-860e-13289ce5d952.png)

**Comment by patrikhuber** [comment]
Hi,

Apologies for the late reply, I missed the notification for this.

I think you are probably trying to compile without CMake, is that correct? If so, please use CMake. Your errors are linker errors, there stem from an invalid build configuration.

Are you still working on this?

I'll close this as it's not an eos issue, but feel free to report back with a follow-up question.
