### ISSUE TITLE
The question about the funtion(extract_texture) with android

### ISSUE THREAD

**Issue by yygbruce** [patrikhuber/eos#315]
Hi patrikhuber,
    When I use the lib with android, I have the following problems:

![out isomap](https://user-images.githubusercontent.com/18020338/85969956-b1415480-b9fb-11ea-89d7-1276546e9427.png)
   I have checked the rendering parameters, no problem.So I think It was caused by the function of extract_texture, and the question just append in android system.

**Comment by patrikhuber** [comment]
Hi,

Good question what could be going on here. It could have to do with the visibility/z-buffer, or perhaps an invalid memory access somewhere. The first thing I'd do is run a debug build, where asserts are enabled. I am thinking that it's likely one of the asserts in the code will fire. Second, you could try the `extract_texture(...)` from the `devel` branch (this was previously in the `render::v2` namespace) - this method will become the default in the near future.

**Comment by yygbruce** [comment]
> Hi,
> 
> Good question what could be going on here. It could have to do with the visibility/z-buffer, or perhaps an invalid memory access somewhere. The first thing I'd do is run a debug build, where asserts are enabled. I am thinking that it's likely one of the asserts in the code will fire. Second, you could try the `extract_texture(...)` from the `devel` branch (this was previously in the `render::v2` namespace) - this method will become the default in the near future.

Yes, It work.But another question append in PC and android.The backgroud color is not transparent：
![out isomap](https://user-images.githubusercontent.com/18020338/86085244-3e0a1200-bad1-11ea-8fc7-d9673e615b37.png)

**Comment by yygbruce** [comment]
> > Hi,
> > Good question what could be going on here. It could have to do with the visibility/z-buffer, or perhaps an invalid memory access somewhere. The first thing I'd do is run a debug build, where asserts are enabled. I am thinking that it's likely one of the asserts in the code will fire. Second, you could try the `extract_texture(...)` from the `devel` branch (this was previously in the `render::v2` namespace) - this method will become the default in the near future.
> 
> Yes, It work.But another question append in PC and android.The backgroud color is not transparent：
> ![out isomap](https://user-images.githubusercontent.com/18020338/86085244-3e0a1200-bad1-11ea-8fc7-d9673e615b37.png)

Thanks! I have solved this problem, after I changed the the file of Rasterizer.hpp(line 52):
colorbuffer = eos::core::image::constant(viewport_height, viewport_width,
                        eos::core::Pixel<std::uint8_t, 4>(0, 0, 0, 0));
In addition, I alse changed the file of opencv_interop.hpp(line 113),:
inline Image4u from_mat_with_alpha(const cv::Mat& image)
{
    Image4u converted(image.rows, image.cols);
    if (image.type() == CV_8UC3)
    {
        for (int r = 0; r < image.rows; ++r)
        {
            for (int c = 0; c < image.cols; ++c)
            {
                converted(r, c) = {image.at<cv::Vec3b>(r, c)[0], image.at<cv::Vec3b>(r, c)[1],
                                   image.at<cv::Vec3b>(r, c)[2], 255};
            }
        }
    }
    else if (image.type() == CV_8UC4)
    {
        for (int r = 0; r < image.rows; ++r)
        {
            for (int c = 0; c < image.cols; ++c)
            {
                converted(r, c) = {image.at<cv::Vec4b>(r, c)[0], image.at<cv::Vec4b>(r, c)[1],
                        image.at<cv::Vec4b>(r, c)[2], image.at<cv::Vec4b>(r, c)[3]};
            }
        }
    }
    else {
        throw std::runtime_error("Can only convert a CV_8UC4 cv::Mat to an eos::core::Image4u or eos::core::Image3u.");
    }
    return converted;
}

**Comment by patrikhuber** [comment]
Sounds good! I'm not sure whether this is/was really a problem with eos on Android, or something local to your system/setup. So I would close this from my side, if you are happy?

**Comment by yygbruce** [comment]
> Sounds good! I'm not sure whether this is/was really a problem with eos on Android, or something local to your system/setup. So I would close this from my side, if you are happy?

Of course!I look forward to your good news。
