### ISSUE TITLE
How to apply for the full Surrey Face Model

### ISSUE THREAD

**Issue by tianboguangding** [patrikhuber/eos#32]
Hi,
Thanks for your shared Model and the published software framework.
You writed that after signing licence agreement ,we can apply for the others model( for example :the full surrey face model ) in your paper. 
But i can not access to the website: http://cvssp.org/facemodel
How to apply for the others model?
Thanks very much.

**Comment by patrikhuber** [comment]
Hi,

Sorry about the page, it was offline out of my control. We fixed it now and it's back online. We're also in the process of making improvements to these pages.

If your inquiry is about _commercial_ use of the model or you would like the full model (shape and colour), please see the information on that page.

If you would like the full resolution _shape_ model, you can fill out [this form](http://www.cvssp.org/faceweb/3dmm/register/register.html) (it'll give an "Unable to store the request", but I'll get an email nonetheless!).

Patrik

**Comment by tianboguangding** [comment]
Thanks for your update！
I will follow your request to apply fot the model.

**Comment by patrikhuber** [comment]
Great!
