### ISSUE TITLE
I runned your project,How change mesh.. into a ply file?

### ISSUE THREAD

**Issue by leiBill** [patrikhuber/eos#320]
![image](https://user-images.githubusercontent.com/11794710/89245089-a56c3200-d63a-11ea-9726-8e75dbfb572b.png)
As you can see from above pcitures.....
How to change it to a .ply file  ?I want save the created face model in my local computer! 
Thank you!

**Comment by patrikhuber** [comment]
You can use `eos.core.write_obj(...)`. If you want a .ply, you can convert it using MeshLab or Blender, or better, use trimesh/pymesh to save the contents of `mesh` directly in the format that you want.

If you need further help, such questions are best posted on the StackExchange network, as these are not "issues" with eos.

**Comment by leiBill** [comment]
You  are really a nice man!
Thank you for your help very much.

**Comment by leiBill** [comment]
> You can use `eos.core.write_obj(...)`. If you want a .ply, you can convert it using MeshLab or Blender, or better, use trimesh/pymesh to save the contents of `mesh` directly in the format that you want.
> 
> If you need further help, such questions are best posted on the StackExchange network, as these are not "issues" with eos.
You are really a nice man!
Thank you for your help very much.
