### ISSUE TITLE
Could the input image be gray or NIR image? 

### ISSUE THREAD

**Issue by briantse100** [patrikhuber/eos#323]
Hi, @patrikhuber I have run the sample with RGB image. And the result is good. But the input is gray or NIR image, it is error. I have known the 3D face model is built on RGB image. So is it only suitable for RGB image. Or how to modify the code for the gray or NIR image. Thanks!

**Comment by patrikhuber** [comment]
Hi,

eos's main fitting (and the one that the `fit-model` example uses) is shape-to-landmarks fitting - no image information beyond the given facial landmarks are used. The landmark fitting works on whatever landmarks you give it. If you have NIR images, you probably want to use a landmark detector that's trained on NIR images.
If the accuracy of landmarks-only fitting is not suitable for you, then you may want to look into non-linear/analysis-by-synthesis fitting (see `fit-model-ceres` and lots of literature about 3D face model fitting out there). Indeed if you want to use a 3DMM colour model in that scenario and with NIR images, you may need to make some adjustments and/or ideally have a colour model learned in NIR-space. There's plenty of options, I would advise you to get more familiar with the topic and the literature.
