### ISSUE TITLE
how to transform a side face into a front face

### ISSUE THREAD

**Issue by spy78111** [patrikhuber/eos#327]
now ,I have a side face and I wish to transform it into a front face. how to do this by eos library ? thanks very much

**Comment by patrikhuber** [comment]
Hi, sorry for the late reply. I suspect this is no longer a current question, but in any case: You can use the eos renderer, and supply an identity model-view matrix, which will result in a frontal rendering. Alternatively you can save the obj and use any renderer you wish (e.g. Blender or something in Python).
