### ISSUE TITLE
How to get the landmarks of the 3D reference face model

### ISSUE THREAD

**Issue by liuyun199111** [patrikhuber/eos#33]
Hi,
Thank you very much for sharing your research.I try to use myself landmark predictor ,it can get 
a  .pts file of  the 2D image  landmark,due to it outputs different points, i don't know how to map my landmark point onto 3D reference face model, and how to get the coordinate of 3D reference face modle.

**Comment by patrikhuber** [comment]
Just have a look at how the current system works, for example step through the `fit-model` app. Most if not all you need to change is [share/ibug2did.txt](https://github.com/patrikhuber/eos/blob/master/share/ibug2did.txt).

**Comment by liuyun199111** [comment]
I know I should change the share/ibug2did.txt,but my own  landmarks are different from you ,in the ibug2did.txt , write the landmark name on the left side ,but on  the right side ,I don't know the corresponding 3D vertex ID .How can I get the 3D vertex ID corresponding to my own landmarks?

**Comment by patrikhuber** [comment]
Look for the vertex id's on the [reference](https://github.com/patrikhuber/eos/blob/master/share/reference.obj). Open the obj in Blender, MeshLab, or a similar tool. It's actually all quite well documented in the readme [here](https://github.com/patrikhuber/eos/tree/master/share) and in the `ibug2did.txt` file itself.

**Comment by liuyun199111** [comment]
I open the reference.obj in Blender, It has  presented a 3D face model，but I still can't get the  vertex ID,can you tell me the specific method to get the ID?Thank you very much.

**Comment by patrikhuber** [comment]
I don't know Blender that well but a quick Google search should reveal it to you. In MeshLab, it's either the "Get Info" button or "Render => Show Label".
