### ISSUE TITLE
blendshape_coeffs for BFM2017

### ISSUE THREAD

**Issue by Ar4enal** [patrikhuber/eos#336]
Hi, first of all thanks for your great work. I have a question for the blendshape_coeffs of BFM2017 model.

I want to use BFM2017 instead of sfm model because I heard that BFM2017 has more expressions compared with sfm model (6 expressions).

I use these files you provide and print the blendshape_coeffs in python.
[https://github.com/patrikhuber/eos/wiki#bfm2017](url)

![捕获](https://user-images.githubusercontent.com/36718239/134279046-03b18222-a037-430a-a1bd-66a342c8afdc.JPG)

I can get 100 blendshape_coeffs but I just do not understand what they mean, like  [anger, disgust, fear, happiness, sadness, surprise] in sfm model that you use in python demo.

Do you know the meaning of the blendshape_coeffs for BFM2017? Looking forward to your reply.

**Comment by Neo1024** [comment]
> Hi, first of all thanks for your great work. I have a question for the blendshape_coeffs of BFM2017 model.
> 
> I want to use BFM2017 instead of sfm model because I heard that BFM2017 has more expressions compared with sfm model (6 expressions).
> 
> I use these files you provide and print the blendshape_coeffs in python. [https://github.com/patrikhuber/eos/wiki#bfm2017](url)
> 
> ![捕获](https://user-images.githubusercontent.com/36718239/134279046-03b18222-a037-430a-a1bd-66a342c8afdc.JPG)
> 
> I can get 100 blendshape_coeffs but I just do not understand what they mean, like [anger, disgust, fear, happiness, sadness, surprise] in sfm model that you use in python demo.
> 
> Do you know the meaning of the blendshape_coeffs for BFM2017? Looking forward to your reply.

Hi, I am also trying to use BFM17 model in my project. I got stucked at generating edge_topology json file for BFM17 as I don't have a lisenced Matlab installed. Is it possible that somehow you share the json file?

**Comment by Neo1024** [comment]
> > Hi, first of all thanks for your great work. I have a question for the blendshape_coeffs of BFM2017 model.
> > I want to use BFM2017 instead of sfm model because I heard that BFM2017 has more expressions compared with sfm model (6 expressions).
> > I use these files you provide and print the blendshape_coeffs in python. [https://github.com/patrikhuber/eos/wiki#bfm2017](url)
> > ![捕获](https://user-images.githubusercontent.com/36718239/134279046-03b18222-a037-430a-a1bd-66a342c8afdc.JPG)
> > I can get 100 blendshape_coeffs but I just do not understand what they mean, like [anger, disgust, fear, happiness, sadness, surprise] in sfm model that you use in python demo.
> > Do you know the meaning of the blendshape_coeffs for BFM2017? Looking forward to your reply.
> 
> Hi, I am also trying to use BFM17 model in my project. I got stucked at generating edge_topology json file for BFM17 as I don't have a lisenced Matlab installed. Is it possible that somehow you share the json file?

Never mind :) I found one python script for the generation of edge topology from the pull request.
