### ISSUE TITLE
Windows

### ISSUE THREAD

**Issue by MAHMOUDRR707** [patrikhuber/eos#337]
has it been tested on Windows or only on linux

**Comment by patrikhuber** [comment]
Hi Mahmoud,

Yes eos is fully working on Windows. Sorry that the CI is currently not working, I need to find some time to update it.
You'll need a somewhat-recent VS version, I'm using VS2022, but 2019 works too. I'm not sure anymore about 2017, as it is getting quite outdated. Certainly VS2017 won't be supported anymore going forward.
