### ISSUE TITLE
Builid

### ISSUE THREAD

**Issue by MAHMOUDRR707** [patrikhuber/eos#338]
thanks for your great efforts but Is there any  video or tutorial instead of Readme to show how to build and run the library I catch an error 
Could NOT find Boost (missing: Boost_INCLUDE_DIR system filesystem
  program_options) (Required is at least version "1.50.0")

**Comment by patrikhuber** [comment]
The error means exactly what it says. If you are trying to compile the examples, they require Boost. As the Readme recommends, I would advise using vcpkg. If you need help using vcpkg, they have a great Readme/documentation too.
Unless you want to use the Python bindings, using the eos C++ library requires a slight bit of knowledge about C++ and building systems. You will probably need to invest a bit of time into learning.
