### ISSUE TITLE
compile problem

### ISSUE THREAD

**Issue by manman25** [patrikhuber/eos#339]
Hello!
      I tried to compile the eos with the latest version, but it seems can not compile successfully as shown in the following figures.
      
![image](https://user-images.githubusercontent.com/20472753/166865659-418217c7-8451-4439-af38-c2e639213ab8.png)

![image](https://user-images.githubusercontent.com/20472753/166865739-1aec1a2a-de96-44e8-999e-31a8e9d04706.png)

   The boost version is 1.75. should I replace another version for boost, or this kind of problem also proposed by other users?
   I hope you can tell me the solution in more details！

**Comment by manman25** [comment]
Dear patrikhuber! i have fixed this bug, thanks!

**Comment by patrikhuber** [comment]
Glad you fixed it. I was going to say that this looks like some issue with your local setup (what you're seeing are linker errors).
