### ISSUE TITLE
Texture is completely black

### ISSUE THREAD

**Issue by nebososo** [patrikhuber/eos#34]
When i run the example I get all 3 files. out.isomap.png looks just fine if I open it with an image viewer, however when I load the obj file with meshlab or blender, the texture is completely black, even though the logs report successfully loading the texture. I couldn't get github to attach the files, so I uploaded them here: www.nebososo.com/out.zip

**Comment by patrikhuber** [comment]
My MeshLab shows them just fine. I've seen this before, this is an issue with your Linux and possibly OpenGL and/or the graphics driver. It has nothing to do with this software at all.

**Comment by nebososo** [comment]
I'm leaving this for future reference. This issue happens on Linux using the proprietary NVIDIA drivers (I was using version 364.19 on all three machines I had this issue), a similar system with an Intel GPU rendered everything just fine. I did not try nouveau or software rendering. A quick workaround is calling render::extract_texture with compute_view_angle = false.

**Comment by patrikhuber** [comment]
Thanks for reporting back on this, I'm sure it will be useful to somebody in the future. That's really odd behaviour of the nvidia driver.

Kind of funny that it works with `compute_view_angle = false` but I guess that means it has something to do with the OpenGL rendering of RGBA texture in the nvidia driver... cool that you found out!
