### ISSUE TITLE
BFM09 texture coordinates (from stn/BFM_UV.mat) are flipped?

### ISSUE THREAD

**Issue by lvZic** [patrikhuber/eos#340]
I use texture_coordinates from stn/BFM_UV.mat and texture_triangle_indices from" bfm2009_raw['tl'] - 1". However, the  obj result of fitting-model-simple is unexpected as following:
![image](https://user-images.githubusercontent.com/7788572/167980830-54c5d247-9567-4dde-a260-524ea57415b7.png)

following is part of converting model code:

# Construct and save the BFM2009 model in the eos format:
model = eos.morphablemodel.MorphableModel(shape_model, color_model, vertex_definitions=None,
                                          texture_coordinates= uv_coords_raw,
                                          texture_triangle_indices = triangle_list.tolist())  # uv-coordinates can be added here

**Comment by lvZic** [comment]
The fitting-model-simple donot change except input parameters, so there must be something wrong about the converting bfm model. I checked the uv_coords_raw, size is 53490 x 2, range [0 1], and it seems fine. And the  triangle_list = bfm2009_raw['tl'] - 1, which from your code. 
I am confused about the problem and wonder why. Because I found these are so many issues about bfm model, however none of them given a solution. So I wonder whether the bfm could reconstruct successfully or jsut sfm can do using eos?

**Comment by lvZic** [comment]
I used bfm_model_2017, and the reconstructed obj seems same with the one by model 09. So what i missed?

**Comment by lvZic** [comment]
![out texture](https://user-images.githubusercontent.com/7788572/168071896-6291a227-080f-4bf1-9062-1e84330dd9f0.png)
The above result with flipped UV_texture's v coordinate, and I wonder why this happen?

**Comment by patrikhuber** [comment]
Hi @lvZic,

>> So I wonder whether the bfm could reconstruct successfully or jsut sfm can do using eos?

eos works fine with the BFM. But since the BFM doesn't come with official texture coordinates (the older versions at least), I suspect that not a lot of people (including me) have used uv texturing with that model.

Yes, the flipping can happen - I think some people define UV coords with the origin at the top-left, others define the origin at the bottom-left. As you've figured out, you can just flip the y-component of the uv coords (i.e. `new_y = 1 - old_y`) to adjust this.

Also it looks like when you're displaying your result in MeshLab, you're actually overlaying the vertex colouring (probably the mean face in this case) with the texturing. If you just want to visualise the texturing in MeshLab, you have to fiddle around with the checkboxes a bit.

I think this can probably be closed?

**Comment by lvZic** [comment]
> Hi @lvZic,
> 
> > > So I wonder whether the bfm could reconstruct successfully or jsut sfm can do using eos?
> 
> eos works fine with the BFM. But since the BFM doesn't come with official texture coordinates (the older versions at least), I suspect that not a lot of people (including me) have used uv texturing with that model.
> 
> Yes, the flipping can happen - I think some people define UV coords with the origin at the top-left, others define the origin at the bottom-left. As you've figured out, you can just flip the y-component of the uv coords (i.e. `new_y = 1 - old_y`) to adjust this.
> 
> Also it looks like when you're displaying your result in MeshLab, you're actually overlaying the vertex colouring (probably the mean face in this case) with the texturing. If you just want to visualise the texturing in MeshLab, you have to fiddle around with the checkboxes a bit.
> 
> I think this can probably be closed?

thanks for your reply, and i want to use eos to ectract identity and expression coef. the problem about flipped y-component of the uv coords is fixed.
Now I used deep3d's uvmat(https://github.com/microsoft/Deep3DFaceReconstruction/blob/master/utils.py), but i am focusing on another problem, which i wonder why.
![test texture](https://user-images.githubusercontent.com/7788572/168429239-6d4dc70d-48f0-4f10-ba50-0e4dbbb08809.png)
the above texture_result is weird and both bfm09 and bfm17 model generated the same result. I have checked the basisi,mean,eigen coef of shape,color and expression coef, and found no mistake. Can u give me advice which i can missed?

**Comment by patrikhuber** [comment]
Do you have an example (maybe from their repository) of how Deep3D's UV mapping is supposed to look like?

I would double-check whether Deep3D's UV mapping uses a different triangulation for the texture triangles, in which case you need to set `tti` (texture triangle indices) correctly.

How does it look like when you visualise the resulting model in MeshLab with this texture?

**Comment by lvZic** [comment]
As the  Deep3D's UV coordinate are selected from origin BFm 2009(53490) UV mat, so I normlize it with range [0, 1} as following:
	uv_coords =  uv_coords_raw[index_shape, :]
	uv_coords = np.reshape(uv_coords, [-1, 2])
	#normlize
	uv_coords[:,0] = (uv_coords[:,0] - (uv_coords[:,0]).min() ) / ((uv_coords[:,0]).max() -  (uv_coords[:,0]).min() )
	uv_coords[:,1] = (uv_coords[:,1] - (uv_coords[:,1]).min() )/ ((uv_coords[:,1]).max()- (uv_coords[:,1]).min() )

![image](https://user-images.githubusercontent.com/7788572/168510122-6fc0bac4-dfcb-44bd-b5a6-6a8d1cbf55f2.png)
above is  the resulting model in MeshLab.

And i remember bfm 2017 model has generated result once (https://github.com/patrikhuber/eos/issues/340#issuecomment-1124918800), however now both 2009 and 2017 failed to produce normal result. During this period, the fitted-model-simple code has nothing changed.

Also, nothing new happened with or without "for t in triangle_list:  t[1], t[2] = t[2], t[1]".

**Comment by lvZic** [comment]
@patrikhuber  the resion of above result is about cmake compile option, when the relwithdebinfo mode is set the result is weird as above, and debug or release mode works fine.
And then i found the different units problem about bfm2009 model and fixed it by https://github.com/patrikhuber/eos/issues/255.
However, the result now is still abnormal as following:
![test_bfm09_front texture](https://user-images.githubusercontent.com/7788572/168590847-1399520d-ff2a-4389-8623-da3ca0f34700.png)
the result in meshlab is :+1: 
![image](https://user-images.githubusercontent.com/7788572/168591001-531a6098-a7b1-4b59-8f0a-adcfe26ba3b4.png)

**Comment by lvZic** [comment]
following is tri from DEEP3D:
![image](https://user-images.githubusercontent.com/7788572/168594296-57e83ccc-a1c6-48b1-ba2a-e11460b0b679.png)
![image](https://user-images.githubusercontent.com/7788572/168594347-1ceb9016-3bd9-4bc2-9ae2-5d5d90db31b5.png)

following is UV mapping of DEEP3D:
![image](https://user-images.githubusercontent.com/7788572/168594547-316cd2bb-3854-4940-9ded-e59c8685ff1f.png)
![image](https://user-images.githubusercontent.com/7788572/168594593-efca9de6-d2b2-41c9-a272-8f97d0a9c0ac.png)

**Comment by lvZic** [comment]
I found the origin BFM09 model (53490 vertex) without expression can generate following result, however the color and shape position don't match correctly.
![image](https://user-images.githubusercontent.com/7788572/168720585-6ed20e5b-520f-4637-a27b-f7193ccd56be.png)
So the must be something wrong with BFM09_front.model(https://github.com/microsoft/Deep3DFaceReconstruction/blob/master/utils.py).

**Comment by lvZic** [comment]
@patrikhuber  Now, i run fit-model with bfm09_frontface_model(35709 vertex), and get following result:
![bfm2009_front texture](https://user-images.githubusercontent.com/7788572/168807796-e084d812-a00c-4569-99f0-c87227ffaca8.png)
![bfm2009_front](https://user-images.githubusercontent.com/7788572/168807821-4b298fcc-f169-4f1f-8bd5-3994c789b5f4.png)
![image](https://user-images.githubusercontent.com/7788572/168807946-4e708f45-89da-4cb8-8773-70c2b333bead.png)

Can u give me advise about where i missed?

**Comment by lvZic** [comment]
@patrikhuber  after re-recheck the  contour json file, i  recreate it using keypoint info from facemodel_info.mat in deep3d, then result is normal as following:
![image](https://user-images.githubusercontent.com/7788572/169242159-bed79550-ab5e-4793-9215-9184bcfa7d6d.png)
The difference is the older  contour json file is created by replaceing bfm2009_model_contours by corresponding vertex index bewteen front_face model and origin bfm09 model，and the new one is created by using keypoint info from facemodel_info.mat which contain 68 landmarks' vertex index. In my opinon, these two should be same....

Anyway, the latest result is normal except for mismatch between color and shape. Can u give me advice about what i missed? thanks a lot!

**Comment by patrikhuber** [comment]
`model_contours.json` should contain the vertex ids for the right and left vertices that correspond to the "2D" (ibug) landmarks. If you want to use the contour fitting, it may help you to read the relevant sub-chapters in my [thesis](https://openresearch.surrey.ac.uk/esploro/outputs/doctoral/Real-time-3D-morphable-shape-model-fitting/99512548502346) that explain the contour fitting in eos? And it doesn't hurt to have a bit of a look at the code to get a broad understanding of how both the front- and back-facing contour fitting work, so you can define the contour vertices correctly. Also if you don't need it, you can disable the contour fitting too - for example `fit-model-simple` runs without the contour fitting.

As for the "mismatch" you're seeing, first, you're still overlaying vertex colouring and texturing in MeshLab, see my comment further above. Second, the "mismatch" comes from inaccurate fitting and it is expected to some degree. Remind yourself that you are only fitting to 68 (or slightly less) **landmarks**. `fit-model` does not do any dense fitting. If you want more accurate results, you can use more landmarks, or you can use eos's result to initialise a more dense fitting approach. Since you're using a different model, you can also play around with the shape regularisation a bit, you need to find a good value for your particular model where your fitting results can deviate from the mean enough, but not too much to generate unrealistic faces.

**Comment by lvZic** [comment]
> `model_contours.json` should contain the vertex ids for the right and left vertices that correspond to the "2D" (ibug) landmarks. If you want to use the contour fitting, it may help you to read the relevant sub-chapters in my [thesis](https://openresearch.surrey.ac.uk/esploro/outputs/doctoral/Real-time-3D-morphable-shape-model-fitting/99512548502346) that explain the contour fitting in eos? And it doesn't hurt to have a bit of a look at the code to get a broad understanding of how both the front- and back-facing contour fitting work, so you can define the contour vertices correctly. Also if you don't need it, you can disable the contour fitting too - for example `fit-model-simple` runs without the contour fitting.
> 
> As for the "mismatch" you're seeing, first, you're still overlaying vertex colouring and texturing in MeshLab, see my comment further above. Second, the "mismatch" comes from inaccurate fitting and it is expected to some degree. Remind yourself that you are only fitting to 68 (or slightly less) **landmarks**. `fit-model` does not do any dense fitting. If you want more accurate results, you can use more landmarks, or you can use eos's result to initialise a more dense fitting approach. Since you're using a different model, you can also play around with the shape regularisation a bit, you need to find a good value for your particular model where your fitting results can deviate from the mean enough, but not too much to generate unrealistic faces.

thanks for your help. and i will close this issue.
