### ISSUE TITLE
Adding custom 3dmm 

### ISSUE THREAD

**Issue by leg0m4n** [patrikhuber/eos#346]
Thank you so much for your work! Amazing library, has been really helpful with my project.

I was wondering how possible is it to add custom 3dmm? For example, ICT-FaceKit(https://github.com/ICT-VGL/ICT-FaceKit), they have a very detailed model with lots of blendshapes. How would you approach such problem?

Thanks!

**Comment by patrikhuber** [comment]
Hi @leg0m4n,

Thank you very much for all your kind praise! I'm very glad to hear that my work has been so helpful for you.

Yes, it is quite easy to add a custom 3DMM to eos, especially if it's PCA-based. Have a look at the convert/loader scripts in the [eos/share/scripts](https://github.com/patrikhuber/eos/tree/master/share/scripts) directory for the BFM2009/2017 and the LYHM. It should be quite easy to write a short Python script that does the same for the ICT-FaceKit model: Load it in Python and then create an `eos.morphablemodel.PcaModel` and `eos.morphablemodel.MorphableModel` instance with the right data (mean, eigenvectors, eigenvalues, triangle list, etc.).

I'd be curious to hear how you get along!

**Comment by leg0m4n** [comment]
Thank you!

**Comment by AlKhwarizmiCoder** [comment]
Hi @leg0m4n , I am working on the same issue and was wondering, if you have make it work?
