### ISSUE TITLE
Request for Protobuf Version Requirement in CMakeLists.txt

### ISSUE THREAD

**Issue by tesmachina** [patrikhuber/eos#359]
I encountered an issue while trying to build a project using CMake and Vcpkg. The CMakeLists.txt file of the project in question uses find_package to locate Protobuf without specifying a version. This has caused issues when trying to configure the project, as it fails to find a compatible version of Protobuf.

My current Protobuf version is 3.21.12, and I would like to ensure compatibility. Could you please specify the required version of Protobuf for this project in the CMakeLists.txt file or provide guidance on the appropriate version to use? This would greatly help users who are trying to build the project using Vcpkg or other package managers.

Thank you for your assistance in resolving this matter.

**Comment by patrikhuber** [comment]
Hi @tesmachina,

Hmm, eos does not depend on protobuf. So this must come in from somewhere as a transitive dependency? I think OpenCV has an optional dependency on protobuf. Can you find out if it's that? And if so, you should be able to install eos with just `opencv4[core,jpeg,png]` and without protobuf. In fact, if you use eos's vcpkg.json, it specifies that only opencv4's jpeg and png features are needed, and not protobuf (https://github.com/patrikhuber/eos/blob/8196a74659ac0987259bbd54d2960e19bed28e49/vcpkg.json#L9-L11).

**Comment by patrikhuber** [comment]
Great! I'll close this then.
