### ISSUE TITLE
The mapping of outside-contour‘s landmarks and 3D model's vertex index

### ISSUE THREAD

**Issue by tianboguangding** [patrikhuber/eos#36]
Hi，Patrickhuber：

Thanks for your shared model.
 There is a problem when  using  anybody's 3D face(which is generated by your eos projects ) to fit a head frame model ( the size of the head frame is stable) .
The size of every people ’s face is different，so I think that I have to stretching the outside contour of the face for fitting the head frame model. But there are no mapping data between outside-contour landmarks and 3D model's vertex indexs in your ibug2did.txt.

 Could you provide the mapping data of this part(1 to 8;10 to 17)? 
Or could you tell me how to solve this problem if don't use the mapping data of outside contour? 
Thanks very much!

**Comment by tianboguangding** [comment]
#

**Comment by patrikhuber** [comment]
Hi,

There is no 1:1 correspondence between these 2D contour landmarks and the 3D model, it depends on the pose. Have a look at our [paper](https://arxiv.org/abs/1605.06764) section II.E, and reference [11] for a more complete overview.

For the simple implementation in our paper, we provide the contour indices in [share/model_contours.json](https://github.com/patrikhuber/eos/blob/master/share/model_contours.json). However you can use whatever solution you like.
