### ISSUE TITLE
Get 2D image from morphable model

### ISSUE THREAD

**Issue by ejulio** [patrikhuber/eos#37]
Hey :)
I'm trying to get a 2D frontal image using the model. I tried using `render::render` and `render::render_affine` but the outputs aren't as expected (they return color and depth images without texture- attached).
Is there a way to get a 2D frontal image with texture? :D
![render1](https://cloud.githubusercontent.com/assets/1322222/16173565/5584c662-357b-11e6-8599-b61497eaf0cf.png)
![render2](https://cloud.githubusercontent.com/assets/1322222/16173564/5581ed34-357b-11e6-87da-25466a31f7f2.png)

**Comment by patrikhuber** [comment]
Hi!

Sure, that's quite easy. [fit-model](https://github.com/patrikhuber/eos/blob/master/examples/fit-model.cpp#L208) already writes out an obj with texture (through `render::write_textured_obj`). You can then just use for example MeshLab to very comfortably view the mesh, including texture.

Furthermore, `render::render` has an optional parameter where you can specify a texture, and it'll then render with texture. See [here](https://github.com/patrikhuber/4dface/blob/master/apps/4dface.cpp#L243) for an example.

**Comment by ejulio** [comment]
Thanks :)
