### ISSUE TITLE
Do I use the model to fit the point cloud?

### ISSUE THREAD

**Issue by XiaXuehai** [patrikhuber/eos#38]
Do I use the  morphable model to fit the point cloud of face which got for stereo camera?

**Comment by patrikhuber** [comment]
You can certainly use our 3D Morphable Model to fit it to a point cloud. That's kind of similar to what we do in the registration stage. It's not eos's use case though, so you'd need another software and use it together with our model.

**Comment by XiaXuehai** [comment]
THX
