### ISSUE TITLE
EOS Build error

### ISSUE THREAD

**Issue by DaveNW16HD** [patrikhuber/eos#39]
Hi

I'm trying to build and install EOS on my ubuntu 14.04. I think all the dependencies are there  but when I do make install, i get the following errors about OpenCV not found: Any ideas ?

`Scanning dependencies of target fit-model
[ 50%] Building CXX object examples/CMakeFiles/fit-model.dir/fit-model.cpp.o
Linking CXX executable fit-model
CMakeFiles/fit-model.dir/fit-model.cpp.o: In function `eos::render::draw_texcoords(eos::render::Mesh, cv::Mat)':
fit-model.cpp:(.text+0x2276): undefined reference to `cv::line(cv::_InputOutputArray const&, cv::Point_<int>, cv::Point_<int>, cv::Scalar_<double> const&, int, int, int)'
fit-model.cpp:(.text+0x24ca): undefined reference to `cv::line(cv::_InputOutputArray const&, cv::Point_<int>, cv::Point_<int>, cv::Scalar_<double> const&, int, int, int)'
fit-model.cpp:(.text+0x271e): undefined reference to `cv::line(cv::_InputOutputArray const&, cv::Point_<int>, cv::Point_<int>, cv::Scalar_<double> const&, int, int, int)'
CMakeFiles/fit-model.dir/fit-model.cpp.o: In function `main':
fit-model.cpp:(.text+0x8c3f): undefined reference to `cv::imread(cv::String const&, int)'
fit-model.cpp:(.text+0x8ffe): undefined reference to `cv::rectangle(cv::_InputOutputArray const&, cv::Point_<int>, cv::Point_<int>, cv::Scalar_<double> const&, int, int, int)'
fit-model.cpp:(.text+0x96d9): undefined reference to `cv::imwrite(cv::String const&, cv::_InputArray const&, std::vector<int, std::allocator<int> > const&)'
CMakeFiles/fit-model.dir/fit-model.cpp.o: In function `cv::String::String(char const*)':
fit-model.cpp:(.text._ZN2cv6StringC2EPKc[_ZN2cv6StringC5EPKc]+0x4f): undefined reference to `cv::String::allocate(unsigned long)'
CMakeFiles/fit-model.dir/fit-model.cpp.o: In function `cv::String::~String()':
fit-model.cpp:(.text._ZN2cv6StringD2Ev[_ZN2cv6StringD5Ev]+0x14): undefined reference to `cv::String::deallocate()'
CMakeFiles/fit-model.dir/fit-model.cpp.o: In function `cv::Mat::Mat(int, int, int, void*, unsigned long)':
fit-model.cpp:(.text._ZN2cv3MatC2EiiiPvm[_ZN2cv3MatC5EiiiPvm]+0x121): undefined reference to `cv::error(int, cv::String const&, char const*, char const*, int)'
fit-model.cpp:(.text._ZN2cv3MatC2EiiiPvm[_ZN2cv3MatC5EiiiPvm]+0x228): undefined reference to `cv::error(int, cv::String const&, char const*, char const*, int)'
CMakeFiles/fit-model.dir/fit-model.cpp.o: In function `cv::String::String(std::string const&)':
fit-model.cpp:(.text._ZN2cv6StringC2ERKSs[_ZN2cv6StringC5ERKSs]+0x69): undefined reference to `cv::String::allocate(unsigned long)'
CMakeFiles/fit-model.dir/fit-model.cpp.o: In function `_ZNK2cv3MatcvNS_3VecIT_XT0_EEEIfLi4EEEv':
fit-model.cpp:(.text._ZNK2cv3MatcvNS_3VecIT_XT0_EEEIfLi4EEEv[_ZNK2cv3MatcvNS_3VecIT_XT0_EEEIfLi4EEEv]+0xc4): undefined reference to `cv::error(int, cv::String const&, char const*, char const*, int)'
CMakeFiles/fit-model.dir/fit-model.cpp.o: In function `_ZNK2cv3MatcvNS_3VecIT_XT0_EEEIfLi3EEEv':
fit-model.cpp:(.text._ZNK2cv3MatcvNS_3VecIT_XT0_EEEIfLi3EEEv[_ZNK2cv3MatcvNS_3VecIT_XT0_EEEIfLi3EEEv]+0xc4): undefined reference to `cv::error(int, cv::String const&, char const*, char const*, int)'
CMakeFiles/fit-model.dir/fit-model.cpp.o: In function `_ZNK2cv3MatcvNS_3VecIT_XT0_EEEIfLi2EEEv':
fit-model.cpp:(.text._ZNK2cv3MatcvNS_3VecIT_XT0_EEEIfLi2EEEv[_ZNK2cv3MatcvNS_3VecIT_XT0_EEEIfLi2EEEv]+0xc4): undefined reference to `cv::error(int, cv::String const&, char const*, char const*, int)'
collect2: error: ld returned 1 exit status
make[2]: *** [examples/fit-model] Error 1
make[1]: *** [examples/CMakeFiles/fit-model.dir/all] Error 2
`

The build info is listed below:

`-- The C compiler identification is GNU 4.9.3
-- The CXX compiler identification is GNU 4.9.3
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Performing Test HAS_CXX14_FLAG
-- Performing Test HAS_CXX14_FLAG - Success
-- Options:
-- BUILD_EXAMPLES: ON
-- BUILD_DOCUMENTATION: OFF
-- OpenCV include dir found at /usr/include/opencv;/usr/include
-- OpenCV lib dir found at 
-- Boost version: 1.54.0
-- Found the following Boost libraries:
--   system
-- Boost found at /usr/include
-- Found Eigen3: /usr/include/eigen3 (Required is at least version "2.91.0") 
-- Eigen3 found: TRUE
-- Eigen3 include dir found at /usr/include/eigen3
-- Eigen3 version: 3.2.0
-- OpenCV 2.x detected
-- OpenCV include dir found at /usr/include/opencv;/usr/include
-- OpenCV lib dir found at 
-- Boost version: 1.54.0
-- Found the following Boost libraries:
--   system
--   filesystem
--   program_options
-- Boost found at /usr/include
-- Configuring done
-- Generating done
`

**Comment by patrikhuber** [comment]
Hi!

It looks to me that OpenCV was not successfully found actually:

```
-- OpenCV include dir found at /usr/include/opencv;/usr/include
-- OpenCV lib dir found at
-- 
```
So it found the headers, but not the libraries (.so/.a files on Linux). This explains your `undefined reference` errors.

Can you check whether you've installed something like opencv-dev and/or opencv-core-dev etc. packages? If yes, for some reason CMake has trouble finding it - it shouldn't. We're just using `find_package(OpenCV 2.4.3 REQUIRED)` in this project, no custom magic going on.
