### ISSUE TITLE
Black line in isomap extraction

### ISSUE THREAD

**Issue by patrikhuber** [patrikhuber/eos#4]
When using the low-resolution model and extracting the isomap, there's a black line in the middle of the face. Investigate and fix it.

Maybe a glitch in the texture coordinates or a rounding issue in the conversion from the CVSSP file.

**Comment by ming81** [comment]
How can i solve this problem?

**Comment by patrikhuber** [comment]
At the moment, if you're bothered by it, a solution is to use the full resolution model. It works fine there.
I'll have a look at the problem eventually though.

**Comment by ming81** [comment]
I do not know? Can't  you provide an example? thank you!!

**Comment by patrikhuber** [comment]
I'm not sure I understand your question. Do you want to know how the bug actually looks like?

**Comment by ming81** [comment]
![3](https://cloud.githubusercontent.com/assets/6691460/10091536/3e2b61f8-636f-11e5-9979-bf9527ab38f4.png)
How can i solve this problem? Can't you provide an example?

**Comment by ming81** [comment]
![4](https://cloud.githubusercontent.com/assets/6691460/10091557/99a915de-636f-11e5-9ec5-cc6a5a228bba.png)
Please See Red Rect!!

**Comment by ming81** [comment]
![4](https://cloud.githubusercontent.com/assets/6691460/10091565/ac31b94a-636f-11e5-9612-d079644fdcfe.png)
Please See Red Rect!

**Comment by ming81** [comment]
The Model is make from faceGen 
![5](https://cloud.githubusercontent.com/assets/6691460/10091631/8d1a3b1c-6370-11e5-891c-cdd5f9a68b2a.png)
!

**Comment by ming81** [comment]
![101](https://cloud.githubusercontent.com/assets/6691460/10091861/e0272d68-6372-11e5-8735-21c8dbd23a01.jpg)

**Comment by patrikhuber** [comment]
Sorry for the late reply - I was at a conference. So, the "problem" you're experiencing is actually not the bug I'm describing in this issue.

When you map the texture from a frontal face to a 3D model, there is going to be some vertices in the 3D model that are not visible - exactly the ones in your red square. Think about it for a moment: These vertices in your red box are at the side of the nose, at >=90° from the frontal view. They're not visible from the model's point of view.

You could merge the texture from different viewpoints, as FaceGen does - in the side-view, these vertices are visible. This feature will also be included in the next release.

If you have any further questions, please open a new issue, as this is not related to the bug posted here. Thanks!

**Comment by hrdkjain** [comment]
We can also use a simple hole filling algorithm, which uses average value of neighbouring pixels. This had served my purpose

**Comment by patrikhuber** [comment]
@hrdkjain Right, that's actually a quick and nice solution :-D Nevertheless, I hope to find the time to get to the bottom of why it is happening in the first place at some point!

**Comment by patrikhuber** [comment]
I implemented the workaround mentioned by @hrdkjain (thanks!) in 0698a88. Nevertheless, I hope to be able to get to the bottom of why it's happening in the first place some time, so I'll leave this issue open.

**Comment by patrikhuber** [comment]
I think this is now finally fixed with 6875e08, thus, I commented the fix. There may still be some "black lines" but that's actually because there are just no uv coordinates that map there, and the alpha channel is set correctly there, so it can easily be masked.

Thanks @PhilippKopp!
