### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by hillday** [patrikhuber/eos#41]
Scanning dependencies of target fit-model
[ 50%] Building CXX object examples/CMakeFiles/fit-model.dir/fit-model.cpp.o
Linking CXX executable fit-model
CMakeFiles/fit-model.dir/fit-model.cpp.o: In function `main':
fit-model.cpp:(.text+0x8319): undefined reference to `boost::program_options::options_description::options_description(std::string const&, unsigned int, unsigned int)'
fit-model.cpp:(.text+0x9105): undefined reference to `boost::filesystem::path::replace_extension(boost::filesystem::path const&)'
fit-model.cpp:(.text+0x918c): undefined reference to `boost::filesystem::path::stem() const'
fit-model.cpp:(.text+0x919f): undefined reference to `boost::filesystem::path::stem() const'
CMakeFiles/fit-model.dir/fit-model.cpp.o: In function `__static_initialization_and_destruction_0(int, int)':
fit-model.cpp:(.text+0xa8a5): undefined reference to `boost::system::generic_category()'
fit-model.cpp:(.text+0xa8b1): undefined reference to `boost::system::generic_category()'
fit-model.cpp:(.text+0xa8bd): undefined reference to `boost::system::system_category()'

make is error,why?

**Comment by patrikhuber** [comment]
Looks like boost wasn't found correctly, thus you get linker errors. Please
analyse the output of cmake.

**Comment by hillday** [comment]
compilation terminated.
[root@cloud2 bulid]# cmake ../eos -DCMAKE_INSTALL_PREFIX=../install/
-- The C compiler identification is GNU 4.9.3
-- The CXX compiler identification is GNU 4.9.3
-- Check for working C compiler: /usr/local/bin/gcc
-- Check for working C compiler: /usr/local/bin/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/local/bin/c++
-- Check for working CXX compiler: /usr/local/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Performing Test HAS_CXX14_FLAG
-- Performing Test HAS_CXX14_FLAG - Success
-- Options:
-- BUILD_EXAMPLES: ON
-- BUILD_DOCUMENTATION: OFF
-- OpenCV include dir found at /usr/local/include/opencv;/usr/local/include
-- OpenCV lib dir found at 
-- Boost version: 1.53.0
-- Found the following Boost libraries:
--   system
-- Boost found at /usr/local/include
-- Found Eigen3: /usr/local/include/eigen3 (Required is at least version "2.91.0") 
-- Eigen3 found: TRUE
-- Eigen3 include dir found at /usr/local/include/eigen3
-- Eigen3 version: 3.2.92
-- OpenCV 2.x detected
-- OpenCV include dir found at /usr/local/include/opencv;/usr/local/include
-- OpenCV lib dir found at 
-- Boost version: 1.53.0
-- Found the following Boost libraries:
--   system
--   filesystem
--   program_options
-- Boost found at /usr/local/include
-- Configuring done
-- Generating done
-- Build files have been written to: /root/morphable_eos/bulid

cmak is success

**Comment by patrikhuber** [comment]
Do you have the boost devel packages installed? Make sure to follow the
instructions.
In any case, 1.53.0 is a bit old, not sure if that could also be the issue.
I recommend upgrading.
