### ISSUE TITLE
more examples.

### ISSUE THREAD

**Issue by ZHAIXINGZHAIYUE** [patrikhuber/eos#42]
your work is great ! thank you.But,more example is needed for beginer. Could you give us a example about the function:
 `std::pair<cv::Mat, cv::Mat> render(Mesh mesh, cv::Mat model_view_matrix, cv::Mat projection_matrix, int viewport_width, int viewport_height, const boost::optional<Texture>& texture = boost::none, bool enable_backface_culling = false, bool enable_near_clipping = true, bool enable_far_clipping = true)`.
thanks again.

**Comment by patrikhuber** [comment]
Thank you very much!

[4dface](https://github.com/patrikhuber/4dface) is quite a good example, particularly around [this line](https://github.com/patrikhuber/4dface/blob/master/apps/4dface.cpp#L243) for the `render()` function.

Does that help you?

**Comment by ZHAIXINGZHAIYUE** [comment]
It help me a lot , than you.
