### ISSUE TITLE
Linker errors - used 32bit CMake generator with 64bit boost

### ISSUE THREAD

**Issue by Adra8373** [patrikhuber/eos#44]
Hello 

Firstly, thank you so much for offering your code. 

I tried to run the code on Visual Studio 2015 update 3 (Windows 7 64bit). But when I tried to run the example, I got a 49 debug errors saying that : 

Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK1104	cannot open file 'boost_program_options-vc140-mt-gd-1_58.lib'	fit-model	C:\phd\codes\eos-master (1)\eos-master\build\examples\LINK	1	
Error	LNK2019	unresolved external symbol "__declspec(dllimport) class boost::system::error_category const & __cdecl boost::system::system_category(void)" (__imp_?system_category@system@boost@@YAAEBVerror_category@12@XZ) referenced in function "void __cdecl boost::system::`dynamic initializer for 'native_ecat''(void)" (??__Enative_ecat@system@boost@@YAXXZ)	scm-to-cereal	C:\phd\codes\eos-master (1)\eos-master\build\examples\scm-to-cereal.obj	1	
Error	LNK2019	unresolved external symbol "__declspec(dllimport) class boost::system::error_category const & __cdecl boost::system::generic_category(void)" (__imp_?generic_category@system@boost@@YAAEBVerror_category@12@XZ) referenced in function "void __cdecl boost::system::`dynamic initializer for 'errno_ecat''(void)" (??__Eerrno_ecat@system@boost@@YAXXZ)	scm-to-cereal	C:\phd\codes\eos-master (1)\eos-master\build\examples\scm-to-cereal.obj	1	
Error	LNK2019	unresolved external symbol "__declspec(dllimport) void __cdecl boost::filesystem::path_traits::convert(char const *,char const *,class std::basic_string<wchar_t,struct std::char_traits<wchar_t>,class std::allocator<wchar_t> > &,class std::codecvt<wchar_t,char,struct _Mbstatet> const &)" (__imp_?convert@path_traits@filesystem@boost@@YAXPEBD0AEAV?$basic_string@_WU?$char_traits@_W@std@@V?$allocator@_W@2@@std@@AEBV?$codecvt@_WDU_Mbstatet@@@5@@Z) referenced in function "void __cdecl boost::filesystem::path_traits::convert(char const *,char const *,class std::basic_string<wchar_t,struct std::char_traits<wchar_t>,class std::allocator<wchar_t> > &)" (?convert@path_traits@filesystem@boost@@YAXPEBD0AEAV?$basic_string@_WU?$char_traits@_W@std@@V?$allocator@_W@2@@std@@@Z)	scm-to-cereal	C:\phd\codes\eos-master (1)\eos-master\build\examples\scm-to-cereal.obj	1	
Error	LNK2019	unresolved external symbol "__declspec(dllimport) public: __cdecl boost::filesystem::path::path(void)" (__imp_??0path@filesystem@boost@@QEAA@XZ) referenced in function main	scm-to-cereal	C:\phd\codes\eos-master (1)\eos-master\build\examples\scm-to-cereal.obj	1	
Error	LNK2019	unresolved external symbol "__declspec(dllimport) public: __cdecl boost::filesystem::path::path(class boost::filesystem::path const &)" (__imp_??0path@filesystem@boost@@QEAA@AEBV012@@Z) referenced in function "class eos::morphablemodel::MorphableModel __cdecl eos::morphablemodel::load_scm_model(class boost::filesystem::path,class boost::filesystem::path)" (?load_scm_model@morphablemodel@eos@@YA?AVMorphableModel@12@Vpath@filesystem@boost@@0@Z)	scm-to-cereal	C:\phd\codes\eos-master (1)\eos-master\build\examples\scm-to-cereal.obj	1	
Error	LNK2019	unresolved external symbol "__declspec(dllimport) public: class boost::filesystem::path & __cdecl boost::filesystem::path::operator=(class boost::filesystem::path const &)" (__imp_??4path@filesystem@boost@@QEAAAEAV012@AEBV012@@Z) referenced in function "public: virtual void __cdecl boost::program_options::typed_value<class boost::filesystem::path,char>::notify(class boost::any const &)const " (?notify@?$typed_value@Vpath@filesystem@boost@@D@program_options@boost@@UEBAXAEBVany@3@@Z)	scm-to-cereal	C:\phd\codes\eos-master (1)\eos-master\build\examples\scm-to-cereal.obj	1	
Error	LNK2019	unresolved external symbol "__declspec(dllimport) public: class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const __cdecl boost::filesystem::path::string(void)const " (__imp_?string@path@filesystem@boost@@QEBA?BV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ) referenced in function "class std::vector<class cv::Vec<float,2>,class std::allocator<class cv::Vec<float,2> > > __cdecl eos::morphablemodel::load_isomap(class boost::filesystem::path)" (?load_isomap@morphablemodel@eos@@YA?AV?$vector@V?$Vec@M$01@cv@@V?$allocator@V?$Vec@M$01@cv@@@std@@@std@@Vpath@filesystem@boost@@@Z)	scm-to-cereal	C:\phd\codes\eos-master (1)\eos-master\build\examples\scm-to-cereal.obj	1	
Error	LNK2019	unresolved external symbol "__declspec(dllimport) public: bool __cdecl boost::filesystem::path::empty(void)const " (__imp_?empty@path@filesystem@boost@@QEBA_NXZ) referenced in function "class eos::morphablemodel::MorphableModel __cdecl eos::morphablemodel::load_scm_model(class boost::filesystem::path,class boost::filesystem::path)" (?load_scm_model@morphablemodel@eos@@YA?AVMorphableModel@12@Vpath@filesystem@boost@@0@Z)	scm-to-cereal	C:\phd\codes\eos-master (1)\eos-master\build\examples\scm-to-cereal.obj	1	
Error	LNK2019	unresolved external symbol "__declspec(dllimport) public: static class std::codecvt<wchar_t,char,struct _Mbstatet> const & __cdecl boost::filesystem::path::codecvt(void)" (__imp_?codecvt@path@filesystem@boost@@SAAEBV?$codecvt@_WDU_Mbstatet@@@std@@XZ) referenced in function "void __cdecl boost::filesystem::path_traits::convert(char const *,char const *,class std::basic_string<wchar_t,struct std::char_traits<wchar_t>,class std::allocator<wchar_t> > &)" (?convert@path_traits@filesystem@boost@@YAXPEBD0AEAV?$basic_string@_WU?$char_traits@_W@std@@V?$allocator@_W@2@@std@@@Z)	scm-to-cereal	C:\phd\codes\eos-master (1)\eos-master\build\examples\scm-to-cereal.obj	1	
Error	LNK2019	unresolved external symbol "__declspec(dllimport) public: __cdecl boost::filesystem::path::~path(void)" (__imp_??1path@filesystem@boost@@QEAA@XZ) referenced in function "class std::vector<class cv::Vec<float,2>,class std::allocator<class cv::Vec<float,2> > > __cdecl eos::morphablemodel::load_isomap(class boost::filesystem::path)" (?load_isomap@morphablemodel@eos@@YA?AV?$vector@V?$Vec@M$01@cv@@V?$allocator@V?$Vec@M$01@cv@@@std@@@std@@Vpath@filesystem@boost@@@Z)	scm-to-cereal	C:\phd\codes\eos-master (1)\eos-master\build\examples\scm-to-cereal.obj	1	
Error	LNK2019	unresolved external symbol "__declspec(dllimport) public: __cdecl boost::program_options::validation_error::validation_error(enum boost::program_options::validation_error::kind_t,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,int)" (__imp_??0validation_error@program_options@boost@@QEAA@W4kind_t@012@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@1H@Z) referenced in function "class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const & __cdecl boost::program_options::validators::get_single_string<char>(class std::vector<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class std::allocator<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > > > const &,bool)" (??$get_single_string@D@validators@program_options@boost@@YAAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBV?$vector@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$allocator@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@@4@_N@Z)	scm-to-cereal	C:\phd\codes\eos-master (1)\eos-master\build\examples\scm-to-cereal.obj	1	
Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2019	unresolved external symbol "__declspec(dllimport) public: virtual __cdecl boost::program_options::validation_error::~validation_error(void)" (__imp_??1validation_error@program_options@boost@@UEAA@XZ) referenced in function "class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const & __cdecl boost::program_options::validators::get_single_string<char>(class std::vector<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class std::allocator<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > > > const &,bool)" (??$get_single_string@D@validators@program_options@boost@@YAAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBV?$vector@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$allocator@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@@4@_N@Z)	scm-to-cereal	C:\phd\codes\eos-master (1)\eos-master\build\examples\scm-to-cereal.obj	1	
Error	LNK2019	unresolved external symbol "__declspec(dllimport) public: __cdecl boost::program_options::validation_error::validation_error(class boost::program_options::validation_error const &)" (__imp_??0validation_error@program_options@boost@@QEAA@AEBV012@@Z) referenced in function "public: __cdecl boost::exception_detail::error_info_injector<class boost::program_options::validation_error>::error_info_injector<class boost::program_options::validation_error>(struct boost::exception_detail::error_info_injector<class boost::program_options::validation_error> const &)" (??0?$error_info_injector@Vvalidation_error@program_options@boost@@@exception_detail@boost@@QEAA@AEBU012@@Z)	scm-to-cereal	C:\phd\codes\eos-master (1)\eos-master\build\examples\scm-to-cereal.obj	1	
Error	LNK2019	unresolved external symbol "__declspec(dllimport) public: __cdecl boost::program_options::invalid_option_value::invalid_option_value(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (__imp_??0invalid_option_value@program_options@boost@@QEAA@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z) referenced in function __catch$??$validate@Vpath@filesystem@boost@@D@program_options@boost@@YAXAEAVany@1@AEBV?$vector@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$allocator@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@@std@@PEAVpath@filesystem@1@J@Z$0	scm-to-cereal	C:\phd\codes\eos-master (1)\eos-master\build\examples\scm-to-cereal.obj	1	
Error	LNK2019	unresolved external symbol "__declspec(dllimport) public: __cdecl boost::program_options::invalid_option_value::invalid_option_value(class boost::program_options::invalid_option_value const &)" (__imp_??0invalid_option_value@program_options@boost@@QEAA@AEBV012@@Z) referenced in function "public: __cdecl boost::exception_detail::error_info_injector<class boost::program_options::invalid_option_value>::error_info_injector<class boost::program_options::invalid_option_value>(struct boost::exception_detail::error_info_injector<class boost::program_options::invalid_option_value> const &)" (??0?$error_info_injector@Vinvalid_option_value@program_options@boost@@@exception_detail@boost@@QEAA@AEBU012@@Z)	scm-to-cereal	C:\phd\codes\eos-master (1)\eos-master\build\examples\scm-to-cereal.obj	1	
Error	LNK2019	unresolved external symbol "__declspec(dllimport) public: __cdecl boost::program_options::value_semantic_codecvt_helper<char>::value_semantic_codecvt_helper<char>(void)" (__imp_??0?$value_semantic_codecvt_helper@D@program_options@boost@@QEAA@XZ) referenced in function "public: __cdecl boost::program_options::typed_value<class boost::filesystem::path,char>::typed_value<class boost::filesystem::path,char>(class boost::filesystem::path *)" (??0?$typed_value@Vpath@filesystem@boost@@D@program_options@boost@@QEAA@PEAVpath@filesystem@2@@Z)	scm-to-cereal	C:\phd\codes\eos-master (1)\eos-master\build\examples\scm-to-cereal.obj	1	
Error	LNK2019	unresolved external symbol "__declspec(dllimport) public: virtual __cdecl boost::program_options::value_semantic_codecvt_helper<char>::~value_semantic_codecvt_helper<char>(void)" (__imp_??1?$value_semantic_codecvt_helper@D@program_options@boost@@UEAA@XZ) referenced in function "int `public: __cdecl boost::program_options::typed_value<class boost::filesystem::path,char>::typed_value<class boost::filesystem::path,char>(class program_options::filesystem::path *)'::`1'::dtor$0" (?dtor$0@?0???0?$typed_value@Vpath@filesystem@boost@@D@program_options@boost@@QEAA@PEAVpath@filesystem@2@@Z@4HA)	scm-to-cereal	C:\phd\codes\eos-master (1)\eos-master\build\examples\scm-to-cereal.obj	1	
Error	LNK2019	unresolved external symbol "__declspec(dllimport) void __cdecl boost::program_options::validators::check_first_occurrence(class boost::any const &)" (__imp_?check_first_occurrence@validators@program_options@boost@@YAXAEBVany@3@@Z) referenced in function "void __cdecl boost::program_options::validate<class boost::filesystem::path,char>(class boost::any &,class std::vector<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class std::allocator<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > > > const &,class boost::filesystem::path *,long)" (??$validate@Vpath@filesystem@boost@@D@program_options@boost@@YAXAEAVany@1@AEBV?$vector@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$allocator@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@@std@@PEAVpath@filesystem@1@J@Z)	scm-to-cereal	C:\phd\codes\eos-master (1)\eos-master\build\examples\scm-to-cereal.obj	1	
Error	LNK2019	unresolved external symbol "__declspec(dllimport) void __cdecl boost::program_options::validate(class boost::any &,class std::vector<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class std::allocator<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > > > const &,bool *,int)" (__imp_?validate@program_options@boost@@YAXAEAVany@2@AEBV?$vector@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$allocator@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@@std@@PEA_NH@Z) referenced in function "public: virtual void __cdecl boost::program_options::typed_value<bool,char>::xparse(class boost::any &,class std::vector<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class std::allocator<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > > > const &)const " (?xparse@?$typed_value@_ND@program_options@boost@@UEBAXAEAVany@3@AEBV?$vector@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$allocator@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@@std@@@Z)	scm-to-cereal	C:\phd\codes\eos-master (1)\eos-master\build\examples\scm-to-cereal.obj	1	
Error	LNK2019	unresolved external symbol "__declspec(dllimport) public: class boost::program_options::options_description_easy_init & __cdecl boost::program_options::options_description_easy_init::operator()(char const *,class boost::program_options::value_semantic const *,char const *)" (__imp_??Roptions_description_easy_init@program_options@boost@@QEAAAEAV012@PEBDPEBVvalue_semantic@12@0@Z) referenced in function main	scm-to-cereal	C:\phd\codes\eos-master (1)\eos-master\build\examples\scm-to-cereal.obj	1	
Error	LNK2019	unresolved external symbol "__declspec(dllimport) public: __cdecl boost::program_options::options_description::options_description(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,unsigned int,unsigned int)" (__imp_??0options_description@program_options@boost@@QEAA@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@II@Z) referenced in function main	scm-to-cereal	C:\phd\codes\eos-master (1)\eos-master\build\examples\scm-to-cereal.obj	1	
Error	LNK2019	unresolved external symbol "__declspec(dllimport) public: class boost::program_options::options_description_easy_init __cdecl boost::program_options::options_description::add_options(void)" (__imp_?add_options@options_description@program_options@boost@@QEAA?AVoptions_description_easy_init@23@XZ) referenced in function main	scm-to-cereal	C:\phd\codes\eos-master (1)\eos-master\build\examples\scm-to-cereal.obj	1	
Error	LNK2019	unresolved external symbol "__declspec(dllimport) class std::basic_ostream<char,struct std::char_traits<char> > & __cdecl boost::program_options::operator<<(class std::basic_ostream<char,struct std::char_traits<char> > &,class boost::program_options::options_description const &)" (__imp_??6program_options@boost@@YAAEAV?$basic_ostream@DU?$char_traits@D@std@@@std@@AEAV23@AEBVoptions_description@01@@Z) referenced in function main	scm-to-cereal	C:\phd\codes\eos-master (1)\eos-master\build\examples\scm-to-cereal.obj	1	
Error	LNK2019	unresolved external symbol "__declspec(dllimport) public: __cdecl boost::program_options::options_description::~options_description(void)" (__imp_??1options_description@program_options@boost@@QEAA@XZ) referenced in function main	scm-to-cereal	C:\phd\codes\eos-master (1)\eos-master\build\examples\scm-to-cereal.obj	1	
Error	LNK2019	unresolved external symbol "__declspec(dllimport) public: __cdecl boost::program_options::detail::cmdline::cmdline(class std::vector<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class std::allocator<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > > > const &)" (__imp_??0cmdline@detail@program_options@boost@@QEAA@AEBV?$vector@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$allocator@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@@std@@@Z) referenced in function "public: __cdecl boost::program_options::basic_command_line_parser<char>::basic_command_line_parser<char>(int,char const * const * const)" (??0?$basic_command_line_parser@D@program_options@boost@@QEAA@HQEBQEBD@Z)	scm-to-cereal	C:\phd\codes\eos-master (1)\eos-master\build\examples\scm-to-cereal.obj	1	
Error	LNK2019	unresolved external symbol "__declspec(dllimport) public: int __cdecl boost::program_options::detail::cmdline::get_canonical_option_prefix(void)" (__imp_?get_canonical_option_prefix@cmdline@detail@program_options@boost@@QEAAHXZ) referenced in function "public: class boost::program_options::basic_parsed_options<char> __cdecl boost::program_options::basic_command_line_parser<char>::run(void)" (?run@?$basic_command_line_parser@D@program_options@boost@@QEAA?AV?$basic_parsed_options@D@23@XZ)	scm-to-cereal	C:\phd\codes\eos-master (1)\eos-master\build\examples\scm-to-cereal.obj	1	
Error	LNK2019	unresolved external symbol "__declspec(dllimport) public: void __cdecl boost::program_options::detail::cmdline::set_options_description(class boost::program_options::options_description const &)" (__imp_?set_options_description@cmdline@detail@program_options@boost@@QEAAXAEBVoptions_description@34@@Z) referenced in function "public: class boost::program_options::basic_command_line_parser<char> & __cdecl boost::program_options::basic_command_line_parser<char>::options(class boost::program_options::options_description const &)" (?options@?$basic_command_line_parser@D@program_options@boost@@QEAAAEAV123@AEBVoptions_description@23@@Z)	scm-to-cereal	C:\phd\codes\eos-master (1)\eos-master\build\examples\scm-to-cereal.obj	1	
Error	LNK2019	unresolved external symbol "__declspec(dllimport) public: class std::vector<class boost::program_options::basic_option<char>,class std::allocator<class boost::program_options::basic_option<char> > > __cdecl boost::program_options::detail::cmdline::run(void)" (__imp_?run@cmdline@detail@program_options@boost@@QEAA?AV?$vector@V?$basic_option@D@program_options@boost@@V?$allocator@V?$basic_option@D@program_options@boost@@@std@@@std@@XZ) referenced in function "public: class boost::program_options::basic_parsed_options<char> __cdecl boost::program_options::basic_command_line_parser<char>::run(void)" (?run@?$basic_command_line_parser@D@program_options@boost@@QEAA?AV?$basic_parsed_options@D@23@XZ)	scm-to-cereal	C:\phd\codes\eos-master (1)\eos-master\build\examples\scm-to-cereal.obj	1	
Error	LNK2019	unresolved external symbol "__declspec(dllimport) public: __cdecl boost::program_options::detail::cmdline::~cmdline(void)" (__imp_??1cmdline@detail@program_options@boost@@QEAA@XZ) referenced in function "public: __cdecl boost::program_options::basic_command_line_parser<char>::~basic_command_line_parser<char>(void)" (??1?$basic_command_line_parser@D@program_options@boost@@QEAA@XZ)	scm-to-cereal	C:\phd\codes\eos-master (1)\eos-master\build\examples\scm-to-cereal.obj	1	
Error	LNK2019	unresolved external symbol "__declspec(dllimport) class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl boost::program_options::to_internal(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (__imp_?to_internal@program_options@boost@@YA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBV34@@Z) referenced in function "class std::vector<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class std::allocator<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > > > __cdecl boost::program_options::to_internal<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > >(class std::vector<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class std::allocator<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > > > const &)" (??$to_internal@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@program_options@boost@@YA?AV?$vector@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$allocator@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@@std@@AEBV23@@Z)	scm-to-cereal	C:\phd\codes\eos-master (1)\eos-master\build\examples\scm-to-cereal.obj	1	
Error	LNK2019	unresolved external symbol "__declspec(dllimport) void __cdecl boost::program_options::store(class boost::program_options::basic_parsed_options<char> const &,class boost::program_options::variables_map &,bool)" (__imp_?store@program_options@boost@@YAXAEBV?$basic_parsed_options@D@12@AEAVvariables_map@12@_N@Z) referenced in function main	scm-to-cereal	C:\phd\codes\eos-master (1)\eos-master\build\examples\scm-to-cereal.obj	1	
Error	LNK2019	unresolved external symbol "__declspec(dllimport) void __cdecl boost::program_options::notify(class boost::program_options::variables_map &)" (__imp_?notify@program_options@boost@@YAXAEAVvariables_map@12@@Z) referenced in function main	scm-to-cereal	C:\phd\codes\eos-master (1)\eos-master\build\examples\scm-to-cereal.obj	1	
Error	LNK2019	unresolved external symbol "__declspec(dllimport) public: unsigned __int64 __cdecl std::_Tree<class std::_Tmap_traits<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class boost::program_options::variable_value,struct std::less<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > >,class std::allocator<struct std::pair<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const ,class boost::program_options::variable_value> >,0> >::count(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)const " (__imp_?count@?$_Tree@V?$_Tmap_traits@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@Vvariable_value@program_options@boost@@U?$less@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@V?$allocator@U?$pair@$$CBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@Vvariable_value@program_options@boost@@@std@@@2@$0A@@std@@@std@@QEBA_KAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@2@@Z) referenced in function main	scm-to-cereal	C:\phd\codes\eos-master (1)\eos-master\build\examples\scm-to-cereal.obj	1	
Error	LNK2019	unresolved external symbol "__declspec(dllimport) public: __cdecl boost::program_options::variables_map::variables_map(void)" (__imp_??0variables_map@program_options@boost@@QEAA@XZ) referenced in function main	scm-to-cereal	C:\phd\codes\eos-master (1)\eos-master\build\examples\scm-to-cereal.obj	1	
Error	LNK2019	unresolved external symbol "__declspec(dllimport) public: virtual __cdecl boost::program_options::variables_map::~variables_map(void)" (__imp_??1variables_map@program_options@boost@@UEAA@XZ) referenced in function main	scm-to-cereal	C:\phd\codes\eos-master (1)\eos-master\build\examples\scm-to-cereal.obj	1	
Error	LNK2001	unresolved external symbol "public: __cdecl boost::program_options::error::error(class boost::program_options::error const &)" (??0error@program_options@boost@@QEAA@AEBV012@@Z)	scm-to-cereal	C:\phd\codes\eos-master (1)\eos-master\build\examples\scm-to-cereal.obj	1	
Error	LNK2001	unresolved external symbol "public: __cdecl boost::program_options::error_with_option_name::error_with_option_name(class boost::program_options::error_with_option_name const &)" (??0error_with_option_name@program_options@boost@@QEAA@AEBV012@@Z)	scm-to-cereal	C:\phd\codes\eos-master (1)\eos-master\build\examples\scm-to-cereal.obj	1	
Error	LNK2001	unresolved external symbol "public: __cdecl boost::program_options::invalid_option_value::invalid_option_value(class boost::program_options::invalid_option_value const &)" (??0invalid_option_value@program_options@boost@@QEAA@AEBV012@@Z)	scm-to-cereal	C:\phd\codes\eos-master (1)\eos-master\build\examples\scm-to-cereal.obj	1	
Error	LNK2001	unresolved external symbol "public: __cdecl boost::program_options::validation_error::validation_error(class boost::program_options::validation_error const &)" (??0validation_error@program_options@boost@@QEAA@AEBV012@@Z)	scm-to-cereal	C:\phd\codes\eos-master (1)\eos-master\build\examples\scm-to-cereal.obj	1	
Error	LNK2001	unresolved external symbol "private: virtual void __cdecl boost::program_options::value_semantic_codecvt_helper<char>::parse(class boost::any &,class std::vector<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class std::allocator<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > > > const &,bool)const " (?parse@?$value_semantic_codecvt_helper@D@program_options@boost@@EEBAXAEAVany@3@AEBV?$vector@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$allocator@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@@std@@_N@Z)	scm-to-cereal	C:\phd\codes\eos-master (1)\eos-master\build\examples\scm-to-cereal.obj	1	
Error	LNK2001	unresolved external symbol "public: virtual void __cdecl boost::program_options::error_with_option_name::set_option_name(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (?set_option_name@error_with_option_name@program_options@boost@@UEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z)	scm-to-cereal	C:\phd\codes\eos-master (1)\eos-master\build\examples\scm-to-cereal.obj	1	
Error	LNK2001	unresolved external symbol "protected: virtual void __cdecl boost::program_options::error_with_option_name::substitute_placeholders(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)const " (?substitute_placeholders@error_with_option_name@program_options@boost@@MEBAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z)	scm-to-cereal	C:\phd\codes\eos-master (1)\eos-master\build\examples\scm-to-cereal.obj	1	
Error	LNK2001	unresolved external symbol "public: virtual char const * __cdecl boost::program_options::error_with_option_name::what(void)const " (?what@error_with_option_name@program_options@boost@@UEBAPEBDXZ)	scm-to-cereal	C:\phd\codes\eos-master (1)\eos-master\build\examples\scm-to-cereal.obj	1	
Error	LNK2001	unresolved external symbol "__declspec(dllimport) class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > boost::program_options::arg" (__imp_?arg@program_options@boost@@3V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@A)	scm-to-cereal	C:\phd\codes\eos-master (1)\eos-master\build\examples\scm-to-cereal.obj	1	
Error	LNK2001	unresolved external symbol "__declspec(dllimport) public: static unsigned int const boost::program_options::options_description::m_default_line_length" (__imp_?m_default_line_length@options_description@program_options@boost@@2IB)	scm-to-cereal	C:\phd\codes\eos-master (1)\eos-master\build\examples\scm-to-cereal.obj	1	
  
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
and 3 warnings saying that : 
Severity	Code	Description	Project	File	Line	Suppression State
Warning	LNK4272	library machine type 'X86' conflicts with target machine type 'x64'	scm-to-cereal	C:\boost_1_50_0\stage\lib\boost_system.lib	1	
Warning	LNK4272	library machine type 'X86' conflicts with target machine type 'x64'	scm-to-cereal	C:\boost_1_50_0\stage\lib\boost_filesystem.lib	1	
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

Although the Cmake configuration refers to Boost version: 1.58.0 as shows below:  

Options:
BUILD_EXAMPLES: ON
BUILD_DOCUMENTATION: OFF
OpenCV ARCH: x64
OpenCV RUNTIME: vc14
OpenCV STATIC: OFF
Found OpenCV 2.4.12 in C:/opencv/install/x64/vc14/lib
You might need to add C:\opencv\install\x64\vc14\bin to your PATH to be able to run your applications.
OpenCV include dir found at C:/opencv/install/include;C:/opencv/install/include/opencv
OpenCV lib dir found at C:/opencv/install/x64/vc14/lib;C:/opencv/install/x64/vc14/lib
Boost version: 1.58.0
Found the following Boost libraries:
  system
Boost found at C:/boost_1_58_0_for_vc14-64/boost_1_58_0-vc14_64/include
Eigen3 found: TRUE
Eigen3 include dir found at C:/eigen/eigen-eigen-bdd17ee3b1b3
Eigen3 version: 3.2.5
OpenCV 2.x detected
OpenCV ARCH: x64
OpenCV RUNTIME: vc14
OpenCV STATIC: OFF
Found OpenCV 2.4.12 in C:/opencv/install/x64/vc14/lib
You might need to add C:\opencv\install\x64\vc14\bin to your PATH to be able to run your applications.
OpenCV include dir found at C:/opencv/install/include;C:/opencv/install/include/opencv
OpenCV lib dir found at C:/opencv/install/x64/vc14/lib;C:/opencv/install/x64/vc14/lib
Boost version: 1.58.0
Found the following Boost libraries:
  system
  filesystem
  program_options
Boost found at C:/boost_1_58_0_for_vc14-64/boost_1_58_0-vc14_64/include
Configuring done
Generating done

Regards

**Comment by patrikhuber** [comment]
Hi,

Thanks.
It looks like you have 64bit libraries installed but used the 32bit cmake
generator. Use the 64bit VS generator as described in the readme.

**Comment by Adra8373** [comment]
Thank you for replaying you saved my time. I did what you said and the problem has been solved, but I have another problem which is below: 

Error while parsing command-line arguments: the option '--model' is required but
 missing
Use --help to display a list of options.
Press any key to continue . . .

I installed the model (share/sfm_shape_3448.bin) but in which directory should I put it to work ?

Many thanks for replying.

**Comment by patrikhuber** [comment]
When you run the `INSTALL` target, all files will automatically be put in the right place (inside the installation directory). Don't forget to set `-DCMAKE_INSTALL_PREFIX`, as described in the readme.

Alternatively you can give the full path to the model with the `--model` option.

**Comment by Adra8373** [comment]
Many thanks.

Changing -DCMAKE_INSTALL_PREFIX path solved the problem.
