### ISSUE TITLE
Create face model from 5 obj's

### ISSUE THREAD

**Issue by samsgates** [patrikhuber/eos#45]
Hi Patrikhuber,

i want to create my own base face model with 5 sample obj 3D model, i am not familiar with MatLap software, do you have any guideline or tutorial to create base face model? 
( or )
please describe with simple steps

**Comment by patrikhuber** [comment]
Hi,

I'm not really sure what you want to do... I suggest you read through #26 and #23.

**Comment by samsgates** [comment]
Thanks, i need some MatLab tutorial for generate PCA, EV from OBJ model

**Comment by patrikhuber** [comment]
Sounds like a good idea. You can also find more information in the issues I linked and in our VISAPP paper. The most important things is the dense correspondence (registration).

I'll close this, feel free to reopen later.

**Comment by tiancaipipi110** [comment]
@samsgates What is EV?

**Comment by patrikhuber** [comment]
@tiancaipipi110 It's a commonly/sometimes used abbreviation for eigenvectors or eigenvalues (which are two separate things, so the abbreviation is a bit ambiguous). I suggest you do an introductory tutorial to PCA to get familiar with these terms.
