### ISSUE TITLE
Generate all models in dataset

### ISSUE THREAD

**Issue by samsgates** [patrikhuber/eos#46]
1.  I guess 63 different type of faces are available in "sfm_shape_3448.bin", i can able to see PCA values for all models, but how can i see all original faces in dataset, like any script to generate all sample faces as obj file output. 

2. How to add my own basel face model into your existing dataset.

**Comment by patrikhuber** [comment]
1. You can't go back to the original faces, PCA is not "reversible". You can generate random faces or faces with specific coefficients.

2. Your own Basel face model? I don't think there is such a thing. There is only _the_ Basel Face Model (BFM), released by Paysan et al. (& Vetter) in 2009.

I think you have some fundamental misunderstandings about the theory and algorithms, I suggest you read some of the papers.

**Comment by samsgates** [comment]
sorry for misunderstanding, own model mean i can create new model with same vertices (3448) with different shape (base reference from reference.obj file), then how can i add that model into your existing dataset (at runtime or predefine file)

**Comment by patrikhuber** [comment]
Why would you want to add that face back to the "dataset"? That face was generated by the model, so adding it back to the PCA model doesn't change anything.

**Comment by samsgates** [comment]
How can i get random face?

**Comment by samsgates** [comment]
1. oh okay fine. so i need to change normal model to PCA data, so that i can use like PCA model
2. how to get random faces?

**Comment by patrikhuber** [comment]
1. What do you mean? The "normal model", if you mean the Surrey Face Model (for example the `sfm_shape_3448.bin`), is a PCA model. Please see the paper(s).

2. Please see the documentation, specifically the member functions of [MorphableModel](http://patrikhuber.github.io/eos/doc/classeos_1_1morphablemodel_1_1_morphable_model.html) and, if you need to access more of the internals, [PcaModel](http://patrikhuber.github.io/eos/doc/classeos_1_1morphablemodel_1_1_pca_model.html). For example, there is a `MorphableModel::draw_sample(...)` method, which will return a mesh given PCA coefficients or standard deviations. Again, this is all described in our VISAPP paper.

**Comment by samsgates** [comment]
Thanks
