### ISSUE TITLE
Dataset Face collection

### ISSUE THREAD

**Issue by samsgates** [patrikhuber/eos#47]
how many different types of faces are included in "sfm_shape_3448" dataset. some indians face shapes are not match with output model. (specially female triangular shape face)
Types of face shape : Oblong faces, Heart faces, Square faces, Oval faces, round faces, Triangular faces, Diamond Faces
did you covered all these types of shapes?

**Comment by patrikhuber** [comment]
Please read these details in our VISAPP paper.

**Comment by samsgates** [comment]
Thanks, i got it
