### ISSUE TITLE
Possible missing namespace qualifiers?

### ISSUE THREAD

**Issue by samsgates** [patrikhuber/eos#49]
when i tried to build dev branch "https://github.com/patrikhuber/eos/tree/devel/utils" 
the below error message triggered, you have any idea how to resolve this issue?

![attachment3](https://cloud.githubusercontent.com/assets/4558944/17587989/69bf50d2-5fe9-11e6-86a9-5f2918aad927.png)

**Comment by patrikhuber** [comment]
It looks like I possibly forgot some namespace qualifiers there. The last one needs to be prefixed with `cv::`, the other ones I believe with `eos::render::`.
Alternatively it's possible that the `#include` for `Texture` is missing, but it's most likely just the namespace.

**Comment by patrikhuber** [comment]
I think this should be fixed with 8782faf18de078e54aff85636b5692ae93b90e7b.
