### ISSUE TITLE
Can't figure out how to run INSTALL target.

### ISSUE THREAD

**Issue by farazirfan47** [patrikhuber/eos#51]
I have successfully generate VS 2015 files using cmake by using this commands:

`git clone https://github.com/patrikhuber/eos.git
mkdir build && cd build
cmake -G "<your favourite generator>" ../eos -DCMAKE_INSTALL_PREFIX=../install/`

but when I run `make && make install` It said "make: *** No targets specified and no makefile found.  Stop." 

I just can't figure it out how run install target.After running above commands I have successfully generate the build folder which has VS 2015 solution file etc. please help me.

Thanks

`

**Comment by patrikhuber** [comment]
Well you just need to read the instructions to the end:

> make && make install # **or open the project file and build in an IDE like Visual Studio**

**Comment by farazirfan47** [comment]
Yes I followed the instruction but when I run `make && make install` It gives me this error "make: *** No targets specified and no makefile found. Stop."

Am I doing wrong anything? Please guide me I am new and I have never build the projects using cmake Thanks.

**Comment by patrikhuber** [comment]
I put the second part of the instructions in bold-font ;-)

>  # or open the project file and build in an IDE like Visual Studio

You have to open the .sln file and build as "normally" with VS.

**Comment by farazirfan47** [comment]
I have successfully build the the project that will create the "fit-model.exe" file but when I run this exe file It will give me the error "some dll file is missing" see the screenshot below. 

![image](https://cloud.githubusercontent.com/assets/21068373/17832778/9de4f1d6-6724-11e6-8254-499f397a2ec8.png)

**Comment by patrikhuber** [comment]
You need to add the path to the boost and OpenCV (and possibly other) DLL's to your Windows PATH variable.

**Comment by farazirfan47** [comment]
Thanks patrick it works.
I have one more question the question is how do I get .pts file for my own image? I want to create mt own 3D Face model.How do I create .pts file for my image?

Thanks

**Comment by patrikhuber** [comment]
Please see #30.

**Comment by farazirfan47** [comment]
I have got it Thank you so much patrick.
Your algorithm is just awesome again Thanks so much for you help and time.

**Comment by patrikhuber** [comment]
Thanks :-)
