### ISSUE TITLE
Difference between Morphable model and PCA Model.

### ISSUE THREAD

**Issue by farazirfan47** [patrikhuber/eos#52]
Hi patrikhuber,

I know this is a very basic question but I want know whats the difference between Morphable model  and PCA model in simple words I am confused about these two terms can you please give me a little bit overview about these two terms and differentiate them and what they contains? also tell me about basel face model are they related with each others?

Thanks

**Comment by patrikhuber** [comment]
Morphable Model is the term usually used for a "model" containing two models, namely a PCA model of shape and a PCA model of vertex colour (albedo). You can find more details in the 1999 Blanz & Vetter paper. Our VISAPP paper also has a nice class diagram that explains the relationship in the code.

The Basel Face Model is a Morphable Model from the Graphics and Vision group in Basel ([link](http://faces.cs.unibas.ch/bfm/)). There's also our [Surrey Face Model](cvssp.org/facemodel).

**Comment by farazirfan47** [comment]
Thanks very much.

**Comment by tiancaipipi110** [comment]
@patrikhuber Hi, say we use ICP for shape model. But when computing albedo model, how do you make sure the color vertex are in correspondence when original scans and template have different amount of verts?

**Comment by patrikhuber** [comment]
@tiancaipipi110 Just use the registered template's vertex positions to look up the colour values in the texture of the original scan. I recommend that you read the literature on registration. This is not really on topic here. You would be better suited on a help website like StackExchange.

**Comment by tiancaipipi110** [comment]
@patrikhuber right! Thanks!
