### ISSUE TITLE
Full head model Testing

### ISSUE THREAD

**Issue by samsgates** [patrikhuber/eos#53]
Hi Patrik,
I have created full head model (PCA model) and generated binary file as well (.bin file). i have used 20 different shape models for creating PCA binary file. 

when i testing with fit-model command using my custom binary file (d123.bin), output model generated (obj) as same shape (same output) for all different shape picture (its look like mean model - average shape). i didn't see any difference between all output model
  
All landmark mappings are properly assign in "ibug2did.txt" file. 

"./fit-model -m share/d123.bin -i face2.jpg -l face2.pts -p share/ibug2did.txt -o out"

you have any idea how to resolve this issue?

**Comment by samsgates** [comment]
Top : output model
Bottom : one of the reference model

![test](https://cloud.githubusercontent.com/assets/4558944/17893451/60dcb4ae-6963-11e6-9bb5-1b7aaaacc2e1.png)

**Comment by patrikhuber** [comment]
Hi Sam,

Looks like nice work!
Can you have a look at the value of the coefficients returned by the shape fitting? That should help.

**Comment by samsgates** [comment]
Top : Generated model
Bottom: Reference model

![test](https://cloud.githubusercontent.com/assets/4558944/17920051/9f55bdc0-69ef-11e6-82a4-9547857a7b11.png)

**Comment by samsgates** [comment]
Multiply with coefficients values as below

vector<float> fitted_coeffs = fitting::fit_shape_to_landmarks_linear(morphable_model, affine_from_ortho, image_points, vertex_indices);
for (int f =0; f <   fitted_coeffs.size(); f++){
  fitted_coeffs[i] =   fitted_coeffs[i] * 60;
}

Result : Almost closed but not accurate, but better output than mean model

**Comment by Thanh-Binh** [comment]
@samsgates : I am interested in how do you build a full head model? by extending the surrey face model?
Thanks.

**Comment by patrikhuber** [comment]
@samsgates Can you instead of this just output the coeffs? However it looks like they're just very low.

How big is your `fitted_coeffs.size()`?

One thing you can try is: 
`fit_shape_to_landmarks_linear` has a parameter `lambda`, the regularisation. Have a look at the current value (the default) and then set lower - for example 0.1 or so.

**Comment by samsgates** [comment]
fitted_coeffs.size() is "20"

i have changed lamda value from "3.0" to "0.1", and there is no difference in output. but any way i achieved almost better quality using Multiply with coefficients

Thanks for your support

**Comment by CodingGou** [comment]
@samsgates : I am also interested in how do you build a full head model? by extending the surrey face model? 
Thanks.

**Comment by CodingGou** [comment]
@samsgates :can you show a demo to me about what you are process with your own full head model? Thanks very much!
