### ISSUE TITLE
How does PCA works in eos.

### ISSUE THREAD

**Issue by farazirfan47** [patrikhuber/eos#54]
What is the role of PCA and why do we need to apply PCA shape and texture model in eos in just simple words.can you explain it in a non-mathematical way,I read about pca in data mining course and I understand it,but I want to know how does it works in eos and how does it apply on the 3D face scans?
I strongly believe that 

`you do not really understand something unless you can explain it to your grandmother -- Albert Einstein`

Well I can't explain it to layman 

Can you explain it in simple words without using mathematical equations so that I will get the purpose of pca in eos as general........suppose that you are explaining this to a layman.

**Comment by patrikhuber** [comment]
The Blanz & Vetter 1999 paper is a nice introduction to PCA for 3D shape models. If you want something easier, you can check out this material: http://gravis.cs.unibas.ch/smiley/
Have a look at their Smiley Tool (works interactively in the browser) and the resources. It's a very simple PCA example.

There are also various resources to [learn more about statistical shape modeling](https://www.futurelearn.com/courses/statistical-shape-modelling).

**Comment by farazirfan47** [comment]
Thanks patrik I got it.
I have one more confusion what this file **sfm_shape_3448.bin** contains is that morphable model or PCA model?
I want to create full head model so I need to create my own binary file like this file **sfm_shape_3448.bin** which contains PCA or morphable model?

**Comment by patrikhuber** [comment]
Have a look at our VISAPP paper of what's in the model. There's also a diagram in there. You can also step through the code in the debugger and then just have a look at what got loaded and what's inside the MorphableModel class.

**Comment by farazirfan47** [comment]
Thanks a lot for your help :)
