### ISSUE TITLE
boost, character conversion failed

### ISSUE THREAD

**Issue by cupwater** [patrikhuber/eos#55]
Hello, Huber! When I run the fit-model after installing eos, I encountered an error as following:
 
`terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<std::logic_error> >'
  what():  character conversion failed
Aborted (core dumped)
`
I run it on Ubuntu 14.04, gcc 4.8.4, Boost 1.59.0.

**Comment by patrikhuber** [comment]
Hi,
Can you check the call stack in the debugger on what line it aborts? Maybe you've just given it a path in a wrong form (e.g. try using double-quotes for the input arguments to `fit-model`).

**Comment by cupwater** [comment]
the debug is in fit-mode.cpp: line 131
`po::store(po::command_line_parser(argc, argv).options(desc).run(), vm);`

**Comment by patrikhuber** [comment]
As I assumed above, looks like you just have a problem with your command-line arguments.

**Comment by cupwater** [comment]
Thanks, I have solved it after re-installing boost. It seems that  something wrong with the boost, not eos code.

**Comment by patrikhuber** [comment]
Great!
