### ISSUE TITLE
expression basis

### ISSUE THREAD

**Issue by cupwater** [patrikhuber/eos#56]
Hi! I see that you wrote in "share/readme.txt" that "6 expression blendshapes for the sfm_shape_3448 model. Contains the expressions angry, disgust, fear, happy, sad and surprised". I'm really interested with it, but I cannot find the expression information in the eos code.
 Could you explain how you use the expression blendshapes? Thank you!

**Comment by patrikhuber** [comment]
Hi,
I think everything you need should be in the [4dface app](https://github.com/patrikhuber/4dface/blob/master/apps/4dface.cpp). It loads and fits expression blendshapes and shows how to use the resulting mesh in various ways.

**Comment by cupwater** [comment]
Thanks! I have viewed the 4dface code, and I'm really appreciate for you and your work. 
P.S. In the 4dface/apps/4dface.cpp file: 225 
" Mat shape_instance = fitting::fit_shape_model(....)  "
Is there any possible that the function " fit_shape_model " been wrote wrong? because I cannot find it in eos, I guess it woud be fit_model function.

**Comment by patrikhuber** [comment]
I recently updated `eos`, but 4dface still points to an older commit in the eos repo - this can cause confusion I guess.

I renamed that function to `fit_shape`, you can find it [here](https://github.com/patrikhuber/eos/blob/master/include/eos/fitting/fitting.hpp#L58).
