### ISSUE TITLE
Full Head Mesh

### ISSUE THREAD

**Issue by farazirfan47** [patrikhuber/eos#57]
What do I need to change in eos for creating full head model. As I know eos mesh only has face region and it cannot create meshes.

I want to know about :
1) what changes are needed in "eos" to make its face only mesh to full head mesh? 
2) If I needed to create my own "sfm_shape_3448.bin" file for creating full head mesh or I can use this file?

Thanks

**Comment by patrikhuber** [comment]
Hi,

Could you have a look at #23, and some of the [other topics](https://github.com/patrikhuber/eos/issues?utf8=%E2%9C%93&q=is%3Aissue%20head%20model) that might be head-related?

I'm happy to answer any remaining questions you have.

One of the main questions you'll have to answer for yourself is if you want a full PCA model over the head,  or just want a more or less "static" head attached to the back of the existing face model.

**Comment by farazirfan47** [comment]
I do not have 3D data of full head that's why I cannot create a full PCA model over head.If you can help me how can I get full head 3d data I will appreciate that and I am able to build my own PCA Model over head,but If you cannot then its okay.
So now I only have one option that is I need some kind of static head that  will attached to the back of existing face only model and look like a full head model,but still I am not sure how to get static head and attached with the existing surrey face model?

**Comment by patrikhuber** [comment]
Well, you can have a look if you find a database with full head scans, for academic use, there is most likely stuff around. But in any case, as you say, depending on your application, a head attached to the face model and having the statistics only calculated on the face-mask might even be what you want.

I haven't done something like this before, but first I would find out which vertices of the face have to be attached to which vertices of the head, and possibly you need some triangulation, to "merge" the meshes. Then, you'd need to adjust or warp the head somehow (at least at the border regions), to make it fit with different face model instances (e.g. if the face model is fitted to a narrow face, the head also needs to get narrower). I can't really give much more help than that.

**Comment by farazirfan47** [comment]
I appreciate for your help and this information in enough to get a way/path for full head creation. 
Thanks for your help as always you do.

**Comment by farazirfan47** [comment]
Hi,I want to find the vertices of surrey face only model and attached with the static head vertices but I am not sure how can I convert cereal binary of "sfm_shape_3448.bin" into obj format So that I am able to modify the morphable model and attached it with the static head can you help me?
Thanks

**Comment by patrikhuber** [comment]
Draw a sample from the model (i.e. just the mean face) and then use `write_obj`.

**Comment by farazirfan47** [comment]
Okay and after modifying the model can I convert it back into cereal binary and use the updated version of sfm_shape_3448.bin?

**Comment by AlKhwarizmiCoder** [comment]
@farazirfan47 : Hi, I'm looking for a similar approach and was wondering if you were able to implement a static head-attach approach? I would appreciate any help.

**Comment by patrikhuber** [comment]
Hi @AlKhwarizmiCoder, there are now a few full-head models available, for example the 4DFM (https://www.4dface.io/4dfm/) for commercial use, or the BFM 2019 for academic use, both of which can be used with eos (depending on what you want to do, it needs a bit of adaptation, but eos is a robust framework/basic to do that, if you bring some experience in that area).

Hope that helps!
