### ISSUE TITLE
texture extraction problem

### ISSUE THREAD

**Issue by cupwater** [patrikhuber/eos#59]
Hi Patrik! I have some questions about the **texture_coordinates** In the class “MorphableModel” reading from the "sfm_shape_3448.bin" file. Since you using the iosmap to set the texture, why you need the texture_coordinates?

**Comment by patrikhuber** [comment]
Hi,
The isomap itself is _defined_ by the texture coordinates, the isomap itself doesn't exist basically. It's the mapping from 3D to 2D texture space, and this mapping is defined by the `texture_coordinates` in the `MorphableModel` class.

**Comment by patrikhuber** [comment]
I'll close this, feel free to reopen if you have further questions.
