### ISSUE TITLE
Python bindings

### ISSUE THREAD

**Issue by patrikhuber** [patrikhuber/eos#60]
I've set up the infrastructure to build Python bindings for eos using pybind11 in the [python-bindings](https://github.com/patrikhuber/eos/tree/python-bindings) branch.

There are no real bindings yet, just a simple example with `PcaModel`. There's a few things that need to be worked out, for example, currently, calling `PcaModel::get_mean_at_point` in Python causes Python to crash, most likely because the function returns a `cv::Vec4f`, which is unknown to Python. I want to test if that's solved if OpenCV-python is imported, or if it doesn't work together like that. Otherwise I could try making bindings for the `glm` vector types.

Any help whatsoever welcome on this.

Once there are actual bindings in the future, it would probably be nice to build them automatically in CMake, so the user doesn't have to run `create-python-bindings` manually.

**Comment by patrikhuber** [comment]
I've created a GitHub [Project](https://github.com/patrikhuber/eos/projects/1) for this!

**Comment by patrikhuber** [comment]
I found out that it won't work together with OpenCV-python, since they don't expose `cv::Mat` and the other types to Python, they generate wrapper functions and return NumPy arrays.

However, pybind11 easily allows to expose existing matrix-like types in Python, by supporting the buffer interface. I've implemented that in e0027ba74d766c9978c9519816e9e207efca37d3 for `cv::Vec4f` and it works great.

One open issue is how to pass images (as NumPy arrays) from Python to C++, but it seems like pybind11 easily supports that case too.

**Comment by sfornengo** [comment]
Thanks for this binding. What are the remaining blocking points to expose fitting::fit_shape_and_pose ?

**Comment by patrikhuber** [comment]
@sfornengo Hi, nothing actually! In fact I just finished that yesterday. It's in the `devel` branch - see the demo: https://github.com/patrikhuber/eos/blob/devel/python/demo.py
Let me know if you have issues.

There are a few more changes in the devel branch that are not finalised yet, like lots of CMake modernisation stuff - but everything should work fine.

**Comment by sfornengo** [comment]
I just try the devel branch and I confirm everything works fine, thanks !
Could we expect render::extract_texture to be exposed too or it is out of your python binding scope ?

**Comment by patrikhuber** [comment]
Cool!

`render::extract_texture` is definitely high up on the list too. The main obstacle is that it requires passing and returning of an image (a 3-channel matrix), and Eigen doesn't really support that. There's a few options, I just don't know which is best - let me give it a try today and tomorrow.

**Comment by patrikhuber** [comment]
This should now work too and there's transparent conversion between `cv::Mat` and NumPy arrays. See b408cd369dc87c9980d7fdd0e7fb7863a86a7685, dd44ea20baa5482b63df30819aa20de6a4cf535a.

**Comment by patrikhuber** [comment]
I will close this issue, as the Python bindings are pretty solid now in the `devel` branch!

Feel free to comment here or open a new issue if anyone wants bindings for something that doesn't work yet.
