### ISSUE TITLE
how to set the regularization term lambda?

### ISSUE THREAD

**Issue by cupwater** [patrikhuber/eos#61]
In the eos code you add an regularization term lambda, and you see a value 10.0f to it. I want to know how you set the value of lambda? If my model is bigger, how to set the value?

**Comment by patrikhuber** [comment]
It's mainly an empirical choice, determined by experiment. If you regularise too much, all faces will look like the mean face. If you regularise too little, shapes can get too far away from the mean and don't look like faces anymore.

**Comment by cupwater** [comment]
I get it. Thank you!

**Comment by cupwater** [comment]
Besides, what the difference between the shape fitting and blendshape fitting? Should I set different lambda values for shape and blendshape fitting?

**Comment by patrikhuber** [comment]
The shape fitting fits _shape identity_, and the blendshape fitting fits _expressions_. They're two different linear systems with different regularisation, so yes it makes sense to set two different lambdas. The defaults work pretty well for me though.

**Comment by patrikhuber** [comment]
I'll close this, feel free to re-open if you have further questions.
