### ISSUE TITLE
Deformation Of Mesh

### ISSUE THREAD

**Issue by qko03160316** [patrikhuber/eos#62]
Hi, 
thank you for your project that it is so wonderful !
But I am wondering if the mesh generated could be deformed like the youtube video below:
https://www.youtube.com/watch?v=MMa2oT1wMIs

like the empty eyes, or the contour fitting to 2D face image.

Thanks a lot !

**Comment by patrikhuber** [comment]
Hi,
Thanks!
Making the eyes empty should be easy by just removing the associated vertices and triangles.
As for the mesh, you can definitely deform a face mesh obtained with eos in a way like that. What they do is beyond the fitting that's available in eos (we fit a PCA shape model and expression blendshapes).

**Comment by qko03160316** [comment]
But how can I know which vertices are associated ? 
Just try and error ?

Thanks.

**Comment by patrikhuber** [comment]
Just write out the mean face as obj and open it in MeshLab or Blender to select the vertices.
You can either use the provided low-res reference.obj, or write out the mean using `draw_sample` and `write_obj`, or use the example app `generate-obj`.

**Comment by qko03160316** [comment]
Is it possible to modify `sfm_shape_3448.bin` and `expression_blendshapes_3448.bin` like adding some new expression, or adding new face ?

Thanks a lot ! Sorry for many questions , I am a newbie , and I am trying to finish my school project with eos.

**Comment by patrikhuber** [comment]
I suggest you to read our VISAPP paper (and possibly more) to get a better understanding of the PCA shape model.

Adding new expressions is easy and could simply be done by adding new blendshapes (either from 3D data or manually created ones using for example Blender).

**Comment by patrikhuber** [comment]
I'll close this, feel free to re-open if you have further questions.
