### ISSUE TITLE
nonlinear shape fitting vs linear shape fitting?

### ISSUE THREAD

**Issue by Thanh-Binh** [patrikhuber/eos#65]
@patrikhuber:
Do you have any comparison results by using different shape fitting?
- run-time?
- estimation accuracy?

**Comment by patrikhuber** [comment]
I am running some accuracy comparisons, but it will be a while until there is something presentable.

I have not done run-time comparisons but ceres is pretty fast too. From what I observed so far I'd say it's slower than the linear shape estimate (which is of course expected), but if you add the time for shape, blendshape and pose estimate, and compare it with ceres (which can do all in one nonlinear optimisation), they might be similar.
