### ISSUE TITLE
The coffecients for eigen vectors are small

### ISSUE THREAD

**Issue by sreesreenu** [patrikhuber/eos#66]
I am trying to extend the face reconstruction to a full head. For my pca model of the head, the eigen vectors are very small in magnitude, ie i am expecting to get the parameters in the range [200-500] to bring in proper shape change. While running the code, the params generated are still less than 1.0 . Is these something specific i have to do while using a different PCA model?

**Comment by patrikhuber** [comment]
Hi! Sorry, somehow I missed the email notification about your issue.

I'm not sure what parameters you're referring to in each sentence, and when you are talking about the eigenvectors, and when about the eigenvalues or even the PCA coefficients. If you clarify, I might be able to help.

In general, no, there's nothing specific you need to do when using a different PCA model. If your vertices are in different units than the Surrey Face Model, then you might need to change the scaling of the camera (or the vertices).

**Comment by patrikhuber** [comment]
I'll close this, feel free to reopen if you're still working on it and have issues. It's very unlikely an issue with eos though, I think you just need to get your model right :-)
