### ISSUE TITLE
 I try to run fit-model according the instruction in VS2015, but failed. Please give me some help.

### ISSUE THREAD

**Issue by JeanGm2016** [patrikhuber/eos#67]
![image](https://cloud.githubusercontent.com/assets/23193053/19893356/2e2a0058-a049-11e6-9139-347ae33f4b88.png)

**Comment by patrikhuber** [comment]
Probably you're just giving wrong paths for the input arguments. Have you read this from the README.md?

> After make install or running the INSTALL target, an example image with landmarks can be found in install/bin/data/. The model and the necessary landmarks mapping file are installed to install/share/.

> You can run the example just by running:

> fit-model

> Or, by manually specifying the face model, landmark-to-vertex mappings, an image and its 2D landmarks:

> fit-model -m ../share/sfm_shape_3448.bin -p ../share/ibug2did.txt -i data/image_0010.png -l data/image_0010.pts

Todo for myself: I really need to improve the error messages.

**Comment by JeanGm2016** [comment]
After make install or running the INSTALL target, an example image with landmarks are automaticly installed in my c:/program files/eos/bin/data/.  I changed the path name eos to install, but the problem still is same.
![image](https://cloud.githubusercontent.com/assets/23193053/19900111/b5798146-a062-11e6-97f2-da196cbd8e96.png)

**Comment by patrikhuber** [comment]
Your mistake is exactly what the error says: `unrecognised option '-1'`. The option is `-l`.
