### ISSUE TITLE
How do I get 68 Landmarks points of any image in ibug format?

### ISSUE THREAD

**Issue by farazirfan47** [patrikhuber/eos#69]
I want to get 68 landmarks points of any 2D image in ibug format and create .pts file,So that I am able to create 3D Model of any image except than ibug dataset.
Is there any library or program that can extract 68 landmarks point form any 2d image of face in ibug format?

**Comment by patrikhuber** [comment]
I think dlib has a model with the 68 ibug points. Just check the ibug page, some recent publications or Google.
