### ISSUE TITLE
Can your 3D morphable model be used to fit to 3D range images?

### ISSUE THREAD

**Issue by qwzlh** [patrikhuber/eos#70]
Hello, I want to use Intel realsense and 3dmm to reconstruct human face, can this this 3dmm be used to fit range face image?

**Comment by patrikhuber** [comment]
Hi!
I haven't really worked with range or depth images, so I don't know. You can certainly use parts of the eos library to interface with the statistical face model, but I think for the actual range-image fitting you need other algorithms. Maybe PCL can help?

**Comment by qwzlh** [comment]
Thanks for answering, Yeah, I also have downloaded other lib like PCL and  I am reading some relative papers. I wish I would succeed.

**Comment by LeeTaiTai** [comment]
@qwzlh do you solve the fitting to depth images?
