### ISSUE TITLE
nanoflann.hpp

### ISSUE THREAD

**Issue by sunjunlishi** [patrikhuber/eos#72]
where is nanoflann.hpp?

**Comment by patrikhuber** [comment]
It's in the repo? Please read the readme:

> Make sure to clone with --recursive to download the required submodules!

and the release notes:

> Make sure to clone the repository with git clone --recursive, or, if you're updating, run git submodule update --init!

If that doesn't fix it, there might be an issue, but it looks fine in the repo and CI passes.
