### ISSUE TITLE
Blendshapes of the 16k vertex model produce faulty shapes

### ISSUE THREAD

**Issue by patrikhuber** [patrikhuber/eos#73]
This problem has been discovered by a user of the 4dface repo, however, I'd like to track this in eos as well, since it mainly applies to eos: https://github.com/patrikhuber/4dface/issues/12

**Comment by wpk-** [comment]
Fixed.
https://github.com/patrikhuber/4dface/issues/12#issuecomment-358682729

**Comment by patrikhuber** [comment]
Thank you @wpk-! I'll post your reply from the other thread here:

> The blendshape file for the 16k model (expression_blendshapes_16759.bin) has been updated on the University of Surrey licence server. This should fix the issue.

Cheers :)
