### ISSUE TITLE
Python bindings: load model error with eos.morphablemodel.load_model

### ISSUE THREAD

**Issue by YadiraF** [patrikhuber/eos#74]
After building the blindings, I got eos.so in install/bin, and can import eos without error.

However, when I run your example codes in the install/bin directory:
```
import eos
import numpy as np
model = eos.morphablemodel.load_model("../share/sfm_shape_3440.bin")
```
It occurs:
_RuntimeError: Error opening given file: ../share/sfm_shape_3440.bin_

Please help me, thanks !

**Comment by Larumbergera** [comment]
You are using "sfm_shape_3440.bin" and the model is "sfm_shape_3448.bin". Try to use the correct model.

Regards.

**Comment by YadiraF** [comment]
@Larumbergera  Oh, it works, I am so careless!  Thanks a lot !

**Comment by Larumbergera** [comment]
You're welcome.

The python example code seems to be wrong.

**Comment by patrikhuber** [comment]
I've just fixed the typo in the readme - no idea how the "3440" got in there!

Thank you very much for reporting it :-)
