### ISSUE TITLE
Draw mesh around face

### ISSUE THREAD

**Issue by esmartlabs** [patrikhuber/eos#76]
Can you please point to a code segment that draws the mesh around the face? 

Also can eos be run on mobile devices in real time?

**Comment by Larumbergera** [comment]
[draw_wireframe()](https://github.com/patrikhuber/eos/blob/master/examples/fit-model.cpp#L231)

**Comment by patrikhuber** [comment]
Exactly, thanks @Larumbergera.
@esmartlabs, yes, the pose and shape fitting takes only a few milliseconds, that should definitely work.

**Comment by esmartlabs** [comment]
Thanks @Larumbergera @patrikhuber - worked!
