### ISSUE TITLE
Get back 2d image from 3d model and texture map

### ISSUE THREAD

**Issue by vidit09** [patrikhuber/eos#78]
Hi Patrik

I'm using the library for fitting but also would like generate 2D image using genrated Mesh and Isomap. I've tried using the render method in render.hpp for this task but I'm not getting a proper 2d image rather image similar to the isomap. Could you please tell what does render function exactly do? Also I've tried with different model view projection values but couldn't get proper 2d image. Any suggestions in this regard will be helpful.

Thanks
Vidit

**Comment by patrikhuber** [comment]
Hi,

You can have a look at how 4dface uses the `render::render()` function: https://github.com/patrikhuber/4dface/blob/master/apps/4dface.cpp#L235

If you want a frontal face, you can just set the modelview matrix to a 4x4 identity matrix.

Hope that helps!

**Comment by vidit09** [comment]
Thanks Patrik. It works now!!

**Comment by siarez** [comment]
I have the same question. How to do this in Python?

**Comment by patrikhuber** [comment]
Just have a look at the python/demo.py example in the eos repository, you can fit and extract texture there. Then, use OpenGL or any other rendering library in Python to render the mesh in Python in whichever way you'd like. See also https://github.com/patrikhuber/eos/issues/294.

**Comment by sicilyliulc** [comment]
> Hi,
> 
> You can have a look at how 4dface uses the `render::render()` function: https://github.com/patrikhuber/4dface/blob/master/apps/4dface.cpp#L235
> 
> If you want a frontal face, you can just set the modelview matrix to a 4x4 identity matrix.
> 
> Hope that helps!

hi, when i use eos.render.render(mesh, model_view_matrix,projection_matrix, image_height, image_width) get a 2d picture,but it get error ,python=3.7  eos-py==1.1.2
AttributeError: module 'eos.render' has no attribute 'render'
