### ISSUE TITLE
How to remove these white area from both sides of the isomap?

### ISSUE THREAD

**Issue by farazirfan47** [patrikhuber/eos#79]
Here is the image 
![dest](https://cloud.githubusercontent.com/assets/21068373/21465822/656ff360-c9d4-11e6-8d8a-efb740fd0b90.jpg)

and here is the generated 3D Model 
![untitled](https://cloud.githubusercontent.com/assets/21068373/21465826/8c444180-c9d4-11e6-9b11-0d1fa75e010d.png)

Model isomap also have back wall white area behind the face.I don't want to get this white area while creating texture and just want to get the face region only skin texture.How can I get rid of this white area?

**Comment by patrikhuber** [comment]
Can you state which exact eos version you're using? And show the landmarks you've used?

**Comment by farazirfan47** [comment]
I am using eos version 0.7.0 and dlib version 19.2 for landmark detection.Is there something wrong with dlib detection library?

**Comment by patrikhuber** [comment]
dlib is fine for landmark detection and works well with eos. :-)

Please upgrade eos to a recent version, you can see in the [changelog](https://github.com/patrikhuber/eos/releases) that there have been many improvements in the fitting, which will also solve your problem.

**Comment by farazirfan47** [comment]
Ok thanks.
