### ISSUE TITLE
Problem in compiling using CMake

### ISSUE THREAD

**Issue by mortezab** [patrikhuber/eos#8]
Hi Patrik,

Thanks for sharing your codes. I'm trying to generate Visual Studio 2015 version of your code using CMake 3.3.1.
I've used your compiled Opencv and Boost libraries.
When I configure using CMake it fails with below error:

[Found the following Boost libraries:
  system
Boost found at D:/boost_1_58_0-vc14_64/include
CMake Error at D:/Programming/Programming_Morteza/cmake_3.3/share/cmake-3.3/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find Eigen3 (missing: EIGEN3_INCLUDE_DIR EIGEN3_VERSION_OK)
  (Required is at least version "2.91.0")
Call Stack (most recent call first):
  D:/Programming/Programming_Morteza/cmake_3.3/share/cmake-3.3/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindEigen3.cmake:76 (find_package_handle_standard_args)
  CMakeLists.txt:81 (find_package)

Configuring incomplete, errors occurred!]

I guess It is related to my Boost variables settings.
I've copied Boost to my D drive and defined BOOSTROOT="D:\boost_1_58_0-vc14_64" in system variables path.

Would you please help me? 
Thanks

**Comment by patrikhuber** [comment]
Hi,

Thanks for your interest!

Can you try the following?

In `initial_cache.cmake` (you can copy the template from `initial_cache.cmake.template`):
`set(BOOST_ROOT     "C:/boost/boost_1_58_0/install"    CACHE STRING "Boost search location" FORCE)`

I think you're missing Eigen as well, so:
`set(EIGEN3_INCLUDE_DIR "C:\\eigen\\eigen-bdd17ee3b1b3\\" CACHE STRING "Directory of the Eigen3 headers" FORCE)`

The paths may be slightly different on your system.

Then, run cmake with
`cmake -C ..\eos\initial_cache.cmake -G ...` and whatever the rest of your options are.

Let me know if that works.

**Comment by mortezab** [comment]
Thanks for your reply. Yes, I've not installed Eigen. It was not in list of needed dependencies. I've download it and CMake works successfully.
It encountered to some errors in visual studio. I think it is related to lib references. I'll check it and let you know the results.

Thanks again

**Comment by patrikhuber** [comment]
Ah, you're right! I added a new algorithm two weeks ago that needs `EIgen::LevenbergMarquardt`, and I didn't update the documentation. Eigen is header-only though so it's very convenient to include. I'll update the documentation, thanks!

I haven't had lib references issues so far, I think it most likely must still be some issue with your Boost or OpenCV setup. Let me know how it goes.

**Comment by zhr69** [comment]
It works :-) 
As you mentioned it was related to my Boost and OpenCV setup. SO THANKS.

**Comment by patrikhuber** [comment]
Cool, glad to hear it! I'll close this issue then :-)
