### ISSUE TITLE
Eigen3-nnls error.

### ISSUE THREAD

**Issue by farazirfan47** [patrikhuber/eos#80]
I got these error while building the fit-model see below
![out isomap](https://cloud.githubusercontent.com/assets/21068373/21467346/1840b060-ca0c-11e6-883d-bb93da7e1db1.png)

How to get rid of these error.

**Comment by patrikhuber** [comment]
Did you follow the instructions

> make sure to clone the repository with git clone --recursive, or, if you're updating, run git submodule update --init --recursive

? If that's not the issue, then you need to inspect the error log more closely and use your best judgement to pinpoint the error more closely. Please see the readme file and appveyor.yml for how to build. Please use Stackoverflow for issues with your system, your configuration or build-setup, as this is not an `eos` library issue. `eos` builds successfully on AppVeyor and travis-ci.
