### ISSUE TITLE
Debug Assertion Failed! Expression: __acrt_first_block == header

### ISSUE THREAD

**Issue by wguo68** [patrikhuber/eos#88]
The fit will crash when run the line of  "return { current_mesh, rendering_params }; "at the end of the function fit_shape_and_pose:

inline std::pair<render::Mesh, fitting::RenderingParameters> fit_shape_and_pose(const morphablemodel::MorphableModel& morphable_model, const std::vector<morphablemodel::Blendshape>& blendshapes, const core::LandmarkCollection<cv::Vec2f>& landmarks, const core::LandmarkMapper& landmark_mapper, int image_width, int image_height, const morphablemodel::EdgeTopology& edge_topology, const fitting::ContourLandmarks& contour_landmarks, const fitting::ModelContour& model_contour, int num_iterations = 5, boost::optional<int> num_shape_coefficients_to_fit = boost::none, float lambda = 3.0f)
{
	std::vector<float> pca_coeffs;
	std::vector<float> blendshape_coeffs;
	std::vector<cv::Vec2f> fitted_image_points;
	return ****fit_shape_and_pose****(morphable_model, blendshapes, landmarks, landmark_mapper, image_width, image_height, edge_topology, contour_landmarks, model_contour, num_iterations, num_shape_coefficients_to_fit, lambda, boost::none, pca_coeffs, blendshape_coeffs, fitted_image_points);
};

**Comment by patrikhuber** [comment]
This looks like an issue with your system, and nothing to do with `eos`. Check your build and system configuration. Also, it's not possible to investigate without further details.

**Comment by wguo68** [comment]
I am using vs2015 and build ceres,glog,gflags also in vS2015.  Is it because gflags  is static lib?

**Comment by patrikhuber** [comment]
As mentioned I'm pretty sure this is an issue on your system, and not a problem in eos. It's hard to help without more details. Can you run the INSTALL target and run from the install-dir, to make sure all paths are correct? Also check this in the debugger, and then check the variables before returning - i.e. did the function get all the correct arguments and do something "useful" with it?

Could it be you're running out of memory? Can you try 64-bit compilation?

**Comment by wguo68** [comment]
I build alll in 64-bit such as opencv, boost, glog,gflags,ceres and eos using CMake now.  I don't know check this in the debugger.  Just when I return the paired mesh and rendering_params .

**Comment by patrikhuber** [comment]
If you just compile `fit-model`, and/or use `fit_shape_and_pose`, you don't need any of glog, gflags or ceres. These have nothing to do with it at all. In fact `BUILD_CERES_EXAMPLE` should be `off` by default so you shouldn't need any of these.

**Comment by wguo68** [comment]
Thank you very much.
