### ISSUE TITLE
Removing dependency on Boost

### ISSUE THREAD

**Issue by wguo68** [patrikhuber/eos#89]
Boost is too large and complex and hard to find it. Cmake always hard to find it because I have installed another boost version boost1.5.0. Although I finally make it work.

I think eos should depend little thirdparty libs so as to it be easy to use.

**Comment by patrikhuber** [comment]
This is kind of planned when VS2017 is released - we will switch to VS2017 and should then be able to remove boost. Note that the core of eos doesn't need much of boost, it's only `boost::optional` and a few other small things. It is mainly the example applications that use boost.

Note that it's really easy to use boost, if you're having difficulties, you're most likely doing something wrong. In Linux it's just `apt-get` and in Windows, just download the binaries, see [here](https://github.com/patrikhuber/eos/blob/master/initial_cache.cmake.template#L3-L8).

**Comment by wguo68** [comment]
Thank you . I have compiled and build  everything. However there is still error:
![eoserr](https://cloud.githubusercontent.com/assets/4994038/21564872/0c49f572-cecc-11e6-85c6-804b71e85af6.jpg)

**Comment by wguo68** [comment]
I also think eos should depend little thirdparty libs so as to it be easy to use.

**Comment by Iragne** [comment]
+1 ;)

**Comment by patrikhuber** [comment]
I'm definitely looking forward to this too! Just waiting for VS2017 final to be released and for some additional tooling to be compatible with it (e.g. ImageWatch).

Hopefully soon! :-)

**Comment by NextDesign1** [comment]
You can pull out just the bits of boost that you need with bcp: http://www.boost.org/doc/libs/1_53_0/tools/bcp/doc/html/index.html

**Comment by patrikhuber** [comment]
@NextDesign1 I know, thanks. I heard that it's not ideal either though because boost has so many interdependencies, so basically you use boost feature X, and it pulls in the headers from Y, Z, A and B.

Anyway it might be an option. But in fact eos doesn't require much of boost, mainly `optional`, as mentioned above, which is already in C++17 and most recent compilers support it. So I think it's only a matter of a few weeks or a few months until I completely remove it from the library. :-)

**Comment by patrikhuber** [comment]
There is now a version in the `devel` branch that has removed all dependency on boost from the library. Some apps still need boost.

Note however that I do not recommend using that branch yet - it is **highly** experimental and only the python bindings and fit-model compile - **the rest does not compile (yet)**. Use at your own risk for now.

I will update & close this ticket once this is "production-ready", probably 4-6 weeks but take the estimate with a grain of salt please. There will also be a new release eventually (v0.13.0 probably).

**Comment by patrikhuber** [comment]
The core of the eos library does not need Boost and OpenCV anymore. These changes are merged into master and in release v0.13.0.
