### ISSUE TITLE
Runtime of estimate_orthographic_camera

### ISSUE THREAD

**Issue by patrikhuber** [patrikhuber/eos#9]
`estimate_orthographic_camera()` reportedly takes around 65ms to execute, which I believe is too much, it should be way faster. Have to measure & profile it on my system.
(the system in question is probably VS2013 x64)

**Comment by Thanh-Binh** [comment]
from my last test, it depends on number of points: 65ms by 1000 points, but 40ms by 800 points.

**Comment by patrikhuber** [comment]
Ah of course, you're using it with the OF, so you have a lot of points. I tested it with 20 to 100 points. I'll have a look as soon as I can.

What about if you just drop half the points in the meantime? I think the pose estimate might be very similar.

**Comment by patrikhuber** [comment]
I'll close this, as there is now [fitting::estimate_orthographic_projection_linear()](https://github.com/patrikhuber/eos/blob/devel/examples/fit-model.cpp#L191), a closed-form algorithm for estimating the camera!

If anyone is using the other function and still worried with the speed, we can always reopen this, but actually I think 65ms might be OK, it's nonlinear optimisation, so it won't be blazingly fast.
