### ISSUE TITLE
About the ibug2did file

### ISSUE THREAD

**Issue by helloyxc** [patrikhuber/eos#90]
I have read the paper you write for the project. But I don't find a method to generate ibug2did file.

for example, why the right eye, 37th landmark, map to 177th vertex in reference.obj, but don't map to the other vertex around 177th vertex in reference.obj?
	37   177 ; right eye outer-corner (1)
	38   172 ; right eye pupil top right (from subject's perspective)
	39   191 ; right eye pupil top left
	40   181 ; right eye inner-corner (5)
	41   173 ; right eye pupil bottom left
	42   174 ; right eye pupil bottom right

What paper or link introduce how the ibug2did file map the landmark in pts file to vertex in model?

In the other word, what's the best way to use reference.obj to  generate ibug2did file if I only have reference.obj?

**Comment by patrikhuber** [comment]
Please read the documentation at the top of the file: https://github.com/patrikhuber/eos/blob/master/share/ibug2did.txt#L1-L2

Usually, the correspondences for a new landmark scheme need to be defined once, manually. You open the reference.obj in a 3D viewer like Blender or MeshLab, and look for the correct vertex ID, given a 2D landmark point from your landmark scheme.

> why the right eye, 37th landmark, map to 177th vertex in reference.obj, but don't map to the other vertex around 177th vertex in reference.obj?

Sorry, I don't understand this question.

**Comment by helloyxc** [comment]
Thank you! I know how to do.
