### ISSUE TITLE
How to modify PCA Color Coefficient??

### ISSUE THREAD

**Issue by codediner** [patrikhuber/eos#91]
Hi Patrik, firstly thank you very much for the job you have done, it works prefectly and I really appreciate it.
  
However I have a problem when I want to modify PCA color coefficients, for the PCA shape coefficients, I can modify them in fitting.hpp and can reset them in generate object.cpp, and the result seems like your presentation in your papar but for the PCA color coefficients, I didn't find where to modify them to produce the same result as yours.

And the second question, can the face model be modified as the video shows with the modificatin of PCA shape coefficients and color coefficients? https://www.youtube.com/watch?v=nice6NYb_WA&t=17s

Thank you en avance for your answer.

Sincerely

**Comment by patrikhuber** [comment]
Hi, thank you very much!

First of all, are you using a model that contains colour PCA information? As mentioned in the readme, the public one contains only shape. It gives a link for you with information on how to obtain the colour model.

Assuming you are using a model with colour PCA, it works exactly the same, it's easiest to use `draw_sample(...)` on the Morphable Model to get a random sample of both shape **and** colour. You can also specify the coefficients by yourself.

As for your linked video, sure, the technique is the same, you can do that easily with eos. Just use `draw_sample` with specific coefficients, for example, set the first one to 1 or 2, and the reset to zero. It's how we generated the figures for the VISAPP paper.

I'm tagging this as invalid for now as I don't think there is an actual issue with eos.

**Comment by codediner** [comment]
Thank you very much for your answer, I think I have taken the wrong model.

**Comment by patrikhuber** [comment]
Good, will close this then :-)
