### ISSUE TITLE
fit-model-ceres: Segmentation fault

### ISSUE THREAD

**Issue by rayjs** [patrikhuber/eos#97]
Hi Patrik,

It seems `fit-model-ceres` seg faults, I have tried it with multiple images and it seg faulted each time.

`$ ./fit-model --image=data/image_034_1.jpg --landmarks=data/image_034_1.pts
Finished fitting and wrote result mesh and isomap to files with basename "out".`
`$ ./fit-model-ceres --image=data/image_034_1.jpg --landmarks=data/image_034_1.pts`
`iter      cost      cost_change  |gradient|   |step|    tr_ratio  tr_radius  ls_iter  iter_time  total_time`
   `0  2.259531e+05    0.00e+00    1.11e+04   0.00e+00   0.00e+00  1.00e+04        0    2.37e-02    2.37e-02
   1  1.789614e+04    2.08e+05    1.57e+03   2.78e+01   9.79e-01  3.00e+04        3    4.98e-02    7.36e-02
   2  1.212682e+04    5.77e+03    6.10e+01   6.85e+00   1.00e+00  9.00e+04        3    4.38e-02    1.17e-01
   3  1.211898e+04    7.84e+00    8.83e-01   2.45e-01   1.00e+00  2.70e+05        3    3.78e-02    1.55e-01
Ceres Solver Report: Iterations: 4, Initial cost: 2.259531e+05, Final cost: 1.211898e+04, Termination: CONVERGENCE
Segmentation fault`

**Comment by patrikhuber** [comment]
Hi,

You'll have to debug this and see. Probably easy to solve. The `fit-model-ceres` example is not really meant to be used "out of the box" anyway, it's meant for researchers that want to work with it, as a starting point.

**Comment by rayjs** [comment]
Thanks for the reply.

**Comment by patrikhuber** [comment]
Did you solve this?

**Comment by rayjs** [comment]
No, I did not look into it anymore.

**Comment by patrikhuber** [comment]
I'm pretty sure I know why you got a segfault. You've probably ran fit-model-ceres with the default model from the repo (sfm_shape_3448.bin), which doesn't contain a colour (albedo) model. See the [note in fit-model-ceres.cpp](https://github.com/patrikhuber/eos/blob/master/examples/fit-model-ceres.cpp#L127-L130).

I've added more explicit checks and errors in the current devel branch: 45479bb25a5f2d8974a5e42f24b539d606491d96.

This should fix all the segfaults.
