### ISSUE TITLE
Texturing the inside of the mouth

### ISSUE THREAD

**Issue by manish-grafty** [patrikhuber/eos#99]
Hi Patrick,
Is there a way to preserve the mouth region when the 3-d face is generated?

e.g. the following 2-D image generates the below 3-d model. However I would like all the mouth features preserved:

![i2](https://cloud.githubusercontent.com/assets/11373335/22504054/6bfd7860-e829-11e6-949c-0f323f8fb7a2.jpg)

![i2-3d](https://cloud.githubusercontent.com/assets/11373335/22504140/cff18aa0-e829-11e6-9c81-44cc78647f98.jpg)

**Comment by patrikhuber** [comment]
Hi,

I suppose you mean the interior of the mouth? Our mesh doesn't include the interior of the mouth. You have some choices how to do that: Add the interior of the mouth to the 3D mesh (I think for example the BFM includes the mouth interior). Alternatively, you could model it in 2D, you could get some inspiration from how the people of the [face2face paper](http://www.graphics.stanford.edu/~niessner/papers/2016/1facetoface/thies2016face.pdf) did it.
